### ISSUE TITLE
Invalid bucket name

### ISSUE THREAD

**Issue by sowmya-accenture** [aws/amazon-sagemaker-examples#1021]
When I am trying the Data analysis part of xgboost with built in rules it is throwing 

_Parameter validation failed:
Invalid bucket name "sagemaker-us-east-1\demo-smdebug-xgboost-regression-2020-02-06-08-50-55-102\debug-output": Bucket name must match the regex "^[a-zA-Z0-9.\-_]{1,255}$" or be an ARN matching the regex "^arn:(aws).*:s3:[a-z\-0-9]+:[0-9]{12}:accesspoint[/:][a-zA-Z0-9\-]{1,63}$"_

**Comment by aaronmarkham** [comment]
Are those pipes in the bucket name? Certainly looks like it... those don't match the regex filter.

**Comment by mchoi8739** [comment]
Let us know if this issue still needs assist. And also providing the link to the notebook you used can be helpful to resolve this issue.

**Comment by mchoi8739** [comment]
After testing the Debugger for XGBoost training notebooks, I decided to retire the notebook ([Debugging XGBoost Training Jobs with Amazon SageMaker Debugger Using Rules](https://github.com/aws/amazon-sagemaker-examples/blob/master/sagemaker-debugger/xgboost_census_explanations/xgboost-census-debugger-rules.ipynb)) that seems what you mentioned in this issue.

Instead, use the [Explainability with Amazon SageMaker Debugger](https://github.com/aws/amazon-sagemaker-examples/blob/master/sagemaker-debugger/xgboost_census_explanations/xgboost-census-debugger-rules.ipynb) notebook that has fully functioning examples and extended analysis.
