### ISSUE TITLE
images_per_epochs hyper-parameter in Tensorpack  mask-rcnn training image is hard-coded to 120000

### ISSUE THREAD

**Issue by ajayvohra2005** [aws/amazon-sagemaker-examples#1027]
`images_per_epochs` hyper-parameter used in notebooks under https://github.com/awslabs/amazon-sagemaker-examples/tree/master/advanced_functionality/distributed_tensorflow_mask_rcnn does not work for Tensorpack training image. It is hardcoded to 120000 images in `container/resources/train.py`. This works for COCO 2017 dataset, but it does not work for other datasets.

**Comment by seanpmorgan** [comment]
Closing issue linked to PR #1078
