### ISSUE TITLE
Distributed Mask RCNN training images have hard coded  ResNET backbone pre-trained model path

### ISSUE THREAD

**Issue by ajayvohra2005** [aws/amazon-sagemaker-examples#1029]
The distributed Mask RCNN containers under https://github.com/awslabs/amazon-sagemaker-examples/tree/master/advanced_functionality/distributed_tensorflow_mask_rcnn have hard-coded path for pre-trained ResNet model used to initialize ResNet backbone. The hard coded path in `container/resources/train.py` uses `ImageNet-R50-AlignPadding.npz`. The back-bone pre-trained model needs to be configurable.

**Comment by seanpmorgan** [comment]
Closing issue linked to PR #1078
