### ISSUE TITLE
Distributed Mask RCNN examples using EFS/FSx for data source don't use EFS/FSx for output logs

### ISSUE THREAD

**Issue by ajayvohra2005** [aws/amazon-sagemaker-examples#1030]
The distributed Mask-RCNN example notebooks under https://github.com/awslabs/amazon-sagemaker-examples/tree/master/advanced_functionality/distributed_tensorflow_mask_rcnn that use EFS/FSx for data source don't write model output logs, checkpoints, and Tensorboard event summaries to EFS/FSx. The model output logs are being written to S3 instead, which works, but it does not make logs accessible in real-time from EFS/FSx while the training is going on.

**Comment by seanpmorgan** [comment]
Closing issue linked to PR #1078
