### ISSUE TITLE
Update to JupyterLab 2.0

### ISSUE THREAD

**Issue by tibdex** [aws/amazon-sagemaker-examples#1071]
The JupyterLab team [released version 2.0](https://jupyterlab.readthedocs.io/en/stable/getting_started/changelog.html#v2-0-0), do you know when it will become the default version on SageMaker (and SageMaker Studio)?

Thanks!

**Comment by samuelsinayoko** [comment]
Any update on this??

**Comment by tibdex** [comment]
JupyterLab 3 is right around the corner.

**Comment by cornhundred** [comment]
@jasongrout @jtpio would you all happen to know if there are any examples if setting up Jupyter lab 2.0 or 3.0 on Sagemaker using lifecycle management?

**Comment by jtpio** [comment]
@cornhundred I haven't used sagemaker for a very long time so can't really say if it's possible to use lifecycle management for this.

**Comment by cornhundred** [comment]
thanks for the feedback @jtpio :)

**Comment by naterush** [comment]
Any update on if upgrading to JupyterLab 2.0 is possible in sagemaker? Thanks for any info!

**Comment by jbeyer16** [comment]
Yes would love to see 2 or 3 on Sagemaker soon!

**Comment by karrtikiyerkcm** [comment]
Is there a way to manually upgrade it to 3.0 via say onstart script configured in lifecycle of notebook instance? Does that work?

**Comment by dsaid-xj** [comment]
you can't manually upgrade it to 3.0 on sagemaker according to AWS support. I've tried nonetheless, but it doesn't work.

**Comment by quetil** [comment]
Hi, did someone manage to update manually jupyterlab ? Thanks again

**Comment by chrisranderson** [comment]
I've tried `pip install --upgrade jupyterlab`. It installs, but then when I try to access JupyterLab from the AWS console, it fails. Restarting my instance reverts to the old version.

**Comment by jkroll-aws** [comment]
As of June 2022, Jupyter Lab 3 is available on SageMaker notebook instances and Studio.

https://aws.amazon.com/blogs/machine-learning/amazon-sagemaker-studio-and-sagemaker-notebook-instance-now-come-with-jupyterlab-3-notebooks-to-boost-developer-productivity/
