### ISSUE TITLE
How does `getting_started` example work?

### ISSUE THREAD

**Issue by avshyz** [aws/amazon-sagemaker-examples#1110]
in `xgboost_customer_churn_studio.ipynb`, it seems as if nowhere in the code is specified which one of the attributes is the predicted label. 

How does the estimator infer that kind of information? Is it assumed the first label in the dataset is the label?

**Comment by seanpmorgan** [comment]
Hi @avshyz apologies for the slow response. I'm not 100% sure which notebook you're referring to but our customer churn examples are classification problems which evaluate a tabular feature set. The returned values from the predictor are probabilities corresponding to the predicted class for the entire array.

The cell after the predictions uses np.round() to turn them into classifications. This means >0.5 == class 1 and vice versa.

https://github.com/aws/amazon-sagemaker-examples/blob/master/introduction_to_applying_machine_learning/xgboost_customer_churn/xgboost_customer_churn.ipynb

Please let us know if there are more questions and we can re-open
