### ISSUE TITLE
scikit-bring-your-own notebook is broken + switch to python3

### ISSUE THREAD

**Issue by misclassified** [aws/amazon-sagemaker-examples#1146]
Hi,

the notebook 'scikit-bring-your-own' is not working correctly. I believe the problem is the path set in the Dockerfile. It's currently opt/program which is in conflict with what the notebook states and in conflict with the pointers in container/train file. 

I believe something happened when you added the batch transform job part.

Also, why is the dockerfile building python 2.7 and not python 3?

**Comment by nadiaya** [comment]
This is a very old example.

Can you tell us more about your use case?
Any particular reason why are you trying to use bring your own scikit image instead of using official one (https://github.com/aws/sagemaker-scikit-learn-container) ?

**Comment by Wei-1** [comment]
Please update this example, we need an example that can host python3 models so that we can modify the code to host our own stuff in whatever libraries.

**Comment by seanpmorgan** [comment]
This has merged:
https://github.com/aws/amazon-sagemaker-examples/pull/1971
