### ISSUE TITLE
Undefined variable in pytorch_mnist.ipynb

### ISSUE THREAD

**Issue by namheegordonkim** [aws/amazon-sagemaker-examples#1214]
https://github.com/awslabs/amazon-sagemaker-examples/blob/7262f9eca92a612423dba16595161c2a473b771e/sagemaker-python-sdk/pytorch_mnist/pytorch_mnist.ipynb#L232

The variable `data` was never defined and thus the last cell before the cleanup section cannot run.

**Comment by hsl89** [comment]
@welkinwalker and @namheegordonkim thanks for using SageMaker, we fixed this issue in this PR #1692
