### ISSUE TITLE
UnexpectedStatusException: Error for Training job sagemaker-pytorch-Failed. Reason: AlgorithmError: framework error: 

### ISSUE THREAD

**Issue by Vertika09** [aws/amazon-sagemaker-examples#1224]
whenever I try to train my model by creating Jupyter notebook instance in Sagemaker my training jobs gets failed and I get below error. The hyperparameters passed to training script is as follows:

```python
from sagemaker.pytorch import PyTorch

estimator = PyTorch(entry_point="train.py",
                    source_dir="train",
                    role=role,
                    framework_version='0.4.0',
                    train_instance_count=1,
                    train_instance_type='ml.p2.xlarge',
                    hyperparameters={
                        'epochs': 10,
                        'hidden_dim': 200,
                    })
```

Error:

```
UnexpectedStatusException: Error for Training job sagemaker-pytorch-2020-05-18-15-06-40-726: Failed. Reason: AlgorithmError: framework error: 
Traceback (most recent call last):
File "/usr/local/lib/python3.6/dist-packages/sagemaker_containers/_trainer.py", line 76, in train
entrypoint()
File "/usr/local/lib/python3.6/dist-packages/sagemaker_pytorch_container/training.py", line 98, in main
train(framework.training_env())
File "/usr/local/lib/python3.6/dist-packages/sagemaker_pytorch_container/training.py", line 52, in train
capture_error=True)
File "/usr/local/lib/python3.6/dist-packages/sagemaker_containers/_modules.py", line 274, in run_module
files.download_and_extract(uri, env.code_dir)
File "/usr/local/lib/python3.6/dist-packages/sagemaker_containers/_files.py", line 124, in download_and_extract
s3_download(uri, dst)
File "/usr/local/lib/python3.6/dist-packages/sagemaker_containers/_files.py", line 159, in s3_download
s3.Bucket(bucket).download_file(key, dst)
File "/usr/local/lib/python3.6/dist-packages/boto3/s3/inject.py", line 246, in bucket_download_file
ExtraArgs=
```

**Comment by laurenyu** [comment]
hi @Vertika09, could you include your full stacktrace and error message? From what you've provided, it looks like something went wrong with downloading from S3, but there's no way to tell what happened beyond that based on the information you've provided.

**Comment by Vertika09** [comment]
@laurenyu Hi 
below is the stacktrace

2020-05-27 11:37:38 Starting - Starting the training job...
2020-05-27 11:37:41 Starting - Launching requested ML instances......
2020-05-27 11:38:54 Starting - Preparing the instances for training.........
2020-05-27 11:40:19 Downloading - Downloading input data...
2020-05-27 11:41:01 Failed - Training job failed
..
---------------------------------------------------------------------------
UnexpectedStatusException                 Traceback (most recent call last)
<ipython-input-2-108999b28458> in <module>()
----> 1 estimator.fit({'training': 's3://lum-ver/train.csv'})

~/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/sagemaker/estimator.py in fit(self, inputs, wait, logs, job_name, experiment_config)
    475         self.jobs.append(self.latest_training_job)
    476         if wait:
--> 477             self.latest_training_job.wait(logs=logs)
    478 
    479     def _compilation_job_name(self):

~/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/sagemaker/estimator.py in wait(self, logs)
   1084         # If logs are requested, call logs_for_jobs.
   1085         if logs != "None":
-> 1086             self.sagemaker_session.logs_for_job(self.job_name, wait=True, log_type=logs)
   1087         else:
   1088             self.sagemaker_session.wait_for_job(self.job_name)

~/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/sagemaker/session.py in logs_for_job(self, job_name, wait, poll, log_type)
   3042 
   3043         if wait:
-> 3044             self._check_job_status(job_name, description, "TrainingJobStatus")
   3045             if dot:
   3046                 print()

~/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/sagemaker/session.py in _check_job_status(self, job, desc, status_key_name)
   2636                 ),
   2637                 allowed_statuses=["Completed", "Stopped"],
-> 2638                 actual_status=status,
   2639             )
   2640 

UnexpectedStatusException: Error for Training job pytorch-training-2020-05-27-11-37-37-457: Failed. Reason: ClientError: Data download failed:403 Forbidden (403): Forbidden

**Comment by Vertika09** [comment]
@laurenyu I added AmazonS3FullAccess policy as well. Am new with Sagemaker and model training.

**Comment by Vertika09** [comment]
@laurenyu hi pls find the stacktrace and error below.

2020-05-27 12:11:57 Starting - Starting the training job...
2020-05-27 12:11:59 Starting - Launching requested ML instances.........
2020-05-27 12:13:40 Starting - Preparing the instances for training.........
2020-05-27 12:15:10 Downloading - Downloading input data...
2020-05-27 12:15:52 Training - Downloading the training image...........bash: cannot set terminal process group (-1): Inappropriate ioctl for device
bash: no job control in this shell
2020-05-27 12:17:39,277 sagemaker-containers INFO     Imported framework sagemaker_pytorch_container.training
2020-05-27 12:17:39,304 sagemaker_pytorch_container.training INFO     Block until all host DNS lookups succeed.
2020-05-27 12:17:39,308 sagemaker_pytorch_container.training INFO     Invoking user training script.
2020-05-27 12:17:39,523 sagemaker-containers ERROR    Reporting training FAILURE
2020-05-27 12:17:39,523 sagemaker-containers ERROR    framework error: 
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/sagemaker_containers/_trainer.py", line 84, in train
    entrypoint()
  File "/opt/conda/lib/python3.6/site-packages/sagemaker_pytorch_container/training.py", line 99, in main
    train(framework.training_env())
  File "/opt/conda/lib/python3.6/site-packages/sagemaker_pytorch_container/training.py", line 50, in train
    framework.modules.download_and_install(training_environment.module_dir)
  File "/opt/conda/lib/python3.6/site-packages/sagemaker_containers/_modules.py", line 159, in download_and_install
    _files.download_and_extract(uri, module_path)
  File "/opt/conda/lib/python3.6/site-packages/sagemaker_containers/_files.py", line 129, in download_and_extract
    s3_download(uri, dst)
  File "/opt/conda/lib/python3.6/site-packages/sagemaker_containers/_files.py", line 165, in s3_download
    s3.Bucket(bucket).download_file(key, dst)
  File "/opt/conda/lib/python3.6/site-packages/boto3/s3/inject.py", line 246, in bucket_download_file
    ExtraArgs=ExtraArgs, Callback=Callback, Config=Config)
  File "/opt/conda/lib/python3.6/site-packages/boto3/s3/inject.py", line 172, in download_file
    extra_args=ExtraArgs, callback=Callback)
  File "/opt/conda/lib/python3.6/site-packages/boto3/s3/transfer.py", line 307, in download_file
    future.result()
  File "/opt/conda/lib/python3.6/site-packages/s3transfer/futures.py", line 106, in result
    return self._coordinator.result()
  File "/opt/conda/lib/python3.6/site-packages/s3transfer/futures.py", line 265, in result
    raise self._exception
  File "/opt/conda/lib/python3.6/site-packages/s3transfer/tasks.py", line 255, in _main
    self._submit(transfer_future=transfer_future, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/s3transfer/download.py", line 343, in _submit
    **transfer_future.meta.call_args.extra_args
  File "/opt/conda/lib/python3.6/site-packages/botocore/client.py", line 316, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/opt/conda/lib/python3.6/site-packages/botocore/client.py", line 599, in _make_api_call
    api_params, operation_model, context=request_context)
  File "/opt/conda/lib/python3.6/site-packages/botocore/client.py", line 647, in _convert_to_request_dict
    api_params, operation_model)
  File "/opt/conda/lib/python3.6/site-packages/botocore/validate.py", line 297, in serialize_to_request
    raise ParamValidationError(report=report.generate_report())
botocore.exceptions.ParamValidationError: Parameter validation failed:
Invalid length for parameter Key, value: 0, valid range: 1-inf

Parameter validation failed:
Invalid length for parameter Key, value: 0, valid range: 1-inf

2020-05-27 12:17:50 Uploading - Uploading generated training model
2020-05-27 12:17:50 Failed - Training job failed
---------------------------------------------------------------------------
UnexpectedStatusException                 Traceback (most recent call last)
<ipython-input-2-09d7144431c1> in <module>()
----> 1 estimator.fit({'training': 's3://lum-ver/'})

~/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/sagemaker/estimator.py in fit(self, inputs, wait, logs, job_name, experiment_config)
    475         self.jobs.append(self.latest_training_job)
    476         if wait:
--> 477             self.latest_training_job.wait(logs=logs)
    478 
    479     def _compilation_job_name(self):

~/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/sagemaker/estimator.py in wait(self, logs)
   1084         # If logs are requested, call logs_for_jobs.
   1085         if logs != "None":
-> 1086             self.sagemaker_session.logs_for_job(self.job_name, wait=True, log_type=logs)
   1087         else:
   1088             self.sagemaker_session.wait_for_job(self.job_name)

~/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/sagemaker/session.py in logs_for_job(self, job_name, wait, poll, log_type)
   3042 
   3043         if wait:
-> 3044             self._check_job_status(job_name, description, "TrainingJobStatus")
   3045             if dot:
   3046                 print()

~/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/sagemaker/session.py in _check_job_status(self, job, desc, status_key_name)
   2636                 ),
   2637                 allowed_statuses=["Completed", "Stopped"],
-> 2638                 actual_status=status,
   2639             )
   2640 

UnexpectedStatusException: Error for Training job pytorch-training-2020-05-27-12-11-56-533: Failed. Reason: AlgorithmError: framework error: 
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/sagemaker_containers/_trainer.py", line 84, in train
    entrypoint()
  File "/opt/conda/lib/python3.6/site-packages/sagemaker_pytorch_container/training.py", line 99, in main
    train(framework.training_env())
  File "/opt/conda/lib/python3.6/site-packages/sagemaker_pytorch_container/training.py", line 50, in train
    framework.modules.download_and_install(training_environment.module_dir)
  File "/opt/conda/lib/python3.6/site-packages/sagemaker_containers/_modules.py", line 159, in download_and_install
    _files.download_and_extract(uri, module_path)
  File "/opt/conda/lib/python3.6/site-packages/sagemaker_containers/_files.py", line 129, in download_and_extract
    s3_download(uri, dst)
  File "/opt/conda/lib/python3.6/site-packages/sagemaker_containers/_files.py", line 165, in s3_download
    s3.Bucket(bucket).download_file(key, dst)
  File "/opt/conda/lib/python3.6/site-packages/boto3/s3/

​

**Comment by nadiaya** [comment]
The actual error message is still cut off.

Do you need to use 0.4.0 version of PyTorch?
This image has been released 2 years ago and we had numerous iterations since then.
I would recommend switching to a new PyTorch version and as a result a newer image if possible.

**Comment by Vertika09** [comment]
@nadiaya Thanks for the response....as you mentioned I have tried using other framework versions as well....but nothing seems to works

**Comment by nadiaya** [comment]
Actually i missed part with the error:
```
  File "/opt/conda/lib/python3.6/site-packages/botocore/validate.py", line 297, in serialize_to_request
    raise ParamValidationError(report=report.generate_report())
botocore.exceptions.ParamValidationError: Parameter validation failed:
Invalid length for parameter Key, value: 0, valid range: 1-inf

Parameter validation failed:
Invalid length for parameter Key, value: 0, valid range: 1-inf
```

Seems there are issues with getting source code from the s3.
What is the python SDK version are you using?
What region are you using? How big is your train folder?

**Comment by Vertika09** [comment]
Hi,
Region is US East (N. Virginia)
Am not sure about  python sdk version. If you can suggest how to get more info in this...it will be helpful.
Train folder is 22.9 MB.
hope I provided the details correct.

**Comment by Vertika09** [comment]
Hi @ChuyangDeng, thanks for the solution. 
I was able to re-install the latest version. 
Still I get the following error:
ClientError                               Traceback (most recent call last)
<ipython-input-2-9c47ff4dccae> in <module>()
----> 1 estimator.fit({'training': 's3://lumus-sagemaker/train.csv'})

~/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/sagemaker/estimator.py in fit(self, inputs, wait, logs, job_name, experiment_config)
    472         self._prepare_for_training(job_name=job_name)
    473 
--> 474         self.latest_training_job = _TrainingJob.start_new(self, inputs, experiment_config)
    475         self.jobs.append(self.latest_training_job)
    476         if wait:

~/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/sagemaker/estimator.py in start_new(cls, estimator, inputs, experiment_config)
   1036             train_args["enable_sagemaker_metrics"] = estimator.enable_sagemaker_metrics
   1037 
-> 1038         estimator.sagemaker_session.train(**train_args)
   1039 
   1040         return cls(estimator.sagemaker_session, estimator._current_job_name)

~/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/sagemaker/session.py in train(self, input_mode, input_config, role, job_name, output_config, resource_config, vpc_config, hyperparameters, stop_condition, tags, metric_definitions, enable_network_isolation, image, algorithm_arn, encrypt_inter_container_traffic, train_use_spot_instances, checkpoint_s3_uri, checkpoint_local_path, experiment_config, debugger_rule_configs, debugger_hook_config, tensorboard_output_config, enable_sagemaker_metrics)
    588         LOGGER.info("Creating training-job with name: %s", job_name)
    589         LOGGER.debug("train request: %s", json.dumps(train_request, indent=4))
--> 590         self.sagemaker_client.create_training_job(**train_request)
    591 
    592     def process(

~/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/botocore/client.py in _api_call(self, *args, **kwargs)
    314                     "%s() only accepts keyword arguments." % py_operation_name)
    315             # The "self" in this scope is referring to the BaseClient.
--> 316             return self._make_api_call(operation_name, kwargs)
    317 
    318         _api_call.__name__ = str(py_operation_name)

~/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/botocore/client.py in _make_api_call(self, operation_name, api_params)
    624             error_code = parsed_response.get("Error", {}).get("Code")
    625             error_class = self.exceptions.from_code(error_code)
--> 626             raise error_class(parsed_response, operation_name)
    627         else:
    628             return parsed_response

ClientError: An error occurred (ValidationException) when calling the CreateTrainingJob operation: No S3 objects found under S3 URL "s3://lumus-sagemaker/train.csv" given in input data source. Please ensure that the bucket exists in the selected region (us-east-1), that objects exist under that S3 prefix, and that the role "arn:aws:iam::082814126327:role/service-role/AmazonSageMaker-ExecutionRole-20200518T145771" has "s3:ListBucket" permissions on bucket "lumus-sagemaker".

**Comment by laurenyu** [comment]
@Vertika09 could you share the code used to start the training job? (i.e. `fit()`)

in addition, could you share the hyperparameters you see in the AWS console from the failed training job?

**Comment by Vertika09** [comment]
Hi @laurenyu, the code for training job is:

from sagemaker.pytorch import PyTorch
estimator = PyTorch(entry_point="train.py",
                    source_dir="s3://lum-sagemaker/train",
                    role=role,
                    framework_version='1.5.0',
                    train_instance_count=1,
                    train_instance_type='ml.p2.xlarge',
                    hyperparameters={
                        'epochs': 10,
                        'hidden_dim': 200,
                    })

estimator.fit({'training': 's3://lum-sagemaker/train.csv'})

Am unable to find hyperparameters from failed training job.

**Comment by laurenyu** [comment]
> Am unable to find hyperparameters from failed training job.

did you check in the AWS console or via the CLI? Are there more logs you can share from the beginning of the training job?

**Comment by Vertika09** [comment]
@laurenyu, I checked in the AWS console. These were the only training logs.

**Comment by laurenyu** [comment]
If I open a training job in the AWS console and scroll down, I see a section that lists the hyperparameters for the training job, e.g.

![Screen Shot 2020-06-18 at 8 47 02 AM](https://user-images.githubusercontent.com/6631887/85042715-62b0d200-b140-11ea-9af4-5fc4dfa854d1.png)

Based on the code you shared earlier, I'd expect your training job to have a handful of hyperparameters set: `epochs` and `hidden_dim` because you defined them above, as well as the `sagemaker_*` ones that are in the screenshot above. Can you show me what you see in the AWS console?

**Comment by Vertika09** [comment]
Hi @laurenyu, pls find the hyperparameters details below:

Hyperparameters
Key	Value
epochs	5
hidden_dim	20
sagemaker_container_log_level	20
sagemaker_enable_cloudwatch_metrics	false
sagemaker_job_name	"pytorch-training-2020-06-15-14-16-41-348"
sagemaker_program	"train.py"
sagemaker_region	"us-east-1"
sagemaker_submit_directory	"s3://sagemaker-us-east-1-082814126327/sagemaker/sentiment_rnn/Train"


I hope I provided the correct details that u asked for.

**Comment by laurenyu** [comment]
@Vertika09 thanks. The last stacktrace and the training code you posted don't match the other stacktraces you've shared here - is [this comment](https://github.com/awslabs/amazon-sagemaker-examples/issues/1224#issuecomment-645503937) the error you're currently dealing with?

In addition, the `sagemaker_submit_directory` hyperparameter value doesn't seem to match what the expected behavior of the estimator. If you check s3://sagemaker-us-east-1-082814126327/sagemaker/sentiment_rnn/Train, is your training script there?

**Comment by Vertika09** [comment]
@laurenyu I have been trying multiple ways to see if works, that's why the difference. Yes, the recent comment you mentioned is where I am still stuck.

Hyperparameters
Key	Value
epochs	10
hidden_dim	200
sagemaker_container_log_level	20
sagemaker_enable_cloudwatch_metrics	false
sagemaker_job_name	"pytorch-training-2020-05-27-12-49-51-805"
sagemaker_program	"train.py"
sagemaker_region	"us-east-1"
sagemaker_submit_directory	"s3://lum-ver"

**Comment by laurenyu** [comment]
`sagemaker_submit_directory "s3://lum-ver"` is more along what I was expecting with your first stacktrace/error message.

my best guess based on what you've shared is that your `source_dir` has been set incorrectly. Since you're using an S3 path for `source_dir`, can you try using an S3 path that points to a `.tar.gz` file with your source code?

it's harder to tell what could be causing what when we're mixing and matching code, hyperparameters, and log output. Could you share that info for a single failed job?

**Comment by Vertika09** [comment]
@laurenyu I tried .tar.gz file path as well for source_dir but the error remained the same. I tried running this multiple times before posting and I made sure every time to set the correct path. 


Hyperparameters
Key	Value
epochs	10
hidden_dim	200
sagemaker_container_log_level	20
sagemaker_enable_cloudwatch_metrics	false
sagemaker_job_name	"pytorch-training-2020-06-12-04-44-05-085"
sagemaker_program	"train.py"
sagemaker_region	"us-east-1"
sagemaker_submit_directory	"s3://lum-sagemaker/model.tar.gz"

**Comment by laurenyu** [comment]
sorry if I wasn't clear earlier. The `.tar.gz` file that `sagemaker_submit_directory` points to should contain your `train.py` file.

If you have `train.py` saved locally and not in S3, then your code should look like:

```python
PyTorch(entry_point='train.py', ...)
```

If it is already saved in S3, then your code should look like:

```python
PyTorch(entry_point='train.py', source_dir='s3://bucket/path/sourcedir.tar.gz', ...)
```

where `sourcedir.tar.gz` looks like:

```
sourcedir.tar.gz
|- train.py
```

If your `train.py` is saved locally and you want it saved in a specific S3 location, then your code should look like:

```
PyTorch(entry_point='train.py', code_location='s3://bucket/path', ...)
```

**Comment by Vertika09** [comment]
Hi @laurenyu, I have tried uploading the train.py file in tar.gz in S3 bucket and gave  the reference path in source_dir. It didn't work either.

**Comment by metrizable** [comment]
I've read through the issue comments and tracebacks. Just for clarity of current state @Vertika09 of the issue you're working through, would you be able to provide:

1. your latest code which includes the creation of an instance of the `PyTorch` estimator
1. the listing the contents of your tar.gz file that you uploaded to S3 (output of command `tar -ztvf yourarchive.tar.gz`)

**Comment by muhammed100119** [comment]
UnexpectedStatusException: Error for Training job xgboost-2020-09-03-08-52-55-355: Failed. Reason: ClientError: Cannot pull algorithm container. Either the image does not exist or its permissions are incorrect.

​

**Comment by muhammed100119** [comment]
what is the error

**Comment by hsl89** [comment]
close for lack of activity
