### ISSUE TITLE
Installing notebook dependencies

### ISSUE THREAD

**Issue by MeLight** [aws/amazon-sagemaker-examples#1244]
Is there a way to install all the python packages for a specific example easily, without manually going through import exceptions?

**Comment by aaronmarkham** [comment]
Examples should have the dependencies in the kernel they're using already. Some examples install additional packages. If you're getting an exception on an import statement, you might be using the wrong kernel. For example, if there's an error around PyTorch, you should check to make sure you're running a PyTorch kernel.

I'm going to close this, but please reopen if you have any specific import exception you want to report.
