### ISSUE TITLE
No Python 3 (Data Science) kernel available in SageMaker Notebook

### ISSUE THREAD

**Issue by cyanzhqq** [aws/amazon-sagemaker-examples#1252]
Hi, I am trying to open `Direct Marketing with Amazon SageMaker Autopilot` directly from SageMaker Notebook (SageMaker Examples), but there is no `Kernel Python 3 (Data Science)` available to choose. Could you provide some guidance how to fix it?

**Comment by seanpmorgan** [comment]
Hi @cyanzhqq apologies for the slow response. The data science kernel is a part of SM Studio:
https://docs.aws.amazon.com/sagemaker/latest/dg/notebooks-available-kernels.html

For notebook instances your best bet is probably `conda_python3` and if you find anything missing you can easily pip or conda install.

Let me know if you have any more questions and we can re-open

**Comment by david-waterworth** [comment]
What I found very confusing was I could not find a `conda_python3` kernel. What's unclear is there appears to be a considerable difference between the kernels available from Sagemaker Studio, and those available on Notebook instances. It seems that despite Sagemaker Studion being newer and more powerful, the samples are all designed to run on Notebook Instances but to someone new to Sagemaker this isn't obvious.
