### ISSUE TITLE
Permission issue when creating my own docker file and build_push script

### ISSUE THREAD

**Issue by happyreaper** [aws/amazon-sagemaker-examples#1257]
I've had no issue running the notebook as is. Was able to successfully build and push to ECR. But when I create my own docker file and build_push script with catboost as the algorithm, I'm getting this error: 
denied: User: arn:aws:sts::<account>:assumed-role/role-name/role-session-name is not authorized to perform: ecr:InitiateLayerUpload on resource: arn:aws:ecr:<region>:<account>:repository/catboost

**Comment by IvyBazan** [comment]
This may be due to not having the proper permissions set up for your role.
For information on updating your SageMaker roles, see https://docs.aws.amazon.com/sagemaker/latest/dg/sagemaker-roles.html
