### ISSUE TITLE
Using Gensim on SageMaker?

### ISSUE THREAD

**Issue by datistiquo** [aws/amazon-sagemaker-examples#1295]
I am very new and before I try Sagemaker I want be sure I can use a libray like gensim on SageMaker? 

Could I just train a model like on a local notebook?

**Comment by seanpmorgan** [comment]
Hi, apologies for the slow response. Yes, sagemaker allows you to bring your own containers which can contain any libraries you'd like. See these examples:
https://github.com/aws/amazon-sagemaker-examples/tree/master/advanced_functionality/custom-training-containers

For the second question you can train models locally with sagemaker for debugging purposes. See these examples:
https://github.com/aws-samples/amazon-sagemaker-local-mode

Closing, but let us know if this didn't answer your question and we can further discuss.
