### ISSUE TITLE
ValueError: Number of features of the model must match the input. Model n_features is 4 and input n_features is 3 

### ISSUE THREAD

**Issue by C24IO** [aws/amazon-sagemaker-examples#1345]
https://github.com/awslabs/amazon-sagemaker-examples/blob/41b36d9c0a7ff4e0f416d048185984e25e1941ae/advanced_functionality/scikit_bring_your_own/scikit_bring_your_own.ipynb#L505

`---------------------------------------------------------------------------
ModelError                                Traceback (most recent call last)
<ipython-input-12-62cda6a13596> in <module>
----> 1 print(predictor.predict(test_data.values).decode('utf-8'))

~/anaconda3/envs/python3/lib/python3.6/site-packages/sagemaker/predictor.py in predict(self, data, initial_args, target_model, target_variant)
    111 
    112         request_args = self._create_request_args(data, initial_args, target_model, target_variant)
--> 113         response = self.sagemaker_session.sagemaker_runtime_client.invoke_endpoint(**request_args)
    114         return self._handle_response(response)
    115 

~/anaconda3/envs/python3/lib/python3.6/site-packages/botocore/client.py in _api_call(self, *args, **kwargs)
    314                     "%s() only accepts keyword arguments." % py_operation_name)
    315             # The "self" in this scope is referring to the BaseClient.
--> 316             return self._make_api_call(operation_name, kwargs)
    317 
    318         _api_call.__name__ = str(py_operation_name)

~/anaconda3/envs/python3/lib/python3.6/site-packages/botocore/client.py in _make_api_call(self, operation_name, api_params)
    633             error_code = parsed_response.get("Error", {}).get("Code")
    634             error_class = self.exceptions.from_code(error_code)
--> 635             raise error_class(parsed_response, operation_name)
    636         else:
    637             return parsed_response

ModelError: An error occurred (ModelError) when calling the InvokeEndpoint operation: Received server error (500) from model with message "<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.</p>
". See https://us-east-1.console.aws.amazon.com/cloudwatch/home?region=us-east-1#logEventViewer:group=/aws/sagemaker/Endpoints/sagemaker-decision-trees-2020-07-24-20-20-13-487 in account 111652037296 for more information.`

**Comment by balajitummala** [comment]
@C24IO I am able to run the notebook as is without any errors. Could you let us know if you are still running into the issue ?
![Screen Shot 2020-08-10 at 3 57 20 PM](https://user-images.githubusercontent.com/63808583/89839398-782ff000-db22-11ea-9b2f-346ef6f7d9d2.png)

**Comment by seanpmorgan** [comment]
Closing because this looks to be a temporary issue, but please let us know if the problem persists. Thanks!

**Comment by andrescmarin** [comment]
The error is present in sagemaker studio notebook with python 3 datascience kernel
