### ISSUE TITLE
Sklearn_on_SageMaker_end2end.ipynb issues

### ISSUE THREAD

**Issue by aaronmarkham** [aws/amazon-sagemaker-examples#1350]
https://github.com/awslabs/amazon-sagemaker-examples/blob/master/sagemaker-python-sdk/scikit_learn_randomforest/Sklearn_on_SageMaker_end2end.ipynb

* tuning
There's a tuning section that should show the following, but upon the first run, it just shows a dash and no data. Maybe a waiting period is required or some check that data is returned so the user knows that something is coming... eventually.
<img width="954" alt="2020-07-27_15-24-32" src="https://user-images.githubusercontent.com/5974205/88603529-0cca2680-d02a-11ea-8395-d06c72e35d4d.png">

**Comment by balajitummala** [comment]
@aaronmarkham I created this PR https://github.com/awslabs/amazon-sagemaker-examples/pull/1381 to address the above issue. Please review.

**Comment by seanpmorgan** [comment]
Closing as this was addressed
