### ISSUE TITLE
random_cut_forest.ipynb issues

### ISSUE THREAD

**Issue by aaronmarkham** [aws/amazon-sagemaker-examples#1351]
https://github.com/awslabs/amazon-sagemaker-examples/blob/master/introduction_to_amazon_algorithms/random_cut_forest/random_cut_forest.ipynb

* error
```
AttributeError: 'Series' object has no attribute 'as_matrix' 
```

* configuration
Also needs the bucket to be set to default bucket or won't run

**Comment by balajitummala** [comment]
@aaronmarkham I was able to run the notebook without any errors. Could you share more details on the error ?
I will create a PR to change the bucket to use default bucket unless the user changes it.

**Comment by balajitummala** [comment]
https://github.com/awslabs/amazon-sagemaker-examples/pull/1376

**Comment by seanpmorgan** [comment]
`as_matrix` no longer is called in this notebook and last adjustment to the notebook was passing CI:
https://github.com/aws/amazon-sagemaker-examples/pull/1718

Closing.
