### ISSUE TITLE
Fail to download Caltech Birds dataset

### ISSUE THREAD

**Issue by harusametime** [aws/amazon-sagemaker-examples#1371]
In [introduction_to_amazon_algorithms/object_detection_birds/object_detection_birds.ipynb](https://github.com/awslabs/amazon-sagemaker-examples/blob/master/introduction_to_amazon_algorithms/object_detection_birds/object_detection_birds.ipynb),  Caltech Birds dataset moved to Google Drive.

Due to this, the following script fails to download the dataset.
```python
download('http://www.vision.caltech.edu/visipedia-data/CUB-200-2011/CUB_200_2011.tgz')
```

**Comment by CloudaYolla** [comment]
The NB is updated. Can now use one made available by fast.ai .
download ('https://s3.amazonaws.com/fast-ai-imageclas/CUB_200_2011.tgz')

**Comment by seanpmorgan** [comment]
Closing as this was resolved. Thanks!
