### ISSUE TITLE
SageMaker Studio ImportError: cannot import name 'csv_serializer' from 'sagemaker.predictor'

### ISSUE THREAD

**Issue by CloudaYolla** [aws/amazon-sagemaker-examples#1372]
SageMaker Studio Getting Started Notebook: is giving the following error. 
I've been informed due to a recent upgrade. DK v2.0.0 came out with a set of breaking changes. 

https://github.com/awslabs/amazon-sagemaker-examples/blob/master/aws_sagemaker_studio/getting_started/xgboost_customer_churn_studio.ipynb

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import io
import os
import sys
import time
import json
from IPython.display import display
from time import strftime, gmtime
import boto3
import re

import sagemaker
from sagemaker import get_execution_role
from sagemaker.predictor import csv_serializer
from sagemaker.debugger import rule_configs, Rule, DebuggerHookConfig
from sagemaker.model_monitor import DataCaptureConfig, DatasetFormat, DefaultModelMonitor
from sagemaker.s3 import S3Uploader, S3Downloader

from smexperiments.experiment import Experiment
from smexperiments.trial import Trial
from smexperiments.trial_component import TrialComponent
from smexperiments.tracker import Tracker

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-2-e0bde508a6eb> in <module>
     15 import sagemaker
     16 from sagemaker import get_execution_role
---> 17 from sagemaker.predictor import csv_serializer
     18 from sagemaker.debugger import rule_configs, Rule, DebuggerHookConfig
     19 from sagemaker.model_monitor import DataCaptureConfig, DatasetFormat, DefaultModelMonitor

ImportError: cannot import name 'csv_serializer' from 'sagemaker.predictor' (/opt/conda/lib/python3.7/site-packages/sagemaker/predictor.py)

**Comment by SoraDevin** [comment]
Just tried getting started with sagemaker today and ran into the same thing. Did you know of a workaround I can edit into the notebook?

**Comment by castillohair** [comment]
`sagemaker` v2.x, which is imported by default, has several [API differences](https://sagemaker.readthedocs.io/en/stable/v2.html) with respect to v1.x, which is what the notebook has been written for. A quick temporary fix is to change the second line of cell [1] to the following:

```
!{sys.executable} -m pip install sagemaker==1.72.0 -U
```

After doing this and restarting the kernel, the notebook works for me.

**Comment by SoraDevin** [comment]
@castillohair mate you're a legend, works great now, at least to get me up and running. Cheers

**Comment by geek311** [comment]
Having the same issue here [](https://github.com/awslabs/amazon-sagemaker-examples/blob/master/sagemaker_batch_transform/introduction_to_batch_transform/batch_transform_pca_dbscan_movie_clusters.ipynb )

>> from sagemaker.predictor import csv_serializer, json_deserializer
ImportError: cannot import name 'csv_serializer'

**Comment by pmhargis-aws** [comment]
Thanks @castillohair 
I had the same issue, and modified the sagemaker install as you said; working now!

@geek311 Look in the first cell (1) where sagemaker is installed by pip, and REPLACE the one without the version string with the one quoted here

**Comment by seanpmorgan** [comment]
This issue has been fixed since there is now a cell which downgrades the SDK. Closing this and will re-create an issue to update the notebook

**Comment by Sandy4321** [comment]
STILL NOT WORKING 
![image](https://github.com/aws/amazon-sagemaker-examples/assets/11426119/50db9b15-c1b9-4304-9180-3005320fe24a)

**Comment by Sandy4321** [comment]
import sys

!{sys.executable} -m pip install -qU awscli boto3 "sagemaker>=1.71.0,<2.0.0"
!{sys.executable} -m pip install sagemaker-experiments
nothing
from 
https://github.com/aws/amazon-sagemaker-examples/blob/main/aws_sagemaker_studio/getting_started/xgboost_customer_churn_studio.ipynb
 helps
![image](https://github.com/aws/amazon-sagemaker-examples/assets/11426119/6cf1f7ee-a7e1-47ac-b21c-4e621ce877b9)

**Comment by Sandy4321** [comment]
![image](https://github.com/aws/amazon-sagemaker-examples/assets/11426119/35dba0dd-a57c-45c5-ae9e-ef4344c7dc80)

**Comment by Sandy4321** [comment]
I try to run code from 
https://www.youtube.com/watch?v=v2V0g0yLemY
https://github.com/johnny-chivers/sagemakerCode/blob/main/sgaemaker-code.py

**Comment by uniqueavi** [comment]
change the imports

from sagemaker.serializers import CSVSerializer

**Comment by liusongdu** [comment]
IMHO, downgrading the package version might workaround the issue for a while, but fixing the issue using the up-to-date version can be a long-term solution.
Based @uniqueavi 's comment, to import both serializer/deserializer classes, the imports would be like:
`# https://sagemaker.readthedocs.io/en/stable/v2.html#serializer-and-deserializer-classes
# from sagemaker.predictor import json_serializer, json_deserializer  # v1.x
from sagemaker.serializers import CSVSerializer # v2.0 and later
from sagemaker.deserializers import JSONDeserializer  # v2.0 and later`
There was a change from version 1.x to 2.x was the [serializer/deserializer classes](https://sagemaker.readthedocs.io/en/stable/v2.html#serializer-and-deserializer-classes)
