### ISSUE TITLE
 scikit_bring_your_own container is python 2 dependent

### ISSUE THREAD

**Issue by gabrielaolinto** [aws/amazon-sagemaker-examples#1380]
Hello,

scikit_bring_your_own container is python 2 dependent. 
Given the end of support for python 2, when will this container be updated to python 3?

Thanks!

**Comment by Wei-1** [comment]
Add another request to move scikit_bring_your_own to python3.
Need to mix models from different DL frameworks in one container and is using scikit_bring_your_own as the template to start, but found that it is still in python2, which is causing many dependency issues.

**Comment by seanpmorgan** [comment]
Not quite fixed. Will submit follow up PR
