### ISSUE TITLE
xgboost_customer_churn_studio updating sagemaker breaks imports

### ISSUE THREAD

**Issue by iprivit** [aws/amazon-sagemaker-examples#1390]
The first cell of the notebook has the user update to the latest version of sagemaker, but the notebook still uses old imports which installing the newest version of the SageMaker Python SDK breaks. It breaks half of the functionality in the notebook and makes it unusable, just to illustrate a few:

cell 1 line 2:
!{sys.executable} -m pip install sagemaker -U
^^^ this action breaks all of the following imports:

cell 2 line 17:
from sagemaker.predictor import csv_serializer 

Fix:
from sagemaker.serializers import CSVSerializer

cell 6 line 1:
from sagemaker.amazon.amazon_estimator import get_image_uri

Fix:
from sagemaker.image_uris import retrieve

cell 7 line 1:
s3_input_train = sagemaker.s3_input(s3_data='s3://{}/{}/train'.format(bucket, prefix), content_type='csv')

Fix:
s3_input_train = sagemaker.inputs.TrainingInput(s3_data='s3://{}/{}/train'.format(bucket, prefix), content_type='csv')

Cell 10 line 5:
xgb = sagemaker.estimator.Estimator(image_name=docker_image_name,

Fix:
update arguments to correct names, e.g. image_name -> image_uri

**Comment by Blakewell** [comment]
Fix on Line 6 is: from sagemaker.serializers import CSVSerializer

**Comment by iprivit** [comment]
> Fix on Line 6 is: from sagemaker.serializers import CSVSerializer

Whoops, you are right, fixed that.

**Comment by nskool** [comment]
@IvyBazan This issue can be closed.
