### ISSUE TITLE
Neo: pytorch_torchvision_neo.ipynb and pytorch_torchvision_neo_studio.ipynb

### ISSUE THREAD

**Issue by mchoi8739** [aws/amazon-sagemaker-examples#1400]
### **In Notebook Instance**

tested in conda_pytorch_p36 kernel

**pytorch_torchvision_neo.ipynb**
- Cannot import model
```
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-8cf7b66b37e8> in <module>
      1 import torch
----> 2 import torchvision.models as models
      3 import tarfile
      4 
      5 resnet18 = models.resnet18(pretrained=True)

ImportError: cannot import name 'PILLOW_VERSION'
```
This was not fixed even after trying `!{sys.executable} -m pip install torch==1.2.0+cpu torchvision==0.4.0+cpu -f https://download.pytorch.org/whl/torch_stable.html` and restart the kernel.

**pytorch_torchvision_neo_studio.ipynb**

- the top cell, `%cd /root/amazon-sagemaker-examples/aws_sagemaker_studio/sagemaker_neo_compilation_jobs/pytorch_torchvision`, is Studio-specific. Works fine in the Notebook instance if skipping the top cell.

### **In Studio**

tested in Python 3 (PyTorch CPU Optimized) kernel

**pytorch_torchvision_neo.ipynb** and **pytorch_torchvision_neo_studio.ipynb**
- In the **pytorch_torchvision_neo.ipynb** notebook, use the following pip install cell.
```
import sys
!{sys.executable} -m pip install torch==1.2.0+cpu torchvision==0.4.0+cpu -f https://download.pytorch.org/whl/torch_stable.html
```
- For both notebooks, the kernels had to be restarted in order to use the installed packages. Otherwise, returned an error message: 
```
ImportError: FloatProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
```

### **What to fix:** 
1. Point out to restart the kernel.
2. Use the same pip install cell for both notebooks:
```
import sys
!{sys.executable} -m pip install torch==1.2.0+cpu torchvision==0.4.0+cpu -f https://download.pytorch.org/whl/torch_stable.html
```
3. Fix **pytorch_torchvision_neo.ipynb** to import the model in the notebook instance.
4. These two notebooks are identical, except the top cell. Suggest to keep it in one place.

**Comment by mchoi8739** [comment]
Tested again, and `import torchvision.models as models` works on the `conda_pytorch_p36` kernel now.

**Comment by ngluna** [comment]
Let's close this ticket unless there is objection?

**Comment by mchoi8739** [comment]
I left it open because the ipywidgets issue still needs to be resolved. 
Was considering to close it because Aaron linked this to issue [1481](https://github.com/awslabs/amazon-sagemaker-examples/issues/1481) that addresses the same problem, so we can close this one if you also agree with closing it.

**Comment by aaronmarkham** [comment]
If you see this error again, please check the version on `pillow`. I think this error will depend on whether or not this is pinned and if torchvision accidentally upgraded it. Seems like you'll get the error if pillow is v7.
https://github.com/pytorch/vision/issues/1718
Sounds like it was transient though and the dependencies are working properly now.
