### ISSUE TITLE
Update mask-rcnn tensorpack and aws-samples containers 

### ISSUE THREAD

**Issue by ajayvohra2005** [aws/amazon-sagemaker-examples#1405]
mask-rcnn containers need to be updated to recent hash commits of https://github.com/tensorpack/tensorpack and https://github.com/aws-samples/mask-rcnn-tensorflow github projects. Also need to update AWS deep learning base container to 763104351884.dkr.ecr.us-west-2.amazonaws.com/tensorflow-training:1.15.2-gpu-py36-cu100-ubuntu18.0: This version contains the custom TensorFlow ops used by the AWS optimized  model in https://github.com/aws-samples/mask-rcnn-tensorflow.

**Comment by seanpmorgan** [comment]
Addressed in #1406
