### ISSUE TITLE
Neo: mxnet_mnist_neo.ipynb

### ISSUE THREAD

**Issue by mchoi8739** [aws/amazon-sagemaker-examples#1408]
https://github.com/aws/amazon-sagemaker-examples/blob/master/sagemaker_neo_compilation_jobs/mxnet_mnist/mxnet_mnist_neo.ipynb

In the Making an inference request section, the prediction with handwritten letter HTML tool does not pass data.
Tested this on SageMaker Notebook Instance JupyterLab.

```
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-62-e00ced6fa805> in <module>
----> 1 data = np.array(data)
      2 response = predictor.predict(data)
      3 print('Raw prediction result:')
      4 print(response)
      5 

NameError: name 'data' is not defined
```

**Comment by ngluna** [comment]
Is this because it breaks CI?

**Comment by ngluna** [comment]
The MNIST notebook for Neo has been updated through [PR #2125](https://github.com/aws/amazon-sagemaker-examples/pull/2125).
