### ISSUE TITLE
mask-rcnn notebooks need to be upgraded to SageMaker 2.x  SDK

### ISSUE THREAD

**Issue by ajayvohra2005** [aws/amazon-sagemaker-examples#1414]
Mask RCNN notebooks for distributed TensorFlow training and inference need to be updated to SageMaker 2.x SDK

**Comment by BigLep** [comment]
@ajayvohra2005 : are you planning to take this on, or are you looking to another SageMaker team to handle this?

**Comment by seanpmorgan** [comment]
Completed in https://github.com/aws/amazon-sagemaker-examples/pull/1406
