### ISSUE TITLE
Local Mode does not work on Sagemaker Studio 

### ISSUE THREAD

**Issue by bloodywolf3** [aws/amazon-sagemaker-examples#1419]
Describe the bug
I am trying to do training in a local container by running the example python notebook: [mxnet_gluon_mnist/mxnet_mnist_with_gluon_local_mode.ipynb](https://github.com/awslabs/amazon-sagemaker-examples/blob/master/sagemaker-python-sdk/mxnet_gluon_mnist/mxnet_mnist_with_gluon_local_mode.ipynb)

To reproduce
A clear, step-by-step set of instructions to reproduce the bug.
In the sagemaker studio window

Select a) MXNET GPU optimized kernel and b) ml.g4dn.xlarge instance
1) Running the script: **!/bin/bash ./setup.sh**
The output is ./setup.sh: line 3: sudo: command not found
The user does not have root access. Everything required to run the notebook is already installed and setup. We are good to go!
2) Run **m.fit(inputs)**
The output is ImportError: 'docker-compose' is not installed. Local Mode features will not work without docker-compose. For more information on how to install 'docker-compose', please, see https://docs.docker.com/compose/install/

System information
SageMaker Python SDK version:
Framework name (eg. PyTorch) or algorithm (eg. KMeans): MXNET GPU optimized kernel
Framework version:
Python version: 3
CPU or GPU: ml.g4dn.xlarge
Custom Docker image (Y/N): N

**Comment by ChuyangDeng** [comment]
Hi @bloodywolf3, docker itself will not work on Studio notebooks as Studio Notebooks run inside docker containers. You could try to run this example on SageMaker Notebook instance instead.

**Comment by seanpmorgan** [comment]
Closing. As mentioned Studio runs inside of docker so in order to build images you can either use this utility: 
https://github.com/aws-samples/sagemaker-studio-image-build-cli

Or build them outside of studio (in SM notebooks, locally with aws cli) and continue with the example after it's been pushed to ECR.

**Comment by samdwar1976** [comment]
I have written an [article](https://medium.com/@sam.edwards1976/local-mode-training-and-inference-in-sagemaker-studio-3062d10ae603) describing a solution that makes it possible to use 'Local Mode' in SageMaker Studio. Apologies for opening a closed issue, but adding this for completeness.
