### ISSUE TITLE
multi_model_endpoint_bring_your_own.ipynb

### ISSUE THREAD

**Issue by aaronmarkham** [aws/amazon-sagemaker-examples#1436]
https://github.com/awslabs/amazon-sagemaker-examples/blob/master/advanced_functionality/multi_model_bring_your_own/multi_model_endpoint_bring_your_own.ipynb

It upgrades to v2, then fails. Needs the pip install line to be removed or updated/pinned to v1.

**Comment by mchoi8739** [comment]
Ran this notebook to reproduce the issue, but it ran successfully.

**Comment by seanpmorgan** [comment]
Closing. This PR also indicates that it's running successfully:
https://github.com/aws/amazon-sagemaker-examples/pull/1663
