### ISSUE TITLE
r_bring_your_own.ipynb

### ISSUE THREAD

**Issue by IvyBazan** [aws/amazon-sagemaker-examples#1442]
Running this notebook results in the following error:

WaiterError: Waiter TrainingJobCompletedOrStopped failed: Waiter encountered a terminal failure state

**Comment by icywang86rui** [comment]
@IvyBazan 

Did you run this on a SageMaker Notebook instance or Studio? What's the instance type you used? Which cell failed to execute?

**Comment by IvyBazan** [comment]
I ran this on a SageMaker ml.t2.medium Notebook instance. The error happened on the third cell of the Train section

**Comment by icywang86rui** [comment]
Did you run this with the sdk come with the notebook instance?
Did the training job start?
Could you show me the entire log from the container?

**Comment by IvyBazan** [comment]
Verified that this notebook is functioning as expected
