### ISSUE TITLE
script-mode-container-2.ipynb

### ISSUE THREAD

**Issue by IvyBazan** [aws/amazon-sagemaker-examples#1454]
Running this notebook results in the following error:
Error: cannot read infile: [Errno 2] No such file or directory: '../scripts/build_and_push.sh'

**Comment by seanpmorgan** [comment]
Just ran this and did not run into that issue. The pathing to `../scripts/build_and_push.sh` from the notebook directory is correct:
https://github.com/aws/amazon-sagemaker-examples/tree/master/advanced_functionality/custom-training-containers/script-mode-container-2/notebook

https://github.com/aws/amazon-sagemaker-examples/blob/master/advanced_functionality/custom-training-containers/script-mode-container-2/scripts/build_and_push.sh
