### ISSUE TITLE
sagemaker-countycensusclustering.ipynb

### ISSUE THREAD

**Issue by xgchena** [aws/amazon-sagemaker-examples#1463]
Symptom:

The notebook failed to load, error message: "File Load Error for sagemaker-countycensusclustering.ipynb
Unreadable Notebook: amazon-sagemaker-examples/introduction_to_applying_machine_learning/US-census_population_segmentation_PCA_Kmeans/sagemaker-countycensusclustering.ipynb NotJSONError('Notebook does not appear to be JSON: \'{\\n "cells": [\\n {\\n "cell_type": "m...')"

Rootcause/Solution:

See my comment on https://github.com/awslabs/amazon-sagemaker-examples/commit/1fffb0335c89934fa821032117ffdff603916009

**Comment by IvyBazan** [comment]
Issue has been fixed: https://github.com/aws/amazon-sagemaker-examples/commit/aafbb77134a9622bebfdd679afeb435bf89de862
