### ISSUE TITLE
FileNotFoundError when loading checkpoint model in RL Notebook

### ISSUE THREAD

**Issue by ngluna** [aws/amazon-sagemaker-examples#1472]
In notebook: https://github.com/awslabs/amazon-sagemaker-examples/blob/master/reinforcement_learning/rl_game_server_autopilot/sagemaker/rl_gamerserver_ray.ipynb

When loading the checkpoint model (code cell  12)

`FileNotFoundError: S3 object s3://sagemaker-us-west-2-688520471316/rl-game-server-autopilot-2020-08-28-xx-xx-xx-605/output/output.tar.gz never appeared after 1200 seconds
`

To reproduce error:

Launch SM Notebook instance
Clone https://github.com/awslabs/amazon-sagemaker-examples.git
Open https://github.com/awslabs/amazon-sagemaker-examples/blob/master/reinforcement_learning/rl_game_server_autopilot/sagemaker/rl_gamerserver_ray.ipynb
Click "Cell" -> "Run All"

**Comment by ngluna** [comment]
Similar issue happened to this notebook: https://github.com/awslabs/amazon-sagemaker-examples/blob/master/reinforcement_learning/rl_roboschool_ray/rl_roboschool_ray.ipynb . The model.tar.gz file never appeared in this case.

**Comment by annaluo676** [comment]
Sorry for the delayed response. `model.tar.gz` is the model output artifact and will appear only when the training is  *completed*. Can you share the last few lines of the job log?

**Comment by ngluna** [comment]
How long does the job take to run? Right now I am running the notebook on a `ml.c5.18xlarge`  instance. It has been going on for about 5 hours.  

I think what's happening is that setting `estimator.fit(wait=False)` allows you to run cells after this one. So, since training hasn't finished, we get the `FileNotFoundError`.

**Comment by yijiezh** [comment]
Does the notebook by default run for over 5 hours or you change some parameters?

**Comment by goelakash** [comment]
Closing as no response received.
