### ISSUE TITLE
Docker Image Not Correctly Pushed to ECR

### ISSUE THREAD

**Issue by ngluna** [aws/amazon-sagemaker-examples#1476]
In https://github.com/awslabs/amazon-sagemaker-examples/blob/master/sagemaker-python-sdk/dgl_gcmc/mxnet_gcmc.ipynb

Calling:

`estimator.fit()`

Returns:

`ClientError: An error occurred (ValidationException) when calling the CreateTrainingJob operation: Cannot find the requested image:`

Note: My NI has all the necessary IAM permissions required to push and pull ECR images.

To reproduce error:

1. Launch SM Notebook instance
2. Clone https://github.com/awslabs/amazon-sagemaker-examples.git
3. Open https://github.com/awslabs/amazon-sagemaker-examples/blob/master/sagemaker-python-sdk/dgl_gcmc/mxnet_gcmc.ipynb
4. Click "Cell" -> "Run All"

**Comment by classicsong** [comment]
The error says: SageMaker can not fide your ECR images.

Is there any other errors before this error?
