### ISSUE TITLE
PyTorch notebooks failing on Studio due to ipywidgets error

### ISSUE THREAD

**Issue by aaronmarkham** [aws/amazon-sagemaker-examples#1481]
https://github.com/awslabs/amazon-sagemaker-examples/blob/master/sagemaker-python-sdk/pytorch_horovod_mnist/pytorch_mnist_horovod.ipynb

Similar issue: https://github.com/awslabs/amazon-sagemaker-examples/issues/1400

Error:
```
ImportError: FloatProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
```

Installing and importing ipywidgets seems to work in some cases, but their installation directions don't exactly work when you try to install the labextension. It isn't clear if you're getting the full functionality or not.

Seems like this should be included by default in any PyTorch kernel.

**Comment by aaronmarkham** [comment]
WORK AROUND

In Jupyter Server
```
jupyter labextension install @jupyter-widgets/jupyterlab-manager
```
In kernel image
```
conda install -c conda-forge ipywidgets -y -q
```

**Comment by atqy** [comment]
This problem no longer occurs in this notebook, probably due to updated containers. Closing this issue for now.
