### ISSUE TITLE
Cell is not displayed when opening sample jpynb file with JupyterLab

### ISSUE THREAD

**Issue by ttsukai** [aws/amazon-sagemaker-examples#1491]
The reproduction procedure is as follows.
1. create notebook instance from SageMaker Console
2. Open JupyterLab
3. Click "Amazon SageMaker sample notebooks" from left side bar
4. Choose "sagemaker_autopilot_direct_marketing.jpynb" in AUTOPILOT chapter
5. Create a copy with "conda_amazonei_mxnet_p27"
6. --> No cell in "4. Upload the dataset to Amazon S3" section.

There is no problem if the above operation is executed in "Jupyter notebook".

**Comment by IvyBazan** [comment]
This issue has been fixed
