### ISSUE TITLE
Restrict Sagemaker Studio Instance Size

### ISSUE THREAD

**Issue by himachalbanik40** [aws/amazon-sagemaker-examples#1499]
In jupyter notebooks of sagemaker studio one can select instance size on the fly. But what i want for an IAM user is to restrict him to specific instance type. For example the user cannot select any other instances except ml.t3.* . So far i have tried by making roles and adding conditions to instance types but nothing worked. Is there any way we can do this?

**Comment by seanpmorgan** [comment]
The easiest way to do this would be to limit the IAM SageMakerExecutionRole for a given Studio Domain. You can use SSO to restrict certain users to specific domains. Please let us know if this doesn't satisfy your request, and we can re-open this and discuss alternate strategies

**Comment by aldegoeij** [comment]
```json
{
    "Action": [
        "sagemaker:CreateApp"
    ],
    "Resource": [
        "*"
    ],
    "Effect": "Deny",
    "Sid": "BlockSagemakerOtherThanT3",
    "Condition": {
        "ForAnyValue:StringNotLike": {
            "sagemaker:InstanceTypes": [
                "ml.t3.medium",
                "ml.t3.xlarge",
                "system",
                "default"
            ]
        }
    }
}
```

**Comment by manoj1madhavan** [comment]
Thank you  - Yes, was using the same and it has been working fine so far. Would have been great if there was a way to enforce the Tag to these "APPS" - would help control access. Was working on a model to track the App run status along with the Tag Name - instead of the user profile it is associated with, to support the Cost/Billing side (for a recharge model).

**Comment by iliassboutechdat** [comment]
Hello,

I have tried the same approach but I can still create instances bigger than the one I mentioned, any tips?

<img width="320" alt="image" src="https://github.com/aws/amazon-sagemaker-examples/assets/61149615/96845c03-5c0a-467b-a57f-a7f51769c431">

**Comment by christiemosley92-commits** [comment]
I didn't think it was going to be so difficult
