### ISSUE TITLE
Prediction Type to be 'binary_classifier' instead of 'regressor' on Breast Cancer example

### ISSUE THREAD

**Issue by Gelesh** [aws/amazon-sagemaker-examples#1505]
The Current Prediction Type found is predictor_type='regressor' and needs to be corrected as  'binary_classifier' 
file https://github.com/awslabs/amazon-sagemaker-examples/blob/master/introduction_to_applying_machine_learning/breast_cancer_prediction/Breast%20Cancer%20Prediction.ipynb

**Comment by paul-cb** [comment]
predictor_type is correctly assigned in this notebook example. Closing.

**Comment by Gelesh** [comment]
Wjat is the target variable?
Is it a continous variable or a category variable.?
Since its a category variable it shpuld be classification not regression. @paul-cb.. I beg to differ with you, or have I missed some part of the problem. Kindly respond.
