### ISSUE TITLE
cannot import name 'get_image_uri' from 'sagemaker.amazon.amazon_estimator'

### ISSUE THREAD

**Issue by mzhao577** [aws/amazon-sagemaker-examples#1507]
Hello,

I am trying to run some examples on AWS SageMaker. I had an error like this when I tried to run the example: linear_learner_mnist.ipynb inside the folder: introduction_to_amazon_algorithms/linear_learner_mnist.

The error message is like this: 
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-13-62e763e9f7d4> in <module>
----> 1 from sagemaker.amazon.amazon_estimator import get_image_uri
      2 container = get_image_uri(boto3.Session().region_name, 'linear-learner')

ImportError: cannot import name 'get_image_uri' from 'sagemaker.amazon.amazon_estimator' (/opt/conda/lib/python3.7/site-packages/sagemaker/amazon/amazon_estimator.py)

I would really help if you could help me.  This appears to be the same as issue # 331.  I tried the suggestion posted there. But I still cannot resolve my issue. I hope I can get some extra help.

Thanks a lot for your help.

Max

**Comment by cfregly** [comment]
you're likely using the new SageMaker 2.x SDK which has some breaking API changes as follows:  https://sagemaker.readthedocs.io/en/stable/v2.html#image-uri-functions-e-g-get-image-uri

to verify:  do a `pip list` and check the version of `sagemaker`

to workaround:  downgrade to the SageMaker 1.x SDK using `pip install sagemaker==1.72.0` at the top of the notebook and re-run.

**Comment by mzhao577** [comment]
Hi Chris,

Thanks so much for your timely response.   I downgrade my sageMaker to 1.72.0
by your command.

Now I got the following warning message: "'get_image_uri' method will be
deprecated in favor of 'ImageURIProvider' class in SageMaker Python SDK
v2." This should not prevent me from running the rest of the codes. right?

The training process is running so I assume it's good. Thanks a lot for
your help.

Max

**Comment by Aruun** [comment]
Resolution:
from sagemaker import image_uris
container = sagemaker.image_uris.retrieve("linear-learner", boto3.Session().region_name)

**Comment by Sigm0oid** [comment]
In my case, I solved the issue by updating : 
```
from sagemaker.amazon.amazon_estimator import get_image_uri
XGBOOST_IMAGE = get_image_uri(boto3.Session().region_name, 'xgboost', repo_version='1.0-1')
```
to 
```
from sagemaker.amazon.amazon_estimator import image_uris
XGBOOST_IMAGE = image_uris.retrieve(region=boto3.Session().region_name, framework='xgboost', version='1.0-1')
```
I hope this helps, for more understanding of the parameters, refer to this [doc](https://sagemaker.readthedocs.io/en/stable/api/utility/image_uris.html#sagemaker.image_uris.retrieve), and I would recommend using v2 sdk rather than manually downgrading the version

**Comment by aditya12997** [comment]
from sagemaker import image_uris
container = sagemaker.image_uris.retrieve("xgboost", boto3.Session().region_name,version ="latest")


Another method that worked for me since the above code was not functional to the XGBoost built in model in my environment 
Hope this helps you in some way.

**Comment by aditya12997** [comment]
One can change the algorithm name as per needed and it should work, as SageMaker has updated the get_image_uri library

**Comment by Anilabhimanyu** [comment]
when we create sagemaker model, we will use both the trained model in tar file and either prebuilt or custom built image, for prebuilt image uri, we use get_image_uri, but for our own image, how can we link the custom image uri with tar file in primary container for endpoint configuration
