### ISSUE TITLE
autopilot_customer_churn_high_level_with_evaluation.ipynb sample fails in the console to prediction step due to unrecognized content type

### ISSUE THREAD

**Issue by aws-rbs** [aws/amazon-sagemaker-examples#1530]
Sample link:
https://github.com/awslabs/amazon-sagemaker-examples/blob/master/autopilot/autopilot_customer_churn_high_level_with_evaluation.ipynb

Problem in Deploy the Selected Candidate section
Here is the code section it fails on :
from sagemaker.predictor import RealTimePredictor
from sagemaker.content_types import CONTENT_TYPE_CSV

predictor = automl.deploy(initial_instance_count=1,
                          instance_type='ml.m5.2xlarge',
                          candidate=candidates[best_candidate_idx],
                          inference_response_keys=inference_response_keys,
                          predictor_cls=RealTimePredictor)
predictor.content_type = CONTENT_TYPE_CSV              //fails on this line
print("Created endpoint: {}".format(predictor.endpoint))

ERROR message:
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-40-557ea1ba6367> in <module>
      9                           inference_response_keys=inference_response_keys,
     10                           predictor_cls=Predictor)
---> 11 predictor.content_type = CONTENT_TYPE_CSV
     12 
     13 print("Created endpoint: {}".format(predictor.endpoint))

NameError: name 'CONTENT_TYPE_CSV' is not defined

**Comment by seanpmorgan** [comment]
Fix in https://github.com/aws/amazon-sagemaker-examples/pull/1667
