### ISSUE TITLE
autopilot_customer_churn.ipynb failed to run in the console when importing Python libraries

### ISSUE THREAD

**Issue by aws-rbs** [aws/amazon-sagemaker-examples#1531]
Code fails here:
import sagemaker
from sagemaker.predictor import csv_serializer

Here is the ERROR message:
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-2-9f07168ccc99> in <module>
     10 from time import strftime, gmtime
     11 import sagemaker
---> 12 from sagemaker.predictor import csv_serializer

ImportError: cannot import name 'csv_serializer'

**Comment by seanpmorgan** [comment]
Fix in https://github.com/aws/amazon-sagemaker-examples/pull/1699
