### ISSUE TITLE
Autopilot Feature_selection_autopilot.ipynb notebook does not loading in the console and fails to upload data in Studio

### ISSUE THREAD

**Issue by aws-rbs** [aws/amazon-sagemaker-examples#1532]
Sample link:
https://github.com/awslabs/amazon-sagemaker-examples/blob/master/autopilot/custom-feature-selection/Feature_selection_autopilot.ipynb

Read only copy does not display and Copy times out.

**Comment by aws-rbs** [comment]
Fails in Studio to upload data:

Here is the code it fails on:

train_input = sagemaker_session.upload_data(
    path='{}/{}'.format(WORK_DIRECTORY, 'train.csv'), 
    bucket=bucket,
    key_prefix='{}/{}'.format(prefix, 'training_data'))

Error message:

'upload_data' method will be deprecated in favor of 'S3Uploader' class (https://sagemaker.readthedocs.io/en/stable/s3.html#sagemaker.s3.S3Uploader) in SageMaker Python SDK v2.
---------------------------------------------------------------------------
ClientError                               Traceback (most recent call last)
/opt/conda/lib/python3.7/site-packages/boto3/s3/transfer.py in upload_file(self, filename, bucket, key, callback, extra_args)
    278         try:
--> 279             future.result()
    280         # If a client error was raised, add the backwards compatibility layer

/opt/conda/lib/python3.7/site-packages/s3transfer/futures.py in result(self)
    105             # out of this and propogate the exception.
--> 106             return self._coordinator.result()
    107         except KeyboardInterrupt as e:

/opt/conda/lib/python3.7/site-packages/s3transfer/futures.py in result(self)
    264         if self._exception:
--> 265             raise self._exception
    266         return self._result

/opt/conda/lib/python3.7/site-packages/s3transfer/tasks.py in __call__(self)
    125             if not self._transfer_coordinator.done():
--> 126                 return self._execute_main(kwargs)
    127         except Exception as e:

/opt/conda/lib/python3.7/site-packages/s3transfer/tasks.py in _execute_main(self, kwargs)
    149 
--> 150         return_value = self._main(**kwargs)
    151         # If the task is the final task, then set the TransferFuture's

/opt/conda/lib/python3.7/site-packages/s3transfer/upload.py in _main(self, client, fileobj, bucket, key, extra_args)
    691         with fileobj as body:
--> 692             client.put_object(Bucket=bucket, Key=key, Body=body, **extra_args)
    693 

/opt/conda/lib/python3.7/site-packages/botocore/client.py in _api_call(self, *args, **kwargs)
    315             # The "self" in this scope is referring to the BaseClient.
--> 316             return self._make_api_call(operation_name, kwargs)
    317 

/opt/conda/lib/python3.7/site-packages/botocore/client.py in _make_api_call(self, operation_name, api_params)
    634             error_class = self.exceptions.from_code(error_code)
--> 635             raise error_class(parsed_response, operation_name)
    636         else:

ClientError: An error occurred (AccessDenied) when calling the PutObject operation: Access Denied

During handling of the above exception, another exception occurred:

S3UploadFailedError                       Traceback (most recent call last)
<ipython-input-4-cb617b7d6ba5> in <module>
      6     path='{}/{}'.format(WORK_DIRECTORY, 'train.csv'),
      7     bucket=bucket,
----> 8     key_prefix='{}/{}'.format(prefix, 'training_data'))

/opt/conda/lib/python3.7/site-packages/sagemaker/session.py in upload_data(self, path, bucket, key_prefix, extra_args)
    212 
    213         for local_path, s3_key in files:
--> 214             s3.Object(bucket, s3_key).upload_file(local_path, ExtraArgs=extra_args)
    215 
    216         s3_uri = "s3://{}/{}".format(bucket, key_prefix)

/opt/conda/lib/python3.7/site-packages/boto3/s3/inject.py in object_upload_file(self, Filename, ExtraArgs, Callback, Config)
    278     return self.meta.client.upload_file(
    279         Filename=Filename, Bucket=self.bucket_name, Key=self.key,
--> 280         ExtraArgs=ExtraArgs, Callback=Callback, Config=Config)
    281 
    282 

/opt/conda/lib/python3.7/site-packages/boto3/s3/inject.py in upload_file(self, Filename, Bucket, Key, ExtraArgs, Callback, Config)
    129         return transfer.upload_file(
    130             filename=Filename, bucket=Bucket, key=Key,
--> 131             extra_args=ExtraArgs, callback=Callback)
    132 
    133 

/opt/conda/lib/python3.7/site-packages/boto3/s3/transfer.py in upload_file(self, filename, bucket, key, callback, extra_args)
    285             raise S3UploadFailedError(
    286                 "Failed to upload %s to %s: %s" % (
--> 287                     filename, '/'.join([bucket, key]), e))
    288 
    289     def download_file(self, bucket, key, filename, extra_args=None,

S3UploadFailedError: Failed to upload data/train.csv to qqnl-autopilot/reuse-autopilot-blog/training_data/train.csv: An error occurred (AccessDenied) when calling the PutObject operation: Access Denied

**Comment by hsl89** [comment]
This is because the bucket does not exist. You can change the beginning of the notebook into 
```
import sagemaker
import os
from sagemaker import get_execution_role

sagemaker_session = sagemaker.Session()

# S3 location to store data
bucket = sagemaker_session.default_bucket()
prefix = 'reuse-autopilot-blog'

# Get a SageMaker-compatible role used by this Notebook Instance.
role = get_execution_role()
```
This should resolve your issue. But the notebook does run end to end. The entry point script is broken and I am working on a PR to fix it.
