### ISSUE TITLE
Principle behind of non possibility of deletion of Training Jobs

### ISSUE THREAD

**Issue by fclesio** [aws/amazon-sagemaker-examples#1535]
Hello I was going thru the issue https://github.com/awslabs/amazon-sagemaker-examples/issues/633 related to the deletion of Training Jobs and the answer was:

>... there is no way to delete a SageMaker Transform Job. The name of each Transform Job must be unique, and each job's metadata will be persisted forever, whether the job Failed or Completed.

I would like to know why it is not possible as we can delete Endpoint Configurations, Endpoints, and Models?

The practical issue: I can run several Training Jobs at the same time or have multiple people doing Training Jobs and see tons of dead status of stale experiments and so on it's non-intuitive.

**Comment by danabens** [comment]
_see tons of dead status of stale experiments and so on it's non-intuitive_

We recently added an SDK method to delete experiments (and all related Trials and Trial Components) if that helps: https://github.com/aws/sagemaker-experiments/blob/main/src/smexperiments/experiment.py#L246

**Comment by seanpmorgan** [comment]
Thanks! Closing as answer was given, but also because this is beyond the scope of the example repository.

**Comment by rlconst** [comment]
@seanpmorgan it's still doesn't answer the question why it's impossible to remove training and transform jobs. Garbage is still garbage
