### ISSUE TITLE
Gluon CIFAR-10 Hyperparameter Tuning notebook exceeding resource limits even when using recommended instance

### ISSUE THREAD

**Issue by aws-rbs** [aws/amazon-sagemaker-examples#1543]
ResourceLimitExceeded: An error occurred (ResourceLimitExceeded) even when using an ml.m4.xlarge notebook. Can change job parameters to void this. Runs fine up to the random hpo search.

Error
ResourceLimitExceeded: An error occurred (ResourceLimitExceeded) when calling the CreateTrainingJob operation: The account-level service limit 'ml.p3.8xlarge for training job usage' is 2 Instances, with current utilization of 3 Instances and a request delta of 1 Instances. Please contact AWS support to request an increase for this limit.

**Comment by aaronmarkham** [comment]
So can it be updated to use a different type that won't fail by default?

**Comment by aws-rbs** [comment]
The notebook says it was tested on an ml.m4.xlarge with vCPU=4 & Memory=6 GB ($0.28/hour).
 I got an out of resources message when I used used the recommended instance, so I used a much larger instance.
The notebook I tried tested it on after on after ml.m4.xlarge failed was ml.p3.8xlarge with vCPU=32 & Memory=244 GB ($14.688/hour). I got an out of resources message, copied above, when I used used the recommended instance.

So the error message ("The account-level service limit 'ml.p3.8xlarge for training job usage' is 2 Instances") seems curious unless there is an internal service agreement that only 2 of the 32 instances are available for training. But that would be odd. I'm reluctant to rerun it given it warns us it can cost up to $400 on the cheaper instance since the larger instance is over 50 time as expensive to run per unit time. But the only part that failed was the tuning that takes up to 2 hours.

So I think we should escalate this issue.

**Comment by aws-rbs** [comment]
Looked at the code and saw the notebook spins up another instance here(step 9) before the random HPO:
def fit_random(job_name, hyperparameters):
    m = MXNet('cifar10.py',
              role=role,
              train_instance_count=1,
              train_instance_type='ml.p3.8xlarge',    #HERE
              framework_version='1.4.1',
              py_version='py3',
              hyperparameters=hyperparameters)
    m.fit(inputs, wait=False, job_name=job_name)

//Failure 2 steps later on jobs = rt.random_search step
//This explains the instance mentioned in the message, but not why it actually fails.
// Tryng: 
train_instance_type='ml.p3.16xlarge'
Specs: ml.p3.16xlarge	64	488 GiB	$28.152/hr
//Failed:An error occurred (ResourceLimitExceeded) when calling the CreateTrainingJob operation: The account-level service limit 'ml.p3.16xlarge for training job usage' is 2 Instances, with current utilization of 3 Instances and a request delta of 1 Instances. Please contact AWS support to request an increase for this limit.
