### ISSUE TITLE
FileNotFoundError; object_detection_birds.ipynb

### ISSUE THREAD

**Issue by ngluna** [aws/amazon-sagemaker-examples#1572]
Folder and .txt file: "CUB_200_2011/classes.txt" is missing in notebook:  https://github.com/awslabs/amazon-sagemaker-examples/blob/master/introduction_to_amazon_algorithms/object_detection_birds/object_detection_birds.ipynb

To recreate issue:
1. Create and open a SageMaker Notebook Instance
2. https://github.com/awslabs/amazon-sagemaker-examples.git
3. Open and "Run All" notebook: object_detection_birds.ipynb

When using Pandas to read in the .txt file:  
`classes_df = pd.read_csv(CLASSES_FILE, sep=' ', names=CLASS_COLS, header=None)`

Notebook returns:  

`FileNotFoundError: [Errno 2] File CUB_200_2011/classes.txt does not exist: 'CUB_200_2011/classes.txt'`

**Comment by ng-j-p** [comment]
This has been fixed in this PR: https://github.com/aws/amazon-sagemaker-examples/pull/1593/files
