### ISSUE TITLE
DeepAR-Electricity example is not compatible with newer versions of Pandas

### ISSUE THREAD

**Issue by iprivit** [aws/amazon-sagemaker-examples#1585]
When running this notebook ran into this error when attempting to use the predictor class:

pandas/_libs/tslibs/c_timestamp.pyx in pandas._libs.tslibs.c_timestamp._Timestamp.__add__()

TypeError: Addition/subtraction of integers and integer-arrays with Timestamp is no longer supported.  Instead of adding/subtracting `n`, use `n * obj.freq`

In code block 24 Line 19 is causing the error:

prediction_time = ts.index[-1] + 1

This needs to be changed to ts.index[-1] +1*ts.index.freq 

However, even after fixing that, there is another error:

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-82-74ca5ceda86e> in <module>
----> 1 predictor.predict(ts=timeseries[120], quantiles=[0.10, 0.5, 0.90]).head()

<ipython-input-80-57276ff31d5b> in predict(self, ts, cat, dynamic_feat, num_samples, return_samples, quantiles)
     21         req = self.__encode_request(ts, cat, dynamic_feat, num_samples, return_samples, quantiles)
     22         res = super(DeepARPredictor, self).predict(req)
---> 23         return self.__decode_response(res, ts.index.freq, prediction_time, return_samples)
     24 
     25     def __encode_request(self, ts, cat, dynamic_feat, num_samples, return_samples, quantiles):

<ipython-input-80-57276ff31d5b> in __decode_response(self, response, freq, prediction_time, return_samples)
     44         predictions = json.loads(response.decode('utf-8'))['predictions'][0]
     45         prediction_length = len(next(iter(predictions['quantiles'].values())))
---> 46         prediction_index = pd.DatetimeIndex(start=prediction_time, freq=freq, periods=prediction_length)
     47         if return_samples:
     48             dict_of_samples = {'sample_' + str(i): s for i, s in enumerate(predictions['samples'])}

TypeError: __new__() got an unexpected keyword argument 'start'

**Comment by seanpmorgan** [comment]
Thanks for reporting. Fixed in #1490
