### ISSUE TITLE
security issues with tensorflow

### ISSUE THREAD

**Issue by aaronmarkham** [aws/amazon-sagemaker-examples#1586]
The following notebooks are pinning to a version of tensorflow with security vulnerabilities.
Recommendation is to remove the pinning, upgrade the notebook, or delete the notebook.

- [x] (https://github.com/aws/amazon-sagemaker-examples/pull/1633) aws_sagemaker_studio/sagemaker_neo_compilation_jobs/deploy_tensorflow_model_on_Inf1_instance/tensorflow_distributed_mnist_neo_inf1_studio.ipynb

- [x] aws_sagemaker_studio/sagemaker_neo_compilation_jobs/tensorflow_distributed_mnist/tensorflow_distributed_mnist_neo_studio.ipynb

- [x] (https://github.com/aws/amazon-sagemaker-examples/pull/1919) sagemaker-python-sdk/tensorboard_keras/tensorboard_keras.ipynb

- [x] (https://github.com/aws/amazon-sagemaker-examples/pull/1896) sagemaker_batch_transform/tensorflow_open-images_tfrecord/code/requirements.txt

**Comment by hsl89** [comment]
Build Errror: 
Exception encountered at "In [8]":
---------------------------------------------------------------------------
ClientError                               Traceback (most recent call last)
<ipython-input-8-b7b00d3481ae> in <module>
      1 mnist_predictor = mnist_estimator.deploy(initial_instance_count=1,
----> 2                                          instance_type='ml.m4.xlarge')

/opt/conda/lib/python3.7/site-packages/sagemaker/estimator.py in deploy(self, initial_instance_count, instance_type, serializer, deserializer, accelerator_type, endpoint_name, use_compiled_model, wait, model_name, kms_key, data_capture_config, tags, **kwargs)
    925             wait=wait,
    926             kms_key=kms_key,
--

[...]

ClientError: An error occurred (ValidationException) when calling the CreateModel operation: Could not find model data at s3://sagemaker-us-west-2-521695447989/tensorflow-training-2021-02-17-01-44-12-426/output/model.tar.gz



----------------------------------------------------------------------
Traceback (most recent call last):
  File "/.pyenv/versions/3.8.3/bin/run-pr-notebooks", line 11, in <module>
    load_entry_point('sagemakerci==0.1.0', 'console_scripts', 'run-pr-notebooks')()
  File "/.pyenv/versions/3.8.3/lib/python3.8/site-packages/sagemakerci/cli/run_pr_notebooks.py", line 75, in main
    raise Exception(
Exception: One or more notebooks failed to execute. Please see above for error messages. If you need more information, please see the CloudWatch logs for the corresponding Processing job.

[Container] 2021/02/17 01:48:04 Command did not exit successfully run-pr-notebooks --pr $PR_NUM --instance $INSTANCE_TYPE exit status 1
[Container] 2021/02/17 01:48:04 Phase complete: BUILD State: FAILED
[Container] 2021/02/17 01:48:04 Phase context status code: COMMAND_EXECUTION_ERROR Message: Error while executing command: run-pr-notebooks --pr $PR_NUM --instance $INSTANCE_TYPE. Reason: exit status 1
[Container] 2021/02/17 01:48:04 Entering phase POST_BUILD
[Container] 2021/02/17 01:48:04 Phase complete: POST_BUILD State: SUCCEEDED
[Container] 2021/02/17 01:48:04 Phase context status code:  Message:
