### ISSUE TITLE
where are the functions input_fn

### ISSUE THREAD

**Issue by AndresUrregoAngel** [aws/amazon-sagemaker-examples#1599]
According to the documentation https://sagemaker.readthedocs.io/en/stable/frameworks/sklearn/using_sklearn.html#create-an-estimator this Sklearn estimator wraps up more functions to handle the input payload to process a prediction , where is that function in this example?

thanks

**Comment by IvyBazan** [comment]
@AndresUrregoAngel Could you specify which example you're referring to?

**Comment by AndresUrregoAngel** [comment]
Here in the official documentation for the Sagemaker framework: https://sagemaker.readthedocs.io/en/stable/frameworks/sklearn/using_sklearn.html theres' a reference to some important functions for serving a model:
* input_fn: Takes request data and deserializes the data into an object for prediction.

* predict_fn: Takes the deserialized request object and performs inference against the loaded model.

* output_fn: Takes the result of prediction and serializes this according to the response content type.

How can we see these functions on the examples for sagemaker sklearn you included in this reporsitory?

**Comment by IvyBazan** [comment]
Here's an example that describes the usage of those functions, as well as how to modify them for a sample use case:
https://github.com/aws/amazon-sagemaker-examples/blob/master/sagemaker-python-sdk/scikit_learn_inference_pipeline/Inference%20Pipeline%20with%20Scikit-learn%20and%20Linear%20Learner.ipynb

**Comment by AndresUrregoAngel** [comment]
Although there are examples full documented, there are others that not call out over the principal functions need it to make the model work
