### ISSUE TITLE
feature_transformation_with_sagemaker_processing

### ISSUE THREAD

**Issue by Olivier-Lakoue** [aws/amazon-sagemaker-examples#1604]
Amazon SageMaker "feature_transformation_with_sagemaker_processing"  Failed. Reason: AlgorithmError
I've just run the exemple without any modifications so i don't understand why.

the log generated by Sagemaker are unreadeable and i'm not able to find the good errors.

someone could help me ?

Thanks in advance.

-------------

Job Name:  spark-preprocessor-2020-10-09-14-27-23-167
Inputs:  [{'InputName': 'code', 'S3Input': {'S3Uri': 's3://sagemaker-eu-west-1-303870020765/spark-preprocessor-2020-10-09-14-27-23-167/input/code/preprocess.py', 'LocalPath': '/opt/ml/processing/input/code', 'S3DataType': 'S3Prefix', 'S3InputMode': 'File', 'S3DataDistributionType': 'FullyReplicated', 'S3CompressionType': 'None'}}]
Outputs:  []
.....................................................*
---------------------------------------------------------------------------
UnexpectedStatusException                 Traceback (most recent call last)
<ipython-input-10-382d84b34787> in <module>
     14                                's3_output_bucket', bucket,
     15                                's3_output_key_prefix', input_preprocessed_prefix],
---> 16                     logs=False)

~/anaconda3/envs/python3/lib/python3.6/site-packages/sagemaker/processing.py in run(self, code, inputs, outputs, arguments, wait, logs, job_name, experiment_config)
    405         self.jobs.append(self.latest_job)
    406         if wait:
--> 407             self.latest_job.wait(logs=logs)
    408 
    409     def _get_user_code_name(self, code):

~/anaconda3/envs/python3/lib/python3.6/site-packages/sagemaker/processing.py in wait(self, logs)
    731             self.sagemaker_session.logs_for_processing_job(self.job_name, wait=True)
    732         else:
--> 733             self.sagemaker_session.wait_for_processing_job(self.job_name)
    734 
    735     def describe(self):

~/anaconda3/envs/python3/lib/python3.6/site-packages/sagemaker/session.py in wait_for_processing_job(self, job, poll)
   2558         """
   2559         desc = _wait_until(lambda: _processing_job_status(self.sagemaker_client, job), poll)
-> 2560         self._check_job_status(job, desc, "ProcessingJobStatus")
   2561         return desc
   2562 

~/anaconda3/envs/python3/lib/python3.6/site-packages/sagemaker/session.py in _check_job_status(self, job, desc, status_key_name)
   2669                 ),
   2670                 allowed_statuses=["Completed", "Stopped"],
-> 2671                 actual_status=status,
   2672             )
   2673 

UnexpectedStatusException: Error for Processing job spark-preprocessor-2020-10-09-14-27-23-167: Failed. Reason: AlgorithmError: See job logs for more information

**Comment by AnilisonGit** [comment]
@Olivier-Lakoue Did you ever get this sorted? I am seeing the same issue and there is nothing in the cloudwatch logs either
