### ISSUE TITLE
Ensemble Learner XGboost and Linear Learner - `as_matrix` depricated

### ISSUE THREAD

**Issue by FabG** [aws/amazon-sagemaker-examples#1614]
Hi,

The following [ensemble notebook](https://github.com/aws/amazon-sagemaker-examples/tree/master/introduction_to_applying_machine_learning/ensemble_modeling) has an issue.

The cells that are referencing `as_matrix()` need to be updated to use `

Example:
`datav = data.iloc[offset:(offset+batch_size),:].as_matrix()`
should read
 `datav = data.iloc[offset:(offset+batch_size),:].to_numpy()`

Reason:
The `as_matrix` method is deprecated since 0.23.0, so you should use `to_numpy` instead.

Enclosed is my notebook with the fix for reference: [ensemble-learner-census-income.ipynb.zip](https://github.com/aws/amazon-sagemaker-examples/files/5373491/ensemble-learner-census-income.ipynb.zip)

**Comment by seanpmorgan** [comment]
Hi @FabG thanks for reporting! This has been fixed. CI was passing on the last PR:
https://github.com/aws/amazon-sagemaker-examples/issues/1614
