### ISSUE TITLE
Sagemaker A2I task time limit

### ISSUE THREAD

**Issue by sudhirnitw** [aws/amazon-sagemaker-examples#1626]
How long does A2I sagemaker task stays in the user's task list, if it's not been worked on?

**Comment by TEChopra1000** [comment]
@sudhirnitw this is determined by your specification for **`TaskTimeLimitInSeconds`** when you create your human review workflow (flow definition) using [CreateFlowDefinition](https://docs.aws.amazon.com/sagemaker/latest/APIReference/API_CreateFlowDefinition.html)

In the console, to configure this you specify a "Take timeout" when you create a human review workflow, which corresponds to this parameter, `TaskTimeLimitInSeconds`.
