### ISSUE TITLE
ModelError: An error occurred (ModelError) when calling the InvokeEndpoint operation: Received server error (500) from model with message "No module named 'sagemaker'"

### ISSUE THREAD

**Issue by knightz33** [aws/amazon-sagemaker-examples#1657]
Hi there, 

I am trying to invoke the endpoint. However, when I try to invoke it using `response = runtime.invoke_endpoint(EndpointName='pytorch-inference-2020-10-26-06-57-44-011', Body=payload)`, I get this error: 

> ModelError: An error occurred (ModelError) when calling the InvokeEndpoint operation: Received server error (500) from model with message "No module named 'sagemaker'". See https://ap-southeast-1.console.aws.amazon.com/cloudwatch/home?region=ap-southeast-1#logEventViewer:group=/aws/sagemaker/Endpoints/pytorch-inference-2020-10-26-06-57-44-011 in account 583324212064 for more information.

Any help is appreciated. I am also using fastai and trying to deploy my model on sagemaker

Thanks!!

**Comment by hsl89** [comment]
@knightz33 can you list which notebook and cell this issue is referring to?

**Comment by knightz33** [comment]
Hi i managed to solve it.

**Comment by zwbgood6** [comment]
Can you tell me how you solve this problem? I face the same error. Thanks!
