### ISSUE TITLE
[Question] TensorBoard in Local Mode

### ISSUE THREAD

**Issue by austinmw** [aws/amazon-sagemaker-examples#1707]
Hi, in non-local training mode, I'm able to set up TensorBoard via:

```python
from sagemaker.debugger import TensorBoardOutputConfig
# train.py writes Events files container_local_output_path
tensorboard_output_config = TensorBoardOutputConfig(
    s3_output_path=f's3://{bucket}/{experiment_name}/',
    container_local_output_path='/tensorboard'
)
```
Then pass `tensorboard_output_config` to my estimator

And I can access the S3 path for tensorboard's `--logdir` arg via `estimator.latest_job_tensorboard_artifacts_path()`

However, I'm unable to figure out how to use TensorBoard in **Local Mode**. Is this possible or no?

No data gets streamed to the specified `s3_output_path` when running local training. I also tried specifying a local path of `file:///tmp/tensorboard/`, but this doesn't appear to work either.

If TensorBoard events files are inaccessible in Local Mode, writing and debugging TensorBoard logging code (for example getting annotated images to display how you'd like) becomes an extremely time consuming process as you'd need to wait for EC2 jobs to launch and sync events files to S3 after every code modification.

**Comment by cfregly** [comment]
Here’s an example how to run and view tensorboard through your SageMaker notebook:  https://github.com/data-science-on-aws/workshop/blob/f94f776dc994199563df8f6da523c56df2a074bc/08_train/wip/99_Tensorboard_AdHoc.ipynb

**Comment by austinmw** [comment]
@cfregly Thanks, but I understand how to run the TensorBoard server. My question is related to how to point the server to events files created by local mode training, since these local events files do not seem to get sent to S3.

**Comment by mchoi8739** [comment]
TensorBoard output config is a feature supported by SageMaker Debugger. Here's the doc that guides how to set up the stream using SageMaker Debugger: https://docs.aws.amazon.com/sagemaker/latest/dg/debugger-enable-tensorboard-summaries.html
