### ISSUE TITLE
Please update semantic_segmentation_pascalvoc.ipynb with Sagemaker v2 syntax

### ISSUE THREAD

**Issue by Andres-G** [aws/amazon-sagemaker-examples#1708]
Hello,

please update the semantic_segmentation_pascalvoc.ipynb with the latest sagemaker v2 syntax as the notebook will not currently run as-is. 

Thanks,
Andres

**Comment by paul-cb** [comment]
Thanks @Andres-G . This notebook has been updated and fixed. Closing.
