### ISSUE TITLE
Install python libraries for PySparkProcessor

### ISSUE THREAD

**Issue by Kukabunga** [aws/amazon-sagemaker-examples#1712]
Hi,

I was wondering if there is way to install additional python libraries when you run **PySparkProcessor**. 

As far as I understand in order to run you own processing jobs I can use **ScriptProcessor** but it doesn include PySpark which is essential in my case. 
I can also build my own Docker image with all the dependecies like Hadoop it's kinda a lot of work.
I can also add some files in **submit_files** in run method of **PySparkProcessor** but it's not always going to work.
There is also way to install packages directly from python but I guess that's not cool :)

And finally I can extend **sagemaker-spark-processing:2.4-cpu-py37-v1.0** Docker image and install everything I want. I guess this it the best way that I found :)

So I was wondering if there is a better straightforward solution for this. Maybe I'm missing something.

**Comment by paul-cb** [comment]
Hi @Kukabunga, a few solutions here. You can pip install any new python libraries in your environment at the top of your script. Alternatively, you could extend your Docker image. See here https://docs.aws.amazon.com/sagemaker/latest/dg/docker-containers-adapt-your-own.html. 

Let me know if this is resolved. Thanks!

**Comment by Kukabunga** [comment]
> Hi @Kukabunga, a few solutions here. You can pip install any new python libraries in your environment at the top of your script. Alternatively, you could extend your Docker image. See here https://docs.aws.amazon.com/sagemaker/latest/dg/docker-containers-adapt-your-own.html.
> 
> Let me know if this is resolved. Thanks!

Hi @paul-cb,

Thanks for the reply. Yeah I ended up extending the pre-build image. I think this is the best solution 👍
