### ISSUE TITLE
I am unable to connect snowflake to sagemaker deepar 

### ISSUE THREAD

**Issue by tg-pawan** [aws/amazon-sagemaker-examples#1788]
did any had code how to connect snowflake to sagemaker jupyter notebook.  when i am using this code

**Comment by tg-pawan** [comment]
%bash
CFFI_VERSION=$(pip list 2>/dev/null | grep cffi )
echo $CFFI_VERSION
if [[ "$CFFI_VERSION" == "cffi (1.10.0)" ]]
then 
   pip uninstall --yes cffi
fi
yum_log=$(sudo yum install -y libffi-devel openssl-devel)
pip_log=$(pip install --upgrade snowflake-connector-python)  
if [[ "$CFFI_VERSION" == "cffi (1.10.0)" ]]
then 
   echo "configuration has changed; restart notebook"
fi

getting error this code is given in databrick community

**Comment by hsl89** [comment]
hi @tg-pawan, is your question related to a specific notebook?

**Comment by hsl89** [comment]
close for lack of activity
