### ISSUE TITLE
Sagemaker notebook stuck in "Stopping" over 1 hour

### ISSUE THREAD

**Issue by acking91** [aws/amazon-sagemaker-examples#1798]
This morning I went to stop and start a notebook and it has been stuck in "Stopping" for over one hour. Unlike EC2, I cannot find a "Force Stop" option either in the console, or in the CLI. 

Running "stop-notebook-instance" on the CLI doesn't help. 

```
aws sagemaker stop-notebook-instance --notebook-instance-name AKing-Service-Mapping

An error occurred (ValidationException) when calling the StopNotebookInstance operation: Status (Stopping) not in ([InService]). Unable to transition to (Stopping) for Notebook Instance (arn:aws:sagemaker:us-east-1:013597205841:notebook-instance/aking-service-mapping).
```

Thread on AWS Forums: https://forums.aws.amazon.com/thread.jspa?threadID=331767

**Comment by acking91** [comment]
Seems issue was caused by US-East-1 region failure two days ago, still don't know how to force stop SageMaker instances though.

**Comment by Ahmant** [comment]
@acking91 
Hello,

Did you managed to solve it?
It happened to us yesterday after the AWS downtime, and our notebook is in the `Stopping` state for more than 20 hours
