### ISSUE TITLE
CIFAR 10 with MXNet Gluon Moved

### ISSUE THREAD

**Issue by Wei-1** [aws/amazon-sagemaker-examples#1802]
In this page:
https://github.com/aws/amazon-sagemaker-examples/tree/master/sagemaker-python-sdk#amazon-sagemaker-pre-built-framework-containers-and-the-python-sdk

The item
 - cifar 10 with MXNet Gluon

The item had been moved to hyper-parameter-tuning, but the link is still there. We should either remove the link from the README.md or add the link to:

https://github.com/aws/amazon-sagemaker-examples/blob/master/hyperparameter_tuning/mxnet_gluon_cifar10_random_search/hyperparameter_tuning_mxnet_gluon_cifar10_random_search.ipynb

**Comment by AnshumanRanjan** [comment]
The example you pointed does not have local mode on it . That files has been completely removed  . I can see it was present in a previous branch : https://github.com/aws/amazon-sagemaker-examples/tree/fa5167f01cedbf3a0d9ba3270f507b4a6df3f4ff/sagemaker-python-sdk/mxnet_gluon_cifar10


Also there are two references of this  notebook which needs to get fixed : 
a)  In AWS Blogs : https://aws.amazon.com/blogs/machine-learning/use-the-amazon-sagemaker-local-mode-to-train-on-your-notebook-instance/

(Paragraph 6 links point to this notebook which now does not exist )

b)  https://github.com/aws/amazon-sagemaker-examples/tree/master/sagemaker-python-sdk  , README.md file  still points to the non existant notebook
