### ISSUE TITLE
Upgrading the SageMaker SDK version in SageMaker Pipeline Sample notebook

### ISSUE THREAD

**Issue by dhawalkp** [aws/amazon-sagemaker-examples#1830]
Issue:

The notebook at [SageMaker Pipeline Notebook](https://github.com/aws/amazon-sagemaker-examples/blob/master/sagemaker-pipelines/sagemaker-pipelines-preprocess-train-evaluate-batch-transform.ipynb) is throwing an error message of from `sagemaker.workflow.parameters package cannot be found` at line below

```
from sagemaker.workflow.parameters import (
    ParameterInteger,
    ParameterString,
)
```

This is because the conda packages available in the existing SageMaker Studio Images are still having older version of SDK.

**Comment by dhawalkp** [comment]
Did not fix for me atleast.
Also, For the conventional sagemaker notebooks, it will still to upgrade the SDK

**Comment by seanpmorgan** [comment]
Confirmed that this notebook (now moved to https://github.com/aws/amazon-sagemaker-examples/blob/master/sagemaker-pipelines/tabular/abalone_build_train_deploy/sagemaker-pipelines-preprocess-train-evaluate-batch-transform.ipynb) runs successfully on Studio. 

Closing but please let us know if there is still issue.
