### ISSUE TITLE
xgboost direct marketing example doesn't make sense

### ISSUE THREAD

**Issue by mattflo-outpace** [aws/amazon-sagemaker-examples#184]
Something doesn't seem right about this example.

https://github.com/awslabs/amazon-sagemaker-examples/blob/master/introduction_to_applying_machine_learning/xgboost_direct_marketing/xgboost_direct_marketing_sagemaker.ipynb

The notes in the Exploration section indicate correctly that 90% of the of the customers do not subscribe. 

The notes in the Evaluation section says ~3700 customers from the test data set were predicted to subscribe. The test data set has right around 4,000 (10% of the whole dataset). So the model that was built predicts a vast majority of subscribers. What's going on here?

**Comment by djarpin** [comment]
Thanks for catching this error!  I've submitted a [PR](https://github.com/awslabs/amazon-sagemaker-examples/pull/185) with a fix.  We'll dig into the root cause as well.

Thanks for your interest in SageMaker.

**Comment by mattflo-outpace** [comment]
I've attached the ipynb in question. I executed all of the sample code. I also built a model with xgboost directly to show the vast difference in model performance.
[xgboost_direct_marketing_sagemaker.ipynb.gz](https://github.com/awslabs/amazon-sagemaker-examples/files/1690162/xgboost_direct_marketing_sagemaker.ipynb.gz)

**Comment by hsl89** [comment]
I am closing it now due to lack of activity, please open it again it the issue persists.
