### ISSUE TITLE
Debugger hooks for custom model

### ISSUE THREAD

**Issue by shubhamsharma1609** [aws/amazon-sagemaker-examples#1842]
Is there anyway we can create tensorplots for a custom model we defined ? For example I am using kerasunet library and want to analyse the tensors by creating tensorplots.Please guide how we can deal with custom models in this case.

**Comment by Vikas-kum** [comment]
Can you check if this helps - 

https://github.com/awslabs/sagemaker-debugger/blob/master/docs/tensorflow.md#using-debugger-on-sagemaker-training-containers-and-custom-containers

**Comment by hsl89** [comment]
close for lack of activity
