### ISSUE TITLE
The primary container for production variant AllTraffic did not pass the ping health check. Please check CloudWatch logs for this endpoint.

### ISSUE THREAD

**Issue by SniKerZ1** [aws/amazon-sagemaker-examples#1853]
Cloud watch logs shows :

nginx = subprocess.Popen(['nginx', '-c', '/opt/program/nginx.conf'])  File "/usr/local/lib/python3.6/subprocess.py", line 729, in __init__    restore_signals, start_new_session)  File "/usr/local/lib/python3.6/subprocess.py", line 1364, in _execute_child    raise child_exception_type(errno_num, err_msg, err_filename)

FileNotFoundError: [Errno 2] No such file or directory: 'nginx': 'nginx'

**Comment by SniKerZ1** [comment]
also facing similar issues with ln -sf /dev/stderr /var/log/nginx/error.log

FileNotFoundError: [Errno 2] No such file or directory: '/var/log/nginx/error.log'

**Comment by hsl89** [comment]
@SniKerZ1 which notebook are you trying to run?
