### ISSUE TITLE
Getting error  KeyError: 'num_classes' with image classifier 

### ISSUE THREAD

**Issue by rpostulart** [aws/amazon-sagemaker-examples#1859]
<img width="1440" alt="Screenshot 2020-12-11 at 07 57 41" src="https://user-images.githubusercontent.com/21346629/101915788-66408580-3bc6-11eb-9876-0f23ffcec8a4.png">

<img width="1440" alt="Screenshot 2020-12-11 at 07 57 36" src="https://user-images.githubusercontent.com/21346629/101915820-6e98c080-3bc6-11eb-9829-1023bb702bd6.png">

<img width="1440" alt="Screenshot 2020-12-11 at 07 57 22" src="https://user-images.githubusercontent.com/21346629/101915848-76586500-3bc6-11eb-82e1-238293dbefa2.png">

**Comment by ngluna** [comment]
Hello, 
Can you provide the notebook URL or the name of the notebook?

**Comment by hsl89** [comment]
closing for now due to lack of activity. Feel free to reopen with more complete issue description.
