### ISSUE TITLE
LabelCategoryConfigS3URI: discrepancy in the documentation.

### ISSUE THREAD

**Issue by threeoceansassets** [aws/amazon-sagemaker-examples#1861]
[This repository example](https://github.com/aws/amazon-sagemaker-examples/blob/master/ground_truth_labeling_jobs/from_unlabeled_data_to_deployed_machine_learning_model_ground_truth_demo_image_classification/from_unlabeled_data_to_deployed_machine_learning_model_ground_truth_demo_image_classification.ipynb) defines the LabelCategoryConfigS3URI as
 `json_body = {
    'labels': [{'label': label} for label in CLASS_LIST]
} ` ,
but [the boto3 docs](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/sagemaker.html#SageMaker.Client.create_labeling_job)  require
 `{
"document-version": "2018-11-28"
"labels": [
{
"label": "*label_1* "
},
{
"label": "*label_2* "
},
...
{
"label": "*label_n* "
}
]
}
`
Which one is correct?

**Comment by TEChopra1000** [comment]
@threeoceansassets you should include `"document-version": "2018-11-28"`. We will update the notebook to include it.

**Comment by TEChopra1000** [comment]
Closing this ticket. @threeoceansassets please reopen if you have any outstanding issues.
