### ISSUE TITLE
Broken Links in Image-classification-multilabel-lst.ipynb

### ISSUE THREAD

**Issue by TylerADavis** [aws/amazon-sagemaker-examples#1870]
The notebook contains links intended to describe the recordio and lst formats, but they now lead to 404 pages.

I'm not sure what the correct link should be, as the original content seems to have been retired.

Notebook with broken link: https://github.com/aws/amazon-sagemaker-examples/blob/master/introduction_to_amazon_algorithms/imageclassification_mscoco_multi_label/Image-classification-multilabel-lst.ipynb

Line with broken link: The image classification algorithm can take two types of input formats. The first is a **recordio** format and the other is a **lst** format. We will use the lst file format for training.

Broken links: 
https://mxnet.incubator.apache.org/tutorials/basic/record_io.html
https://mxnet.incubator.apache.org/how_to/recordio.html?highlight=im2rec

Potential replacements:
https://mxnet.apache.org/versions/1.7.0/api/faq/recordio
https://mxnet.apache.org/versions/1.7.0/api/python/docs/api/mxnet/recordio/index.html

**Comment by seanpmorgan** [comment]
Thanks for reporting! Fixed with https://github.com/aws/amazon-sagemaker-examples/pull/1921

**Comment by TylerADavis** [comment]
Thanks!
