### ISSUE TITLE
smp_bert_tutorial.ipynb has typo

### ISSUE THREAD

**Issue by muhyun** [aws/amazon-sagemaker-examples#1872]
In training/distributed_training/pytorch/model_parallel/bert/smp_bert_tutorial.ipynb,

```
"mpi": {
    "enabled": True,
    "process_per_host": 8,
    "custom_mpi_options": mpi_options,
}
```

Here, `process_per_host` has typo. It should be `processes_per_host`.

**Comment by TEChopra1000** [comment]
Issue has been resolved.
