### ISSUE TITLE
sagemaker lamda integration error

### ISSUE THREAD

**Issue by MATDSL** [aws/amazon-sagemaker-examples#1881]
Dear all

Am getting this error when invoking sagemaker endpoint from lambda function.could  you pls help

Response:
{
  "errorMessage": "An error occurred (ModelError) when calling the InvokeEndpoint operation: Received client error (400) from model with message \"unable to evaluate payload provided\". See https://ap-southeast-1.console.aws.amazon.com/cloudwatch/home?region=ap-southeast-1#logEventViewer:group=/aws/sagemaker/Endpoints/DEMO-linear-endpoint-202012190430 in account 112753223654 for more information.",
  "errorType": "ModelError",
  "stackTrace": [
    "  File \"/var/task/lambda_function.py\", line 21, in lambda_handler\n    response = runtime.invoke_endpoint(EndpointName=ENDPOINT_NAME,\n",
    "  File \"/var/runtime/botocore/client.py\", line 357, in _api_call\n    return self._make_api_call(operation_name, kwargs)\n",
    "  File \"/var/runtime/botocore/client.py\", line 676, in _make_api_call\n    raise error_class(parsed_response, operation_name)\n"
  ]
}

the program is below
import os
import io
import boto3
import json
import csv

# grab environment variables
ENDPOINT_NAME = os.environ['ENDPOINT_NAME']
runtime= boto3.client('runtime.sagemaker')
print("ENDPOINT_NAME")
#data = [6.4, 3.2, 4.5, 1.5]
#print(data)

def lambda_handler(event, context):
    print("Received event: " + json.dumps(event, indent=2))
    
    data = json.loads(json.dumps(event))
    payload = data["data"]
    print("Ramanan:" + payload)
    
    response = runtime.invoke_endpoint(EndpointName=ENDPOINT_NAME,
                                       ContentType='text/csv',
                                       Body=payload)
    print(response)
    #result = json.loads(response['Body'].read().decode())
    #print(result)
    #pred = int(result['predictions'][0]['score'])
    #predicted_label = 'M' if pred == 1 else 'B'
    
    #return predicted_label
    return payload

**Comment by poojaprabhu28** [comment]
Hi! I faced the same issue and It was due to error in Access ID and Secret Access Key. Please check your permissions (if you are using any) and give it a try.

**Comment by hsl89** [comment]
hi @MATDSL, the link to the cloudwatch you provided above requires logins of your own AWS account. Please paste the detailed error here, so that we can take a look.

**Comment by MATDSL** [comment]
please find the detailed error here

C:\Users\Ramanan>aws sagemaker-runtime invoke-endpoint --endpoint-name DEMO-linear-endpoint-202012190430 --body "[1,3,4]" --content-type application/json --accept application/json results

An error occurred (ModelError) when calling the InvokeEndpoint operation: Received client error (400) from model with message "unable to evaluate payload provided". See https://ap-southeast-1.console.aws.amazon.com/cloudwatch/home?region=ap-southeast-1#logEventViewer:group=/aws/sagemaker/Endpoints/DEMO-linear-endpoint-202012190430 in account 112753223654 for more information.

**Comment by hsl89** [comment]
Hi @MATDSL, try here https://stackoverflow.com/questions/tagged/amazon-sagemaker

**Comment by dayo777** [comment]
Hello all, I am also facing the same issue. I am trying to invoke sagemaker through AWS Lambda but getting an error, i do not understand what to do about it, 

```
Test Event Name
test-invokation

Response
{
  "errorMessage": "An error occurred (ModelError) when calling the InvokeEndpoint operation: Received client error (400) from primary and could not load the entire response body. See https://us-east-1.console.aws.amazon.com/cloudwatch/home?region=us-east-1#logEventViewer:group=/aws/sagemaker/Endpoints/jira-endpoint in account my-account-id for more information.",
  "errorType": "ModelError",
  "stackTrace": [
    "  File \"/var/task/lambda_function.py\", line 19, in lambda_handler\n    response = runtime.invoke_endpoint(EndpointName=ENDPOINT_NAME,\n",
    "  File \"/var/runtime/botocore/client.py\", line 565, in _api_call\n    return self._make_api_call(operation_name, kwargs)\n",
    "  File \"/var/runtime/botocore/client.py\", line 1021, in _make_api_call\n    raise error_class(parsed_response, operation_name)\n"
  ]
}
```
