### ISSUE TITLE
Deploying preprocessing container

### ISSUE THREAD

**Issue by pritesh-aidash** [aws/amazon-sagemaker-examples#1894]
What is the best way to deploy the preprocessing container? I tried using a pipeline for training, but not sure if there is a way to deploy a pipeline for inference. Can someone please help me with ideas. 

My preprocessing container is pretty involved with dependencies of Gdal and Opencv; so the SKLearn and SparkML preprocessing images will not help.

**Comment by seanpmorgan** [comment]
Hi @pritesh-aidash could you clarify what "pipeline" you're referring to? Is this SageMaker Pipelines or just the general term for a workflow being ran?

SageMaker processing jobs have full support for custom containers so you should be able to run your specialized container:
https://docs.aws.amazon.com/sagemaker/latest/dg/processing-container-run-scripts.html

**Comment by pritesh-aidash** [comment]
I was referring to the sagemaker pipeline.

**Comment by seanpmorgan** [comment]
So IIUC you want a pipeline to be triggered from an inference endpoint. That may not the best fit for Pipelines (more used for CI/CD of training and deploying models). If you have a preprocessing step that needs to run in the serving container at inference time, you're probably better off including that step/dependency in the hosting container. Here's an example of a custom Docker container for model hosting... you could modify that to include your opencv deps etc:
https://github.com/aws/amazon-sagemaker-examples/tree/master/advanced_functionality/multi_model_bring_your_own

Closing but let us know if this didn't meet your needs and we can re-open and continue discussion.

**Comment by pritesh-aidash** [comment]
Thanks Sean, we solved the issue by moving the preprocessing to an Estimator. Since our preprocessing was pretty heavy, and useful outside this particular model, we wanted to keep this separate from the training code. Though our problem is sorted for now, I guess it would be great to be able to deploy a ScriptProcessor to an endpoint just like a model.

**Comment by seanpmorgan** [comment]
Sounds good @pritesh-aidash, I forgot to mention InferencePipelines which very much fits what you're looking to do:
https://docs.aws.amazon.com/sagemaker/latest/dg/inference-pipelines.html
