### ISSUE TITLE
Missing "\n" in json

### ISSUE THREAD

**Issue by Previatto** [aws/amazon-sagemaker-examples#1902]
Hello, I was testing the mnist-handwritten-digits-classification-experiment and I encountered a little problem in the notebook (last line has 2 commands instead of being 2 lines):

![image](https://user-images.githubusercontent.com/32130824/103557602-30738180-4e92-11eb-8806-bc2f767d4ad6.png)

It's simple and I believe that a '\n' at the end of this line will solve it.

https://github.com/aws/amazon-sagemaker-examples/blob/5bc2f130628be553dcc38b0a0780f891a37226bf/sagemaker-experiments/mnist-handwritten-digits-classification-experiment/mnist-handwritten-digits-classification-experiment.ipynb#L67

**Comment by ngluna** [comment]
Thanks for catching that.
PR fixing this can be found here: https://github.com/aws/amazon-sagemaker-examples/pull/1905
