### ISSUE TITLE
[Batch Transform] sagemaker_batch_transform/tensorflow_open-images_tfrecord/tensorflow-serving-tfrecord.cli.ipynb fail on batch transform jobs

### ISSUE THREAD

**Issue by mchoi8739** [aws/amazon-sagemaker-examples#1903]
The batch transform job fails with the following error:

```
Waiter TransformJobCompletedOrStopped failed: Waiter encountered a terminal failure state: For expression "TransformJobStatus" we matched expected path: "Failed"
fatal error: An error occurred (404) when calling the HeadObject operation: Key "sagemaker/DEMO-tf-batch-inference-jpeg-images-python-sdk/output/train-00001-of-00100.out" does not exist
```

**Comment by mchoi8739** [comment]
```
%%bash
aws s3 ls "sagemaker-us-east-1-688520471316/sagemaker/DEMO-tf-batch-inference-jpeg-images-python-sdk/"
```
This returns only a `model/` directory. There's no `output/` directory created

**Comment by mchoi8739** [comment]
from CW log:
```
2021-01-01T02:14:20.293:[sagemaker logs]: sagemaker-sample-data-us-east-1/batch-transform/open-images/tfrecord/train-00099-of-00100: 
{
    "error": "module 'tensorflow' has no attribute 'train'"
}
```

**Comment by mchoi8739** [comment]
The example uses SageMaker TF serving container at https://github.com/aws/sagemaker-tensorflow-serving-container#sagemaker-tensorflow-serving-container

However, it uses TF 1.13, which doesn't seem supported by the SM TF servin container repo.

> 'sagemaker-tensorflow-serving' for 1.4.1, 1.5.0, 1.6.0, 1.7.0, 1.8.0, 1.9.0, 1.10.0, 1.11.0, 1.12.0 versions in the following AWS accounts:
    "057415533634" in "ap-east-1";
    "724002660598" in "me-south-1";
    "520713654638" in other SageMaker public regions.

**Comment by seanpmorgan** [comment]
Closing as this was resolved. Thanks!
