### ISSUE TITLE
An error occurred (403) when calling the HeadObject operation: Forbidden while executing Script-mode Custom Training Container (2)

### ISSUE THREAD

**Issue by AnkurShukla85** [aws/amazon-sagemaker-examples#1931]
While executing https://github.com/aws/amazon-sagemaker-examples/blob/master/advanced_functionality/custom-training-containers/script-mode-container-2/notebook/script-mode-container-2.ipynb step by step. 

I am getting an error while fitting the estimator :
Creating tmpdihkgx52_algo-1-xwmby_1 ... 
Attaching to tmpdihkgx52_algo-1-xwmby_12mdone
algo-1-xwmby_1  | 2021-01-13 06:06:12,724 sagemaker-training-toolkit ERROR    Reporting training FAILURE
algo-1-xwmby_1  | 2021-01-13 06:06:12,724 sagemaker-training-toolkit ERROR    framework error: 
algo-1-xwmby_1  | Traceback (most recent call last):
algo-1-xwmby_1  |   File "/usr/local/lib/python3.6/site-packages/sagemaker_training/trainer.py", line 97, in train
algo-1-xwmby_1  |     runner_type=runner_type,
algo-1-xwmby_1  |   File "/usr/local/lib/python3.6/site-packages/sagemaker_training/entry_point.py", line 92, in run
algo-1-xwmby_1  |     files.download_and_extract(uri=uri, path=environment.code_dir)
algo-1-xwmby_1  |   File "/usr/local/lib/python3.6/site-packages/sagemaker_training/files.py", line 131, in download_and_extract
algo-1-xwmby_1  |     s3_download(uri, dst)
algo-1-xwmby_1  |   File "/usr/local/lib/python3.6/site-packages/sagemaker_training/files.py", line 167, in s3_download
algo-1-xwmby_1  |     s3.Bucket(bucket).download_file(key, dst)
algo-1-xwmby_1  |   File "/usr/local/lib/python3.6/site-packages/boto3/s3/inject.py", line 246, in bucket_download_file
algo-1-xwmby_1  |     ExtraArgs=ExtraArgs, Callback=Callback, Config=Config)
algo-1-xwmby_1  |   File "/usr/local/lib/python3.6/site-packages/boto3/s3/inject.py", line 172, in download_file
algo-1-xwmby_1  |     extra_args=ExtraArgs, callback=Callback)
algo-1-xwmby_1  |   File "/usr/local/lib/python3.6/site-packages/boto3/s3/transfer.py", line 307, in download_file
algo-1-xwmby_1  |     future.result()
algo-1-xwmby_1  |   File "/usr/local/lib/python3.6/site-packages/s3transfer/futures.py", line 106, in result
algo-1-xwmby_1  |     return self._coordinator.result()
algo-1-xwmby_1  |   File "/usr/local/lib/python3.6/site-packages/s3transfer/futures.py", line 265, in result
algo-1-xwmby_1  |     raise self._exception
algo-1-xwmby_1  |   File "/usr/local/lib/python3.6/site-packages/s3transfer/tasks.py", line 255, in _main
algo-1-xwmby_1  |     self._submit(transfer_future=transfer_future, **kwargs)
algo-1-xwmby_1  |   File "/usr/local/lib/python3.6/site-packages/s3transfer/download.py", line 343, in _submit
algo-1-xwmby_1  |     **transfer_future.meta.call_args.extra_args
algo-1-xwmby_1  |   File "/usr/local/lib/python3.6/site-packages/botocore/client.py", line 357, in _api_call
algo-1-xwmby_1  |     return self._make_api_call(operation_name, kwargs)
algo-1-xwmby_1  |   File "/usr/local/lib/python3.6/site-packages/botocore/client.py", line 676, in _make_api_call
algo-1-xwmby_1  |     raise error_class(parsed_response, operation_name)
algo-1-xwmby_1  | botocore.exceptions.ClientError: An error occurred (403) when calling the HeadObject operation: Forbidden
algo-1-xwmby_1  | 
algo-1-xwmby_1  | An error occurred (403) when calling the HeadObject operation: Forbidden
tmpdihkgx52_algo-1-xwmby_1 exited with code 1
Aborting on container exit...

**Comment by hsl89** [comment]
hi @AnkurShukla85 , I was not able to reproduce your error. What policies did you attach to the execution role?

**Comment by hsl89** [comment]
feel free to reopen if the issue persists
