### ISSUE TITLE
Save the model file into S3 Bucket fails

### ISSUE THREAD

**Issue by artjoms-formulevics** [aws/amazon-sagemaker-examples#1932]
All works fine, if define the arguments, train the model and output the file:

    parser.add_argument('--model-dir', type=str, default=os.environ.get('SM_MODEL_DIR'))
    parser.add_argument('--train', type=str, default=os.environ.get('SM_CHANNEL_TRAIN'))
    parser.add_argument('--test', type=str, default=os.environ.get('SM_CHANNEL_TEST'))
    
    # train the model...
    
    joblib.dump(model, os.path.join(args.model_dir, "model.joblib"))

And call the job with:

    aws_sklearn.fit({'train': 's3://path/to/train', 'test': 's3://path/to/test'}, wait=False)

In this case model gets stored on different auto-generated bucket, which I do not want. I want to get the output (.joblib file) in the same s3 bucket I took data from. So I add the parameter `model-dir`:

    aws_sklearn.fit({'train': 's3://path/to/train', 'test': 's3://path/to/test', `model-dir`: 's3://path/to/model'}, wait=False)

But it results in error:
`FileNotFoundError: [Errno 2] No such file or directory: 's3://path/to/model/model.joblib'`

Same happens if I hardcode the output path inside the training script.

Am I missing something?

**Comment by hsl89** [comment]
Hello @artjoms-formulevics , please post the question here https://stackoverflow.com/questions/tagged/amazon-sagemaker
