### ISSUE TITLE
Aws sagemaker object detection inference on video clip

### ISSUE THREAD

**Issue by thasin96** [aws/amazon-sagemaker-examples#1933]
I am new to aws sage maker. I have trained a custom object detection model using sagemaker's object detection algorithm. I am happy with the accuracy. Now, I would like to perform inference on video clip which is located in S3 bucket. 
Before performing, I would like to get recommendation from AWS developers to what is the recommended way to achieve the above scenario? 

I have integrated kvs stream to my deployed EC2 instance using cloudformation. But, for video clip what's the recommended way? 

1. How to pick stable frames from the clip?
2. How to visualize the result video?

**Comment by hsl89** [comment]
Hi @thasin96 , please post the question here https://stackoverflow.com/questions/tagged/amazon-sagemaker
