### ISSUE TITLE
Provide example of input pre processing and prediction post processing

### ISSUE THREAD

**Issue by datagrayaaa** [aws/amazon-sagemaker-examples#1943]
This repo provides many fine examples of setting up different models, training them, and creating an API which can be called to predict on new data.  The problem is the examples are using toy data that is prediction ready and show the API calls being used with the same toy data.

But generally incoming data must be cleaned and transformed. Out going predictions must be parsed, scaled, and formatted. There does not seem to be a clear example of how to do this or wire these processes together when setting up a sagemaker predictor.

What is lacking is a clear example of how to configure a function or script that can can take that API input and process the data before passing it to the model for the prediction.  If you feel it already exists, then the issue would instead be that it is not clearly mentioned or linked to in the repo's readme.

And similarly, once the model is called, how can the prediction be sent to a post processing script prior to the api returning the response.

Please add a notebook that shows a clear example of how to call a function on the input and output, not just pass already prediction ready data to a model object.

**Comment by TEChopra1000** [comment]
Thank you for the feedback @datagrayaaa. 

Have you seen the examples in these folders?
* https://github.com/aws/amazon-sagemaker-examples/tree/master/prep_data
* https://github.com/aws/amazon-sagemaker-examples/tree/master/ingest_data
* https://github.com/aws/amazon-sagemaker-examples/tree/master/ground_truth_labeling_jobs

I'll add a section to the README that highlights the prep_data and ingest_data folders.

**Comment by datagrayaaa** [comment]
@TEChopra1000 Thanks for suggested reading. After doing more research, what I was looking for and what should be highlighted is the diagram in this medium post: https://medium.com/weareservian/machine-learning-on-aws-sagemaker-53e1a5e218d9

The specific diagram I"m refering to is the one showing the flow of the prediction request to the input_fn, then the predict_fn, and finally the output_fn. I believe this material is available in the docs, but I have not seen it concisely illustrated or stated like this. If such an overview is already there, it would be helpful for newer users if it was highlighted. The direct link to the image I'm talking about is https://miro.medium.com/max/1000/1*e3zlZHLMya3lBVCuS5HdeQ.jpeg.

I'm not sure whether the article author made the diagram themselves, in which case maybe they can be contacted and asked if it can be used, or if the diagram is already somewhere in the sagemaker docs and examples. If it's already there, the structure shown in that diagram is the type of overview and guide that should be called out. It concisely shows how the data flows and how pre and post processing can be done with the input_fn and the similar functions.

**Comment by hsl89** [comment]
Hi @datagrayaaa , do any notebooks here https://github.com/aws/amazon-sagemaker-examples/tree/master/sagemaker_processing look like what you are looking for?

**Comment by hsl89** [comment]
close for lack of activity. pls reopen if you have new input
