### ISSUE TITLE
No module named 'misc'

### ISSUE THREAD

**Issue by ghost** [aws/amazon-sagemaker-examples#1944]
Have you tried `sys.path.append("/root/amazon-sagemaker-examples/reinforcement_learning/rl_cartpole_batch_coach/common")`?  If you are using SageMaker Studio, the path can be different as it's mounted on EFS (see https://github.com/awslabs/amazon-sagemaker-examples/issues/955).

_Originally posted by @annaluo676 in https://github.com/aws/amazon-sagemaker-examples/issues/746#issuecomment-567633403_

I am facing the error though I appended the path in to my jupyter notebook instances.
what possibly could be the reason

**Comment by seanpmorgan** [comment]
Looks like the user had been deleted and I'm unsure of what the question was. Closing.
