### ISSUE TITLE
Not able to create Labeling job

### ISSUE THREAD

**Issue by Suri12990** [aws/amazon-sagemaker-examples#1945]
Hey @TEChopra1000 
thank you for the quick response. I made all necessary changes, but labeling job is not created, it has been showing in-progress for the last two days. I thought it take some time, but it is not created yet. 

Here is the output of the labeling job:
`{'LabelingJobStatus': 'InProgress', 'LabelCounters': {'TotalLabeled': 0, 'HumanLabeled': 0, 'MachineLabeled': 0, 'FailedNonRetryableError': 0, 'Unlabeled': 0}, 'CreationTime': datetime.datetime(2021, 1, 22, 13, 16, 57, 501000, tzinfo=tzlocal()), 'LastModifiedTime': datetime.datetime(2021, 1, 22, 13, 16, 58, 754000, tzinfo=tzlocal()), 'JobReferenceCode': '507354440914YHSw1jUyO0XYOgL2', 'LabelingJobName': 'point-label-1', 'LabelingJobArn': 'arn:aws:sagemaker:eu-central-1:507354440914:labeling-job/point-label-1', 'LabelAttributeName': 'point-label-1', 'InputConfig': {'DataSource': {'S3DataSource': {'ManifestS3Uri': 's3://point-cloud-data-1/artifacts/gt-point-cloud-demos/manifests/SingleFrame-manifest.json'}}, 'DataAttributes': {'ContentClassifiers': ['FreeOfPersonallyIdentifiableInformation', 'FreeOfAdultContent']}}, 'OutputConfig': {'S3OutputPath': 's3://point-cloud-data-1/examples/output/', 'KmsKeyId': ''}, 'RoleArn': 'arn:aws:iam::507354440914:role/service-role/AmazonSageMaker-ExecutionRole-20210122T130644', 'LabelCategoryConfigS3Uri': 's3://point-cloud-data-1/artifacts/gt-point-cloud-demos/label-category-config/label-category.json', 'StoppingConditions': {'MaxPercentageOfInputDatasetLabeled': 100}, 'HumanTaskConfig': {'WorkteamArn': 'arn:aws:sagemaker:eu-central-1:507354440914:workteam/private-crowd/daimer', 'UiConfig': {'HumanTaskUiArn': 'arn:aws:sagemaker:eu-central-1:394669845002:human-task-ui/PointCloudObjectDetection'}, 'PreHumanTaskLambdaArn': 'arn:aws:lambda:eu-central-1:203001061592:function:PRE-3DPointCloudObjectDetection', 'TaskKeywords': ['lidar', 'pointcloud'], 'TaskTitle': 'Add a Task Title Here - This is Displayed to Workers', 'TaskDescription': 'add a task description here', 'NumberOfHumanWorkersPerDataObject': 1, 'TaskTimeLimitInSeconds': 3600, 'TaskAvailabilityLifetimeInSeconds': 18000, 'MaxConcurrentTaskCount': 200, 'AnnotationConsolidationConfig': {'AnnotationConsolidationLambdaArn': 'arn:aws:lambda:eu-central-1:203001061592:function:ACS-3DPointCloudObjectDetection'}}, 'ResponseMetadata': {'RequestId': 'e1d35bf3-29ad-4a09-89aa-1e2fa3912cb1', 'HTTPStatusCode': 200, 'HTTPHeaders': {'x-amzn-requestid': 'e1d35bf3-29ad-4a09-89aa-1e2fa3912cb1', 'content-type': 'application/x-amz-json-1.1', 'content-length': '1848', 'date': 'Fri, 22 Jan 2021 13:16:59 GMT'}, 'RetryAttempts': 0}}
`

It is not showing any error this time, I successfully ran the script and also got the labeling job name.  
![aws_error](https://user-images.githubusercontent.com/53983084/105521375-17fdc680-5cdc-11eb-8bce-aee1ad047ecf.png)

Thanks in advance
_Originally posted by @Suri12990 in https://github.com/aws/amazon-sagemaker-examples/issues/1936#issuecomment-765556229_

**Comment by TEChopra1000** [comment]
@Suri12990  It looks to me like the labeling job has been created and is running but the data object has not been labeled yet. If you look at the labeling job statuses, InProgress means the labeling job is in progress: https://docs.aws.amazon.com/sagemaker/latest/APIReference/API_DescribeLabelingJob.html#sagemaker-DescribeLabelingJob-response-LabelingJobStatus 

You can see an example in this video - I click "Create" to create a labeling job, and it shows up as "InProgress": https://youtu.be/_FPI6KjDlCI?t=439. I am then able to go into the worker portal, and work on the task that was created. 

If you are not already a worker on your private work team, you can add yourself and then go into the worker portal and check to see if the task is live. Have you tried this?

**Comment by Suri12990** [comment]
Sorry, I forgot to close it, I got it
