### ISSUE TITLE
scikit_bring_your_own example is not working

### ISSUE THREAD

**Issue by tabdunabi** [aws/amazon-sagemaker-examples#1953]
The example [scikit_bring_your_own](https://github.com/aws/amazon-sagemaker-examples/tree/master/advanced_functionality/scikit_bring_your_own) needs to be updated.
When trying to build the image, the following command in the Dockerfile fails 
```
RUN wget https://bootstrap.pypa.io/get-pip.py && python get-pip.py && \
    pip install numpy==1.16.2 scipy==1.2.1 scikit-learn==0.20.2 pandas flask gevent gunicorn && \
        (cd /usr/local/lib/python2.7/dist-packages/scipy/.libs; rm *; ln ../../numpy/.libs/* .) && \
        rm -rf /root/.cache
```
with the error message:
```
Traceback (most recent call last):
  File "get-pip.py", line 24226, in <module>
    main()
  File "get-pip.py", line 199, in main
    bootstrap(tmpdir=tmpdir)
  File "get-pip.py", line 82, in bootstrap
    from pip._internal.cli.main import main as pip_entry_point
  File "/tmp/tmp2aZyDl/pip.zip/pip/_internal/cli/main.py", line 60
    sys.stderr.write(f"ERROR: {exc}")
```
**Note:** I've fixed the issue by simply changing `wget https://bootstrap.pypa.io/get-pip.py` to `wget https://bootstrap.pypa.io/2.7/get-pip.py`.
However, it would be good if the example is updated to Python version 3.x

**Comment by seanpmorgan** [comment]
Not quite fixed. Will submit follow up PR
