### ISSUE TITLE
What does subprocess.call(['tail', '-f', '/dev/null']) in docker entrypoint do?

### ISSUE THREAD

**Issue by eugeneyan** [aws/amazon-sagemaker-examples#1985]
I'm trying to understand this sample docker entrypoint [here](https://github.com/aws/amazon-sagemaker-examples/blob/master/advanced_functionality/multi_model_bring_your_own/container/dockerd-entrypoint.py) (reproduced below).

```
import subprocess
import sys
import shlex
import os
from retrying import retry
from subprocess import CalledProcessError
from sagemaker_inference import model_server

def _retry_if_error(exception):
    return isinstance(exception, CalledProcessError or OSError)

@retry(stop_max_delay=1000 * 50,
       retry_on_exception=_retry_if_error)
def _start_mms():
    # by default the number of workers per model is 1, but we can configure it through the
    # environment variable below if desired.
    # os.environ['SAGEMAKER_MODEL_SERVER_WORKERS'] = '2'
    model_server.start_model_server(handler_service='/home/model-server/model_handler.py:handle')

def main():
    if sys.argv[1] == 'serve':
        _start_mms()
    else:
        subprocess.check_call(shlex.split(' '.join(sys.argv[1:])))

    # prevent docker exit
    subprocess.call(['tail', '-f', '/dev/null'])
    
main()
```

AFAIK, `main()` will start the model server. After the model server is started, will it shut down? Is that why we need `subprocess.call(['tail', '-f', '/dev/null'])` on line 27 to keep the model server up?

However, I've spun up multiple endpoints without `subprocess.call(['tail', '-f', '/dev/null'])` and the endpoints seem to work fine. Thus, I'm uncertain on what purpose `subprocess.call(['tail', '-f', '/dev/null'])` serves.

Any clarification would be greatly appreciated!

**Comment by IvyBazan** [comment]
From the original notebook writer:
"The purpose of that line is to prevent docker from exiting after starting the server."

**Comment by seanpmorgan** [comment]
Closing. Please let us know if there is any more information you're looking for.
