### ISSUE TITLE
Compiling a simple keras model using Neo

### ISSUE THREAD

**Issue by anubhav1** [aws/amazon-sagemaker-examples#1993]
Sorry for creating issue but I couldnt find answers anywhere.
Is it possible to  compile only the Keras Image Classification Model using Neo (according to this [link])(https://aws.amazon.com/releasenotes/sagemaker-neo-supported-frameworks-and-operators/)? 

I tried to compile my simple Keras model created for regression problem:
```
import pandas as pd
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import *

model = Sequential()
model.add(Dense(50, input_dim=9, activation='relu'))
model.add(Dense(100, activation='relu'))
model.add(Dense(50, activation='relu'))
model.add(Dense(1, activation='linear'))
model.compile(loss='mean_squared_error', optimizer='adam')

```
but getting error:
`ClientError: InputConfiguration: Unable to load provided Keras model. Error: 'sample_weight_mode'`

**Comment by hsl89** [comment]
Hello @anubhav1, please post the question here https://stackoverflow.com/questions/tagged/amazon-sagemaker
