### ISSUE TITLE
ValueError: Number of features of the model must match the input. Model n_features is 4 and input n_features is 3 

### ISSUE THREAD

**Issue by andrescmarin** [aws/amazon-sagemaker-examples#2005]
https://github.com/awslabs/amazon-sagemaker-examples/blob/41b36d9c0a7ff4e0f416d048185984e25e1941ae/advanced_functionality/scikit_bring_your_own/scikit_bring_your_own.ipynb#L505

`---------------------------------------------------------------------------
ModelError Traceback (most recent call last)
in
----> 1 print(predictor.predict(test_data.values).decode('utf-8'))

~/anaconda3/envs/python3/lib/python3.6/site-packages/sagemaker/predictor.py in predict(self, data, initial_args, target_model, target_variant)
111
112 request_args = self._create_request_args(data, initial_args, target_model, target_variant)
--> 113 response = self.sagemaker_session.sagemaker_runtime_client.invoke_endpoint(**request_args)
114 return self._handle_response(response)
115

~/anaconda3/envs/python3/lib/python3.6/site-packages/botocore/client.py in _api_call(self, *args, **kwargs)
314 "%s() only accepts keyword arguments." % py_operation_name)
315 # The "self" in this scope is referring to the BaseClient.
--> 316 return self._make_api_call(operation_name, kwargs)
317
318 _api_call.name = str(py_operation_name)

~/anaconda3/envs/python3/lib/python3.6/site-packages/botocore/client.py in _make_api_call(self, operation_name, api_params)
633 error_code = parsed_response.get("Error", {}).get("Code")
634 error_class = self.exceptions.from_code(error_code)
--> 635 raise error_class(parsed_response, operation_name)
636 else:
637 return parsed_response

ModelError: An error occurred (ModelError) when calling the InvokeEndpoint operation: Received server error (500) from model with message "
<title>500 Internal Server Error</title>
Internal Server Error

The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
". See https://us-east-1.console.aws.amazon.com/cloudwatch/home?region=us-east-1#logEventViewer:group=/aws/sagemaker/Endpoints/sagemaker-decision-trees-2020-07-24-20-20-13-487 in account 111652037296 for more information.`****

The error occurs in sagemaker studio notebook with python 3 datascience kernel

**Comment by seanpmorgan** [comment]
Hi @andrescmarin thanks for reporting. We can't see your cloud watch logs, would you be able to copy the num_features stack trace / error so I can take a look

**Comment by andrescmarin** [comment]
Greetings, the error in Cloudwatch "Model n_features is 4 and input n_features is 3" it is solved now. The problem is that when the previous cell trims the first column with the label and then internally the predictor.py that goes inside the container drops again the first column pass in the inference, ending the novel prediction with 3 variables (losing one of the predictor variables)
