### ISSUE TITLE
SMDataParallel examples are difficult to run

### ISSUE THREAD

**Issue by iprivit** [aws/amazon-sagemaker-examples#2010]
https://github.com/aws/amazon-sagemaker-examples/blob/master/training/distributed_training/tensorflow/data_parallel/bert/tensorflow2_smdataparallel_bert_demo.ipynb

The two SMDataParallel examples both include instructions:

Stage dataset in Amazon S3. Original dataset for BERT pretraining consists of text passages from BooksCorpus (800M words) (Zhu et al. 2015) and English Wikipedia (2,500M words). Please follow original guidelines by NVidia to prepare training data in hdf5 format - https://github.com/NVIDIA/DeepLearningExamples/blob/master/PyTorch/LanguageModeling/BERT/README.md#getting-the-data

The problem with this is the instructions in the linked Nvidia example expect the user is doing this within a NGC container as there are hardcoded paths and environment variables in all of the scripts used for downloading data. This makes simply following the data download instructions rather tedious since a large number of statements need to be edited for it to run in either SageMaker Studio or a classic SageMaker Notebook. 

For example in bertPrep.py it defines working_dir, a variable used throughout the script, as 
os.environ['BERT_PREP_WORKING_DIR']

This environment variable doesn't exist in SageMaker, making any attempt to run this script immediately fail.

Simplifying the data download process will make it substantially easier to run this notebook.

**Comment by hsl89** [comment]
Any insight @piyushghai ?
