### ISSUE TITLE
Sagemaker Neo compiled model is giving  slightly different results than the actual keras model

### ISSUE THREAD

**Issue by anubhav1** [aws/amazon-sagemaker-examples#2022]
**Describe the bug**
Sagemaker Neo compiled model is giving  slighthly different results than the actual keras model.

**To Reproduce**
I created a simple Keras regression model and trained it and then saved it in h5 format.
Then in order to deploy on greengrass, i compiled this model using neo and then deployed it and inferenced using lamda function. Final prediction result is slightly different than the prediction of actual keras model.

**Model:**
```
import pandas as pd
from keras.models import Sequential
from keras.layers import *

model = Sequential()
model.add(Dense(50, input_dim=9, activation='relu'))
model.add(Dense(100, activation='relu'))
model.add(Dense(50, activation='relu'))
model.add(Dense(1, activation='linear'))
model.compile(loss='mean_squared_error', optimizer='adam')
```

Is it an expected behaviour?

**Comment by hsl89** [comment]
hi @anubhav1 , it's unlikely to be the expected behavior. Try here  https://stackoverflow.com/questions/tagged/amazon-sagemaker
