### ISSUE TITLE
Sagemaker model parallelism API example: smp_bert_tutorial.ipynb training fails

### ISSUE THREAD

**Issue by akinolawilson** [aws/amazon-sagemaker-examples#2023]
[You can find the relevant notebook here](https://github.com/aws/amazon-sagemaker-examples/blob/master/training/distributed_training/pytorch/model_parallel/bert/smp_bert_tutorial.ipynb)

**Bug description**
When I attempt to run the Notebook using the test dataset: _'datasets/binary/bert/hdf5_lower_case_1_seq_len_128_max_pred_20_masked_lm_prob_0.15_random_seed_12345_dupe_factor_5/wikicorpus_en_abstract'_
as given in the notebook, I receive an error message regarding: 
`PMIX_MCA_mca_base_component_show_load_errors': '1'` 
[Please see the full output here](https://drive.google.com/file/d/1Xy8FiWMB2nIL5p5s9LvHM0o-uPSgKNbd/view?usp=sharing)

**To Reproduce**
Run the notebook book supported by an _ml.p3.8xlarge_ instance. Change the variables:
```
instance_type="ml.p3.8xlarge"
volume_size=500
instance_count=1
```
In the snippet of the notebook titled: **Instantiate Pytorch Estimator with SMP enabled** and run the entire notebook.

**Comment by hsl89** [comment]
hello @akinolawilson , looking at your traceback. The error is 
```
f"The number of node-local MPI processes {self.lib.smp_local_size()}"
[1,2]<stderr>:RuntimeError: The number of node-local MPI processes 8cannot be larger than the device count 4
```
This means you are trying to run 8 process on a device with 4 gpu. Try something like "ml.p3.16xlarge" or set "processes_per_host" to 4.
