### ISSUE TITLE
Not enough annotation packed in the list file or the RecordIO file

### ISSUE THREAD

**Issue by isakkirajan** [aws/amazon-sagemaker-examples#2027]
Please have a look at the sample .lst file

`0	2	5	1.0	42.4	21.756487025948104	54.133333333333326	39.12175648702595	1.0	49.46666666666667	38.72255489021956	60.266666666666666	58.08383233532935	/object-detection/data/train/image01.jpg
1	2	5	0.0	47.733333333333334	13.572854291417165	59.06666666666667	34.73053892215568	0.0	56	31.53692614770459	66.13333333333333	53.49301397205589	/object-detection/data/train/image02.jpg
2	2	5	0.0	41.25205958936868	46.60157896881577	48.58539292270201	60.972836453845716	0.0	47.733333333333334	30.93812375249501	57.06666666666667	46.30738522954092	/object-detection/data/train/img03.jpg
`

Error:
UnexpectedStatusException: Error for Training job object-detection-2021-02-23-01-16-07-172: Failed. Reason: ClientError: Not enough annotation packed in the list file or the RecordIO file. Each object requires at least five numbers [label_id, xmin, ymin, ymax] for annotation.

**Comment by hsl89** [comment]
please follow the template
