### ISSUE TITLE
Validation failed while creating model package in aws sagemaker

### ISSUE THREAD

**Issue by ArturasDruteika** [aws/amazon-sagemaker-examples#2028]
I get this error: "Client error: ClientError: See job logs for more information". I use default nginx gunicorn. I use code from: https://github.com/aws/amazon-sagemaker-examples/tree/master/aws_marketplace/creating_marketplace_products/container.

| timestamp | message
| 1614001176448 | Starting the inference server with 1 workers.
| 1614001176448 | 2021/02/22 13:39:31 https://forums.aws.amazon.com/ 11#11: *1 connect() to unix:/tmp/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 169.254.255.130, server: , request: "GET /ping HTTP/1.1", upstream: "http://unix:/tmp/gunicorn.sock:/ping", host: "169.254.255.131:8080" |
| 1614001176448 | 169.254.255.130 - - 22/Feb/2021:13:39:31 +0000 "GET /ping HTTP/1.1" 502 173 "-" "Go-http-client/1.1"
| 1614001176448 | 2021/02/22 13:39:31 https://forums.aws.amazon.com/ 11#11: *3 connect() to unix:/tmp/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 169.254.255.130, server: , request: "GET /ping HTTP/1.1", upstream: "http://unix:/tmp/gunicorn.sock:/ping", host: "169.254.255.131:8080" |
| 1614001176448 | 169.254.255.130 - - 22/Feb/2021:13:39:31 +0000 "GET /ping HTTP/1.1" 502 173 "-" "Go-http-client/1.1"
| 1614001176448 | 2021/02/22 13:39:32 https://forums.aws.amazon.com/ 11#11: *5 connect() to unix:/tmp/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 169.254.255.130, server: , request: "GET /ping HTTP/1.1", upstream: "http://unix:/tmp/gunicorn.sock:/ping", host: "169.254.255.131:8080" |
| 1614001176448 | 169.254.255.130 - - 22/Feb/2021:13:39:32 +0000 "GET /ping HTTP/1.1" 502 173 "-" "Go-http-client/1.1"
| 1614001176448 | 2021/02/22 13:39:32 https://forums.aws.amazon.com/ 11#11: *7 connect() to unix:/tmp/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 169.254.255.130, server: , request: "GET /ping HTTP/1.1", upstream: "http://unix:/tmp/gunicorn.sock:/ping", host: "169.254.255.131:8080" |
| 1614001176448 | 169.254.255.130 - - 22/Feb/2021:13:39:32 +0000 "GET /ping HTTP/1.1" 502 173 "-" "Go-http-client/1.1"
| 1614001176448 | 2021/02/22 13:39:32 https://forums.aws.amazon.com/ 11#11: *9 connect() to unix:/tmp/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 169.254.255.130, server: , request: "GET /ping HTTP/1.1", upstream: "http://unix:/tmp/gunicorn.sock:/ping", host: "169.254.255.131:8080" |
| 1614001176448 | 169.254.255.130 - - 22/Feb/2021:13:39:32 +0000 "GET /ping HTTP/1.1" 502 173 "-" "Go-http-client/1.1"
| 1614001176448 | https://forums.aws.amazon.com/ https://forums.aws.amazon.com/ https://forums.aws.amazon.com/ Starting gunicorn 20.0.4
| 1614001176448 | https://forums.aws.amazon.com/ https://forums.aws.amazon.com/ https://forums.aws.amazon.com/ Listening at: unix:/tmp/gunicorn.sock (10)
| 1614001176448 | https://forums.aws.amazon.com/ https://forums.aws.amazon.com/ https://forums.aws.amazon.com/ Using worker: gevent
| 1614001176448 | https://forums.aws.amazon.com/ https://forums.aws.amazon.com/ https://forums.aws.amazon.com/ Booting worker with pid: 13
| 1614001176448 | 2021-02-22 13:39:32.710056: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcudart.so.10.1'; dlerror: libcudart.so.10.1: cannot open shared object file: No such file or directory |
| 1614001176449 | 2021-02-22 13:39:32.710090: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine. |
| 1614001176449 | 2021-02-22 13:39:33.744540: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory |
| 1614001176449 | 2021-02-22 13:39:33.744578: W tensorflow/stream_executor/cuda/cuda_driver.cc:312] failed call to cuInit: UNKNOWN ERROR (303)
| 1614001176449 | 2021-02-22 13:39:33.744600: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (5bb5d9cf82c6): /proc/driver/nvidia/version does not exist |
| 1614001176449 | 2021-02-22 13:39:33.747156: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN)to use the following CPU instructions in performance-critical operations: AVX2 AVX512F FMA |
| 1614001176449 | To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
| 1614001176449 | 2021-02-22 13:39:33.770093: I tensorflow/core/platform/profile_utils/cpu_utils.cc:104] CPU Frequency: 3000000000 Hz
| 1614001176449 | 2021-02-22 13:39:33.770554: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x5626d699fd10 initialized for platform Host (this does not guarantee that XLA will be used). Devices: |
| 1614001176449 | 2021-02-22 13:39:33.770587: I tensorflow/compiler/xla/service/service.cc:176] StreamExecutor device (0): Host, Default Version
| 1614001176449 | 169.254.255.130 - - 22/Feb/2021:13:39:33 +0000 "GET /ping HTTP/1.1" 200 1 "-" "Go-http-client/1.1"
| 1614001176449 | 169.254.255.130 - - 22/Feb/2021:13:39:33 +0000 "GET /execution-parameters HTTP/1.1" 404 2 "-" "Go-http-client/1.1"

As you can see from logs ping health check request are being sent before gunicorn starts

What could cause this problem and how to solve it?

**Comment by hsl89** [comment]
how to reproduce the error?

**Comment by danielcavalli** [comment]
Can we reopen this?
Got the same error while trying to setup an Endpoint with internet access.

**Comment by gthmml** [comment]
hi, could you re-open this incident?

I have tried will larger instances, but unable to get through.
also try adding gunicorn and nginx to requirements.txt as mentioned in other blogs.

Error Message:
2022/02/20 13:18:25 [crit] 22#22: *213 connect() to unix:/tmp/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 10.32.0.2, server: , request: "GET /ping HTTP/1.1", upstream: "[http://unix:/tmp/gunicorn.sock:/ping](http://unix/tmp/gunicorn.sock:/ping)", host: "model.aws.local:8080"
