### ISSUE TITLE
SM Data Parallel Notebook Error

### ISSUE THREAD

**Issue by ksindwan** [aws/amazon-sagemaker-examples#2029]
**Link to the notebook**
https://github.com/aws/amazon-sagemaker-examples/blob/master/training/distributed_training/tensorflow/data_parallel/mnist/tensorflow2_smdataparallel_mnist_demo.ipynb
**Describe the bug**
`[1,9]<stdout>:    AttributeError: module 'smdistributed.dataparallel.tensorflow' has no attribute 'get_world_size'
`
**To Reproduce**
While executing the cell estimator.fit() in the notebook.

**Comment by mchoi8739** [comment]
The fix is WIP as sev 2 (P44569763). Closing this issue since this is not a direct issue originated from the notebook.
