### ISSUE TITLE
[Deployed xgboost model fail with an error when calling prediction function]

### ISSUE THREAD

**Issue by dsow86** [aws/amazon-sagemaker-examples#2030]
Hello every one, i am trying to find out what cause this issus the hall day but i am getting the same thing.
i use used amazaon sagemaker (sagemaker: 2.24.1) to build and deploy model on the classical "orders_with_predicted_value.csv" dataset. Everything works find with the training and the model well deployed. But when i call de prediction method on the test data this bring the following error:
"
![sagemaker_issue](https://user-images.githubusercontent.com/64834120/108871492-80043d00-75f9-11eb-9638-7c9bb665646d.JPG)
AttributeError: ("'NoneType' object has no attribute 'Accept'", 'occurred at index 0')"
![sagemaker_issue](https://user-images.githubusercontent.com/64834120/108871556-91e5e000-75f9-11eb-8172-f252e3442435.JPG)
 I have also to note that the same issue happen in the aws plateform with an aws notebook instance, and also locally using boto3 and installing sagemaker on python. 
A second remark is that this worked for me in the past on a notebook instance without any issue.
Thanks for your help

**Comment by hsl89** [comment]
please open the issue with template
