### ISSUE TITLE
Error when using xgboost in framework mode to predict

### ISSUE THREAD

**Issue by Zhengro** [aws/amazon-sagemaker-examples#2031]
**Link to the notebook**
https://github.com/aws/amazon-sagemaker-examples/blob/master/aws_sagemaker_studio/getting_started/xgboost_customer_churn_studio.ipynb

**Describe the bug**
When hosting the model, the `xgb_predictor` uses the model in algorithm mode, i.e., `xgb`. I wanted to use the model in framework mode, i.e., `framework_xgb`. I deployed it but `xgb_predictor.predict` didn't work any more.

Errors I got:
An error occurred (ModelError) when calling the InvokeEndpoint operation: Received server error (500) from model with message " 500 Internal Server Error Internal Server Error The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

Log in CloudWatch:
sagemaker_containers._errors.ClientError: 'tuple' object has no attribute 'predict

Thanks in advance for your help!

**Comment by mchoi8739** [comment]
The end-to-end notebook series uses the XGBoost framework mode. Have a look at this notebook and see if it helps you resolve the issue: https://github.com/aws/amazon-sagemaker-examples/blob/f8feda292edba2edd41f408684deeb2db4aaca97/end_to_end/4-deploy-run-inference-e2e.ipynb

**Comment by mchoi8739** [comment]
Also it would be helpful if you can share your modified script for constructing the `framework_xgb` estimator, how you executed `framework_xgb.fit` and deployed it.

**Comment by Zhengro** [comment]
> Also it would be helpful if you can share your modified script for constructing the `framework_xgb` estimator, how you executed `framework_xgb.fit` and deployed it.

Thanks for your quick replies! Regarding the script for constructing the `framework_xgb` estimator, I didn't have a custom script but simply tested the given [script](https://github.com/aws/amazon-sagemaker-examples/blob/master/aws_sagemaker_studio/getting_started/xgboost_customer_churn.py) accompanying the [notebook](https://github.com/aws/amazon-sagemaker-examples/blob/master/aws_sagemaker_studio/getting_started/xgboost_customer_churn_studio.ipynb) I mentioned.

It turned out that the error came from the given script. Instead of `return booster, format` in `model_fn(model_dir)`, it should only return `booster`. Then everything works fine without modifying any parts of the notebook.
