### ISSUE TITLE
[Content Improvement]

### ISSUE THREAD

**Issue by rhettdesbutler** [aws/amazon-sagemaker-examples#2041]
https://github.com/aws/amazon-sagemaker-examples/blob/master/sagemaker_model_monitor/model_quality/model_quality_churn_sdk.ipynb

Problem:

Regarding the gathering of `ground-truth` labels and inference results from a model in production in order to create the `monitoring schedule` as shown below which makes use of the `ground_truth_input` parameter.

```
.create_monitoring_schedule(
    monitor_schedule_name=churn_monitor_schedule_name,
    endpoint_input=endpointInput,
    output_s3_uri = baseline_results_uri,
    problem_type='BinaryClassification',
    ground_truth_input=ground_truth_upload_path,
    constraints=baseline_job.suggested_constraints(),
    schedule_cron_expression=CronExpressionGenerator.hourly(), 
    enable_cloudwatch_metrics=True
)
```

When you query an endpoint and get back a prediction, you don't always know, in the case of the example, if the person indeed churned or not. You are making a prediction and getting back a "score" and "predicted_label". Only after the person churned would you be able to provide the `ground-truth` label to then evaluate if your prediction was indeed correct. 

In the example this is just somehow "faked" but no clear explanation on why and how.
I do not fully understand then WHERE or HOW `ground-truth` labels would be collected from in production. It can be done using test, train or validation datasets because you already know the outcome, that is the `ground-truth`. But how can the model monitor an inference being made on `churning` in this example, if we dont know yet if the person indeed churned or not. That `ground-truth` does not yet exist for THAT particular person (only the ones from training, testing, validation).

I would suggest:
Make it clear in the notebook where and how you would retrieve the `ground-truth` labels in order to then provide the input for  the `.create_monitoring_schedule()` request. As well as where and how to retrieve `ground-truth` labels for a prediction being made (live data in production) and not yet having a "confirmed" churn or not data.

**Comment by hsl89** [comment]
Hi @rhettdesbutler thanks for the suggestion. It makes sense, you would never get ground-truth for a "non-churn" customer for real use case. How about we adjust the notebook to predict whether a customer churns in 1 year. Then, there will be ground truth for both positive and negative.
