### ISSUE TITLE
Different Errors deploying MXNet BYOM into Elastic Inference Instance

### ISSUE THREAD

**Issue by monitarb** [aws/amazon-sagemaker-examples#2060]
I have a model already trained in MXNet.  I've deployed it and used it as a Sagemaker endpoint using a p3.2xlarge instance which was toooooo expensive.  Now I'm trying to deploy using Elastic Inference.
I'm following this documentation: https://sagemaker.readthedocs.io/en/stable/frameworks/mxnet/using_mxnet.html?highlight=elastic#elastic-inference

Sometimes, when I deploy the model I get this error after 15min:
_"Error hosting endpoint receti-model-20210304-030842: Failed. Reason:  The primary container,accelerator for production variant AllTraffic did not pass the ping health check. Please check CloudWatch logs for this endpoint..."_

Other times, the endpoint deploys correctly in around 8min, aparently, but whenever I try to invoke it I get this other error after 20min:
_"Read timeout on endpoint URL: "https://runtime.sagemaker.us-east-1.amazonaws.com/endpoints/my_endpoint/invocations""_

It seems like the behaviour is different everytime, (but never successful).  

This is my create/deploy sentence:
```
print('Creating Endpoint: ', endpoint_name)
model = MXNetModel(
    entry_point='entrypoint.py',
    model_data=model_data_s3_uri,
    framework_version='1.4.1', 
    py_version='py3',
    role=sagemaker.get_execution_role()
)

print('Deploy Endpoint: ', endpoint_name)
predictor = model.deploy(endpoint_name=endpoint_name, 
                         initial_instance_count=1, 
                         instance_type='ml.m4.2xlarge',
                         accelerator_type='ml.eia2.medium')

```
Where model_data_s3_uri is the S3 location of the tar.gz containing my params file.  I've run this in Sagemaker Studio with an mnxnet and an amazonei kernell with the same unsuccessful result.
This is the loading function inside my entrypoint.py file:
```
def model_fn(model_dir):
    ctx = mx.eia()
    model = gcv.model_zoo.get_model('ssd_300_vgg16_atrous_custom', classes=CLASSES, ctx=ctx
                              pretrained=False, pretrained_base=False)
    model.load_parameters('ssd_512_vgg16_atrous_voc_best.params', ctx, ignore_extra=True)
    return model, ctx
```
Can someone please help me understand this behaviour or point me what I'm doing wrong, or is it really a bug because of the different behaviours?

**Comment by hsl89** [comment]
@monitarb , you used 'ssd_300_vgg16_atrous_custom' model. It is a probably very big. my guess is your elastic inference device is not big enough to host this model. Can you figure out the size of your model?
