### ISSUE TITLE
[Bug Report] - DeepAR-Electricity.ipynb

### ISSUE THREAD

**Issue by marklaszlo9** [aws/amazon-sagemaker-examples#2065]
**Link to the notebook**
https://github.com/aws/amazon-sagemaker-examples/blob/master/introduction_to_amazon_algorithms/deepar_electricity/DeepAR-Electricity.ipynb

**Describe the bug**
When running this cell:
num_test_windows = 4

test_data = [
    {
        "start": str(start_dataset),
        "target": ts[start_dataset:end_training + k * prediction_length].tolist()
    }
    for k in range(1, num_test_windows + 1) 
    for ts in timeseries
]

I got the following error:
TypeError: Addition/subtraction of integers and integer-arrays with Timestamp is no longer supported.  Instead of adding/subtracting `n`, use `n * obj.freq`

**To Reproduce**
I've tried in Sagemaker Studio with Data Science kernel and reguler notebook instance with Conda Python3 kernel. Same result everywhere.

**Comment by seanpmorgan** [comment]
Hi @marklaszlo9 could you make sure you're running the updated master branch? I believe these issues were fixed a few months ago and I'm seeing a different code cell than you've pasted:
```

num_test_windows = 4

test_data = [
    {
        "start": str(start_dataset),
        "target": ts[start_dataset:end_training + timedelta(days=k * prediction_length)].tolist()
    }
    for k in range(1, num_test_windows + 1) 
    for ts in timeseries
]
print(len(test_data))
```

**Comment by marklaszlo9** [comment]
Hi @seanpmorgan you are right. I did pull the master, but for some reason it did not update. My bad

**Comment by seanpmorgan** [comment]
> Hi @seanpmorgan you are right. I did pull the master, but for some reason it did not update. My bad

No worries, happy to have it sorted out!
