### ISSUE TITLE
Notebook sagemaker-countycensusclustering: S3 bucket aws-ml-blog-sagemaker-census-segmentation access

### ISSUE THREAD

**Issue by gradymorgan** [aws/amazon-sagemaker-examples#2116]
Hi Team,
The bucket "aws-ml-blog-sagemaker-census-segmentation" used by the notebook sagemaker-countycensusclustering is no longer public and hence get access denied even if the sagemaker role has access to all buckets.

Possible solutions to either move the dataset to AWS public datasets or change the bucket policy to allow access to all accounts and all users

**Comment by hsl89** [comment]
@gradymorgan can you explain more? which notebook in this repo are you talking about

**Comment by johnsmi-yle** [comment]
Probabmly this one, I got the same error "ClientError: An error occurred (AccessDenied) when calling the ListObjects operation: Access Denied" while running `obj_list=s3_client.list_objects(Bucket=data_bucket_name)` at :  https://github.com/aws/amazon-sagemaker-examples/blob/master/introduction_to_applying_machine_learning/US-census_population_segmentation_PCA_Kmeans/sagemaker-countycensusclustering.ipynb

**Comment by hsl89** [comment]
Can you do it this 
```
aws s3 ls s3://aws-ml-blog-sagemaker-census-segmentation
```
from the command line?
