### ISSUE TITLE
[Bug Report] Metrics File not Generated after Melodic Update

### ISSUE THREAD

**Issue by ShaylinChetty** [aws/amazon-sagemaker-examples#2219]
**Link to the notebook**
https://github.com/aws/amazon-sagemaker-examples/blob/master/reinforcement_learning/rl_deepracer_robomaker_coach_gazebo/deepracer_rl.ipynb

**Describe the bug**
The simulation job does not generate the metrics.json file.

The simulation job completes successfully, tried with both 10 minute and 60 minute jobs. No file is sent to the configured S3 bucket. The issue has appeared since the melodic migration.

**To Reproduce**
Running the notebook start to finish on Sagemaker.
Cell 28 fails with the following error.

FileNotFoundError: S3 object s3://sagemaker-us-east-1-010176289379/deepracer-notebook-sagemaker-210511-121640/training_metrics.json never appeared after 1200 seconds

**Comment by aaronmarkham** [comment]
@lingjiekong can you take a look at this?

**Comment by lingjiekong** [comment]
@ShaylinChetty Thanks for raising the issue up. I was trying to reproduce this failure on my side. Unfortunately I was not able to reproduce it.

First, could you please log into your s3 bucket at s3://sagemaker-us-east-1-010176289379/deepracer-notebook-sagemaker-210511-121640/training_metrics.json to check whether this folder or json file exist.

Second, If you are saying that simulation job completed successfully, you should be able to see blow logs in your RoboMaker cloudwatch log, if you search "s3" as filter keyword
`[s3] Successfully uploaded metrics to s3 bucket sagemaker-us-east-1-x with s3 key deepracer-notebook-sagemaker-x/training_metrics.json.`
Could you please share you RoboMaker log or help me confirm regarding whether this logs appears or not.

I am looking forwards to get a bit more details to help you trouble shoot your issue further.

**Comment by ShaylinChetty** [comment]
The training_metrics.json file does not exist.
