### ISSUE TITLE
[Bug Report] census-income.csv file for the eu-west-1 region

### ISSUE THREAD

**Issue by abedshantti** [aws/amazon-sagemaker-examples#2227]
**Link to the notebook**
https://github.com/aws/amazon-sagemaker-examples/blob/187e52fc3db844645b469cc35122ccbc188357a1/sagemaker_processing/feature_transformation_with_sagemaker_processing_dask/feature_transformation_with_sagemaker_processing_dask.ipynb

**Describe the bug**
I am not sure if the file "s3://sagemaker-sample-data-{}/processing/census/census-income.csv".format(region) exists for the eu-west-1 region? I have tried running the first two cells of the notebook and received:

`FileNotFoundError: [Errno 2] No such file or directory: 'census-income.csv'`

**To Reproduce**
```python
from time import gmtime, strftime
import sagemaker
import boto3
import pandas as pd

s3 = boto3.client("s3")
region = sagemaker_session.boto_region_name # eu-west-1 in my case
sagemaker_session = sagemaker.Session()
role = sagemaker.get_execution_role()

awsID = 00000000000
bucket_name = XXXXX
bucket = "production-individual-" + awsID + region + bucket_name
timestamp_prefix = strftime("%Y-%m-%d-%H-%M-%S", gmtime())

prefix = "sagemaker/dask-preprocess-demo"
input_prefix = prefix + "/input/raw/census"
input_preprocessed_prefix = prefix + "/input/preprocessed/census"
model_prefix = prefix + "/model"

input_data = "s3://sagemaker-sample-data-{}/processing/census/census-income.csv".format(region)
!aws s3 cp $input_data .

# Uploading the training data to S3
sagemaker_session.upload_data(path="census-income.csv", bucket=bucket, key_prefix=input_prefix)
```

I have initially tried with `bucket = sagemaker_session.default_bucket()` but that returned `ClientError: An error occurred (AccessDenied) when calling the CreateBucket operation: Access Denied`. So I am just setting the bucket in the same manner as I do for the rest of my projects.

**Comment by aaronmarkham** [comment]
Can you switch that use us-east-1 to fetch the data? (at least for now... we'll still need to get the data copied to your region)

**Comment by jkroll-aws** [comment]
I confirmed that the file exists in eu-west-1 and can be downloaded.

```
aws s3 ls sagemaker-sample-data-us-east-1/processing/census/census-income.csv
wget https://sagemaker-sample-data-eu-west-1.s3.amazonaws.com/processing/census/census-income.csv
```

I also created a SageMaker notebook instance in eu-west-1 and was able to run the notebook cells successfully to download the file.

Given that you also got an Access Denied error when trying to get and create the default bucket, I suspect that the IAM role you are using to run this notebook may not have sufficient S3 permissions, so it is failing to copy the file from S3, and then raising the error that the file does not exist locally to copy to your specified S3 bucket. Adding either `AmazonS3FullAccess` or `AmazonSageMakerFullAccess` managed policies may fix the issue, or you could write your own policy allowing at least `s3:GetObject` on `s3://sagemaker-sample-data-eu-west-1`.
