### ISSUE TITLE
deepar_chicago_traffic_violations.ipynb failed CI

### ISSUE THREAD

**Issue by hsl89** [aws/amazon-sagemaker-examples#2254]
Link to the notebook:
https://github.com/aws/amazon-sagemaker-examples/blob/master/introduction_to_applying_machine_learning/deepar_chicago_traffic_violations/deepar_chicago_traffic_violations.ipynb

Error:

---------------------------------------------------------------------------
Exception encountered at "In [6]":
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-6-73d091ffa7a6> in <module>
     39                             early_stopping_type='Auto')
     40 
---> 41 s3_input_train = sagemaker.s3_input(s3_data='s3://{}/{}/train/'.format(bucket, prefix),
     42                                     content_type='json')
     43 s3_input_test = sagemaker.s3_input(s3_data='s3://{}/{}/test/'.format(bucket, prefix),

AttributeError: module 'sagemaker' has no attribute 's3_input'

**Comment by atqy** [comment]
Doesn't exist anymore, code has been changed
