### ISSUE TITLE
object_detection_tutorial.ipynb failed CI

### ISSUE THREAD

**Issue by hsl89** [aws/amazon-sagemaker-examples#2332]
Link to the notebook:
https://github.com/aws/amazon-sagemaker-examples/blob/master/ground_truth_labeling_jobs/ground_truth_object_detection_tutorial/object_detection_tutorial.ipynb

Error:

---------------------------------------------------------------------------
Exception encountered at "In [2]":
---------------------------------------------------------------------------
ParamValidationError                      Traceback (most recent call last)
<ipython-input-2-6f0622ae9028> in <module>
      3 region = boto3.session.Session().region_name
      4 s3 = boto3.client('s3')
----> 5 bucket_region = s3.head_bucket(Bucket=BUCKET)['ResponseMetadata']['HTTPHeaders']['x-amz-bucket-region']
      6 assert bucket_region == region, "Your S3 bucket {} and this notebook need to be in the same region.".format(BUCKET)

/opt/conda/lib/python3.7/site-packages/botocore/clie

[...]

Invalid bucket name "<< YOUR S3 BUCKET NAME >>": Bucket name must match the regex "^[a-zA-Z0-9.\-_]{1,255}$" or be an ARN matching the regex "^arn:(aws).*:s3:[a-z\-0-9]+:[0-9]{12}:accesspoint[/:][a-zA-Z0-9\-]{1,63}$|^arn:(aws).*:s3-outposts:[a-z\-0-9]+:[0-9]{12}:outpost[/:][a-zA-Z0-9\-]{1,63}[/:]accesspoint[/:][a-zA-Z0-9\-]{1,63}$"

**Comment by atqy** [comment]
Given the context, it is best to leave the S3 bucket blank for now for the user to fill in their own input. Additionally, this notebook is on the skip list as it requires other manual inputs and will not be fully CI even if this issue is resolved. Closing this issue for now.
