### ISSUE TITLE
r_xgboost_batch_transform.ipynb failed CI

### ISSUE THREAD

**Issue by hsl89** [aws/amazon-sagemaker-examples#2336]
Link to the notebook:
https://github.com/aws/amazon-sagemaker-examples/blob/master/r_examples/r_batch_transform/r_xgboost_batch_transform.ipynb

Error:

---------------------------------------------------------------------------
Exception encountered at "In [1]":
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-1-75c5b43bf74d> in <module>
      1 # Turn warnings off globally
----> 2 options(warn=-1)

NameError: name 'options' is not defined

**Comment by atqy** [comment]
Not an issue anymore, it has been fixed.
