### ISSUE TITLE
iterative_model_pruning_resnet.ipynb failed CI

### ISSUE THREAD

**Issue by hsl89** [aws/amazon-sagemaker-examples#2348]
Link to the notebook:
https://github.com/aws/amazon-sagemaker-examples/blob/master/sagemaker-debugger/pytorch_iterative_model_pruning/iterative_model_pruning_resnet.ipynb

Error:

---------------------------------------------------------------------------
Exception encountered at "In [4]":
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-4-3740732b6f46> in <module>
----> 1 import torch
      2 from torchvision import models
      3 from torch import nn
      4 
      5 model = models.resnet18(pretrained=True)

ModuleNotFoundError: No module named 'torch'

**Comment by mchoi8739** [comment]
Used the correct kernel and fixed the issue along with the PR above.
