### ISSUE TITLE
sagemaker_edge_example.ipynb failed CI

### ISSUE THREAD

**Issue by hsl89** [aws/amazon-sagemaker-examples#2394]
Link to the notebook:
https://github.com/aws/amazon-sagemaker-examples/blob/master/sagemaker_edge_manager/sagemaker_edge_example/sagemaker_edge_example.ipynb

Error:

---------------------------------------------------------------------------
Exception encountered at "In [9]":
  File "<ipython-input-9-66c8e2c6e8cd>", line 1
    ec2_profile_name = <ec2_role_name>  # the name of the role created for EC2
                       ^
SyntaxError: invalid syntax

**Comment by atqy** [comment]
Closing this issue for now as I think more work is needed to make the notebooks fully functional on CI as:
(1) the notebooks make you manually pick between tensorpack_image and aws_samples_image (one solution may be to split one notebook into two notebooks that handles one image each but I think this needs further discussion) 
(2) there may be some information that the user may need to input manually (i.e. container names, security group names, etc - there may be a possibility we can automate this but it will need further investigation)
