### ISSUE TITLE
Image-classification-fulltraining-highlevel.ipynb failed CI

### ISSUE THREAD

**Issue by hsl89** [aws/amazon-sagemaker-examples#2408]
Link to the notebook:
https://github.com/aws/amazon-sagemaker-examples/blob/master/introduction_to_amazon_algorithms/imageclassification_caltech/Image-classification-fulltraining-highlevel.ipynb

Error:

---------------------------------------------------------------------------
Exception encountered at "In [9]":
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-9-6ebaea4d6017> in <module>
      1 optimized_ic = ic
----> 2 if ic.create_model().check_neo_region(boto3.Session().region_name) is False:
      3     print('Neo is not currently supported in', boto3.Session().region_name)
      4 else:
      5     output_path = '/'.join(ic.output_path.split('/')[:-1])

AttributeError: 'Model' object has no attribute 'check_neo_region'

**Comment by jkroll-aws** [comment]
This `check_neo_region()` function is deprecated and can be removed. Neo has launched in almost all regions.

**Comment by OneManArmy93** [comment]
hello did you find a fix for this? Thank you

**Comment by jkroll-aws** [comment]
@OneManArmy93 Working on a fix. Please see the linked PR. Still debugging the final prediction step.

**Comment by jkroll-aws** [comment]
@OneManArmy93 FYI this is fixed now.
