### ISSUE TITLE
mask-rcnn-inference.ipynb failed CI

### ISSUE THREAD

**Issue by hsl89** [aws/amazon-sagemaker-examples#2506]
Link to the notebook:
https://github.com/aws/amazon-sagemaker-examples/blob/master/advanced_functionality/distributed_tensorflow_mask_rcnn/mask-rcnn-inference.ipynb

Error:

---------------------------------------------------------------------------
Exception encountered at "In [4]":
  File "<ipython-input-4-2ee64160c1f9>", line 1
    tensorpack_image = # mask-rcnn-tensorpack-serving-sagemaker ECR URI
                                                                       ^
SyntaxError: invalid syntax

**Comment by atqy** [comment]
Closing this issue for now as I think more work is needed to make the notebooks fully functional on CI as:
(1) the notebooks make you manually pick between tensorpack_image and aws_samples_image (one solution may be to split one notebook into two notebooks that handles one image each but I think this needs further discussion)
(2) there may be some information that the user may need to input manually (i.e. container names, security group names, etc - there may be a possibility we can automate this but it will need further investigation)
