### ISSUE TITLE
mask-rcnn-experiment-trials.ipynb failed CI

### ISSUE THREAD

**Issue by hsl89** [aws/amazon-sagemaker-examples#2507]
Link to the notebook:
https://github.com/aws/amazon-sagemaker-examples/blob/master/advanced_functionality/distributed_tensorflow_mask_rcnn/mask-rcnn-experiment-trials.ipynb

Error:

---------------------------------------------------------------------------
Exception encountered at "In [1]":
  File "<ipython-input-1-1b037ff64807>", line 1
    aws_region = # aws-region-code e.g. us-east-1
                                                 ^
SyntaxError: invalid syntax

**Comment by atqy** [comment]
The original file and issue no longer exists, therefore I will close this issue
