### ISSUE TITLE
mask-rcnn-efs.ipynb failed CI

### ISSUE THREAD

**Issue by hsl89** [aws/amazon-sagemaker-examples#2508]
Link to the notebook:
https://github.com/aws/amazon-sagemaker-examples/blob/master/advanced_functionality/distributed_tensorflow_mask_rcnn/mask-rcnn-efs.ipynb

Error:

---------------------------------------------------------------------------
Exception encountered at "In [1]":
  File "<ipython-input-1-1b037ff64807>", line 1
    aws_region = # aws-region-code e.g. us-east-1
                                                 ^
SyntaxError: invalid syntax

**Comment by atqy** [comment]
The original notebook and issue no longer exists, therefore I am closing this issue
