### ISSUE TITLE
mask-rcnn-scriptmode-efs.ipynb failed CI

### ISSUE THREAD

**Issue by hsl89** [aws/amazon-sagemaker-examples#2509]
Link to the notebook:
https://github.com/aws/amazon-sagemaker-examples/blob/master/advanced_functionality/distributed_tensorflow_mask_rcnn/mask-rcnn-scriptmode-efs.ipynb

Error:

---------------------------------------------------------------------------
Exception encountered at "In [1]":
  File "<ipython-input-1-0c391109ef7f>", line 5
    s3_bucket  = # your-s3-bucket-name
                                      ^
SyntaxError: invalid syntax

**Comment by atqy** [comment]
Closing this issue for now as I think more work is needed to make the notebooks fully functional on CI as:
(1) the notebooks make you manually pick between tensorpack_image and aws_samples_image (one solution may be to split one notebook into two notebooks that handles one image each but I think this needs further discussion)
(2) there may be some information that the user may need to input manually (i.e. container names, security group names, etc - there may be a possibility we can automate this but it will need further investigation)
