### ISSUE TITLE
[Bug Report] DeepAR-Electricity.ipynb has non-breaking deprecated methods/parameters

### ISSUE THREAD

**Issue by absinr** [aws/amazon-sagemaker-examples#2789]
**Link to the notebook**
https://github.com/aws/amazon-sagemaker-examples/blob/master/introduction_to_amazon_algorithms/deepar_electricity/DeepAR-Electricity.ipynb

**Describe the bug**
There are methods and parameters in the notebook that are deprecated on Python SDK v2.x.

**To reproduce**
Simply run the cells that contain the methods/parameters:
get_image_uri(), train_instance_count, & train_instance_type

**Logs**
Message from Jupyter cell output:
The method get_image_uri has been renamed in sagemaker>=2.
See: https://sagemaker.readthedocs.io/en/stable/v2.html for details.

train_instance_count has been renamed in sagemaker>=2.
See: https://sagemaker.readthedocs.io/en/stable/v2.html for details.
train_instance_type has been renamed in sagemaker>=2.
See: https://sagemaker.readthedocs.io/en/stable/v2.html for details.

**Comment by jkroll-aws** [comment]
Fixed, resolving.
