### ISSUE TITLE
sagemaker documentation for json_deserializer not able to execeute due to depreciation

### ISSUE THREAD

**Issue by martialai** [aws/amazon-sagemaker-examples#2853]
sagemaker documentation for json_deserializer not able to execeute due to depreciation
However I don't know how to make it work for the 2018 notebook for https://github.com/awslabs/visual-search/blob/master/notebooks/visual-search-feature-generation.ipynb visual search. 

from sagemaker.predictor import csv_serializer, json_deserializer
knn_predictor.serializer = CSVSerializer()
knn_predictor.deserializer = json_deserializer

query_id = 0
result = knn_predictor.predict(train_features[query_id])
print(result)

Its telling me json_deserializer is depreciated .  Im new to programming but I don't how to set the JSON deserialser to work in this casee

**Comment by martialai** [comment]
no need i have cancelled subcritption

**Comment by jkroll-aws** [comment]
Closing - the notebook has been fixed.
