### ISSUE TITLE
[Bug Report] deeplearning.net does not respond

### ISSUE THREAD

**Issue by jwpestrak** [aws/amazon-sagemaker-examples#2876]
**Link to the notebook**
github.com/aws/sagemaker-experiments/

**Describe the bug**
The `urllib.request.urlretrieve()` call returns an exception `URLError: <urlopen error [Errno 110] Connection timed out>`.

**To reproduce**
Run the code in the Examples section.

**Comment by jkroll-aws** [comment]
Fixed. Thanks for the bug report.
