### ISSUE TITLE
[Bug Report] CNN MNIST Hyperlink Not Working

### ISSUE THREAD

**Issue by pcolmer99** [aws/amazon-sagemaker-examples#2885]
**Link to the notebook**
https://github.com/aws/amazon-sagemaker-examples/blob/master/sagemaker-python-sdk/tensorflow_script_mode_training_and_serving/tensorflow_script_mode_training_and_serving.ipynb

**Describe the bug**
The "CNN MNIST example" hyperlink is not working.  It is under the section "Construct a script for distributed training".

**To reproduce**
Click on the link and a 404 page not found error occurs.

**Logs**
n/a

**Comment by jkroll-aws** [comment]
Fixed broken link. Resolving.
