### ISSUE TITLE
[Bug Report] Incorrect pipeline definition

### ISSUE THREAD

**Issue by juliensimon** [aws/amazon-sagemaker-examples#2903]
In https://github.com/aws/amazon-sagemaker-examples/blob/master/end_to_end/fraud_detection/5-pipeline-e2e.ipynb:

There's a missing dependency in 'Step 3: Create Dataset and Train/Test Split'. Here's the correct code.

create_dataset_step = ProcessingStep(
. . .
    code=create_dataset_script_uri,
    **depends_on=[claims_flow_step.name, customers_flow_step.name]**
)

**Comment by jkroll-aws** [comment]
Fixed. Thanks for reporting.
