### ISSUE TITLE
[Bug Report] object2vec_movie_recommendation.ipynb broken by changes in v2 of SageMaker Python SDK

### ISSUE THREAD

**Issue by rizblie** [aws/amazon-sagemaker-examples#2924]
**Link to the notebook**
https://github.com/aws/amazon-sagemaker-examples/tree/master/introduction_to_amazon_algorithms/object2vec_movie_recommendation

**Describe the bug**
In the section *Inference using trained model*, the call to *regressor.create_model()* model fails because the parameters
```
serializer=json_serializer, deserializer=json_deserializer, content_type="application/json"
```
are no longer supported by this method.

To fix this, these parameters need to be passed as part of *regression_model.deploy()* as follows:
```
predictor = regression_model.deploy(serializer=json_serializer, deserializer=json_deserializer, content_type="application/json", initial_instance_count=1, instance_type="ml.m4.xlarge")
```

There are also some other warnings about depracated / renamed identifiers (see attached log).
[object2vec_movie_recommendation_09Sep21.ipynb.gz](https://github.com/aws/amazon-sagemaker-examples/files/7137970/object2vec_movie_recommendation_09Sep21.ipynb.gz)

**To reproduce**

Just run through the notebook and you will hit the error in the first cell in the section *Inference using trained model*. The same error occurs again further down the notebook in the *Recommendation task* section.

**Logs**

```
serializer is a no-op in sagemaker>=2.
See: https://sagemaker.readthedocs.io/en/stable/v2.html for details.
deserializer is a no-op in sagemaker>=2.
See: https://sagemaker.readthedocs.io/en/stable/v2.html for details.
content_type is a no-op in sagemaker>=2.
See: https://sagemaker.readthedocs.io/en/stable/v2.html for details.
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-22-efc214ef98d2> in <module>
      4 # create a model using the trained algorithm
      5 regression_model = regressor.create_model(
----> 6     serializer=json_serializer, deserializer=json_deserializer, content_type="application/json"
      7 )

~/anaconda3/envs/python3/lib/python3.6/site-packages/sagemaker/estimator.py in create_model(self, role, image_uri, predictor_cls, vpc_config_override, **kwargs)
   1969             sagemaker_session=self.sagemaker_session,
   1970             predictor_cls=predictor_cls,
-> 1971             **kwargs,
   1972         )
   1973 

TypeError: __init__() got an unexpected keyword argument 'serializer'
```

[object2vec_movie_recommendation_09Sep21.ipynb.gz](https://github.com/aws/amazon-sagemaker-examples/files/7137986/object2vec_movie_recommendation_09Sep21.ipynb.gz)

**Comment by jkroll-aws** [comment]
Notebook has been fixed. Closing.
