### ISSUE TITLE
[Bug Report] The retail_trials-bathbodyworks dataset no longer exists

### ISSUE THREAD

**Issue by williams-katie** [aws/amazon-sagemaker-examples#2938]
**Link to the notebook**
https://github.com/aws/amazon-sagemaker-examples/blob/master/aws_marketplace/using_data/using_data_with_ml_model/using-dataset-product-from-aws-data-exchange-with-ml-model-from-aws-marketplace.ipynb

**Describe the bug**
The retail_trials-bathbodyworks dataset (from the ) no longer exists, so this notebook does not work. We've created a new notebook in this repo that works with the data currently available in Shutterstock's Free Sample Data. This notebook is located here: https://github.com/aws/amazon-sagemaker-examples/blob/master/aws_marketplace/using_data/image_classification_with_shutterstock_image_datasets/image-classification-with-shutterstock-datasets.ipynb

**To reproduce**
Subscribe to the Shuttterstock Free Sample dataset, scroll down to datasets, look for a dataset named "retail_trials-bathbodyworks". It does not exist

Shutterstock Free Sample Dataset can be found here: https://console.aws.amazon.com/dataexchange/home?region=us-east-1#/products/prodview-2h52yl4q6jrjw 

**Logs**
If applicable, add logs to help explain your problem.
You may also attach an `.ipynb` file to this issue if it includes relevant logs or output.

**Comment by jkroll-aws** [comment]
Thank you for the bug report. The notebook has been deleted since there is a new, accurate equivalent notebook. Closing.
