### ISSUE TITLE
[Bug Report] Invalid dataset_type in explainability_image_classification notebook

### ISSUE THREAD

**Issue by urirosenberg** [aws/amazon-sagemaker-examples#3063]
**Link to the notebook**
https://github.com/aws/amazon-sagemaker-examples/blob/343e8c36040f0367d817632c7caedc906cc58ffe/sagemaker_processing/computer_vision/explainability_image_classification.ipynb

**Describe the bug**
When running cell containing
```
explainability_data_config = clarify.DataConfig(
    s3_data_input_path=s3_data_input_path,
    s3_output_path=analysis_result_path,
    dataset_type="application/x-image",
)
```
Throws ```ValueError: Invalid dataset_type 'application/x-image'. Please check the API documentation for the supported dataset types.```
Indeed, looking at the API for clarify processing I see supported ```dataset_type``` in ```sagemaker.clarify.DataConfig``` Valid values are “text/csv” for CSV, “application/jsonlines” for JSONLines, and “application/x-parquet” for Parquet.

https://sagemaker.readthedocs.io/en/v2.71.0/api/training/processing.html

**To reproduce**
Run the above notebook in SM studio. Also tried running ```!pip install sagemaker -U``` to make sure I am running latest version of sagemaker.

**Logs**
If applicable, add logs to help explain your problem.
You may also attach an `.ipynb` file to this issue if it includes relevant logs or output.

**Comment by karan6181** [comment]
Maybe you need to restart your kernel since the jupyter notebook installs the latest sagemaker pypi version and the latest version won’t get used until you restart your kernel. Once you restart the kernel, it will use the latest sagemaker API version.

**Comment by urirosenberg** [comment]
@karan6181 Thanks but I tried restarting kernel and still seeing the same issue. 
Please note, as I mentioned earlier:
> looking at the API for clarify processing I see supported dataset_type in sagemaker.clarify.DataConfig Valid values are “text/csv” for CSV, “application/jsonlines” for JSONLines, and “application/x-parquet” for Parquet.

>https://sagemaker.readthedocs.io/en/v2.71.0/api/training/processing.html

@shisrat @panditshreya @jeniyat - anything I'm missing?

**Comment by urirosenberg** [comment]
Thanks @karan6181! 
Indeed, I ran 
`print(sagemaker.__version__)`
and saw I was on version 2.68.
After` !pip install sagemaker -U -q` and restarting the kernel, SageMaker sdk loaded with current current version: 2.70.0
Cheers!

**Comment by karan6181** [comment]
@urirosenberg Looks like your issue is resolved. Please feel free to close the issue. If you are still facing the issue, please let me know! Thanks!

**Comment by jkroll-aws** [comment]
Closing. Please reopen if needed. Thanks @karan6181 for the fix.
