### ISSUE TITLE
"Amazon SageMaker could not get a response from the endpoint".

### ISSUE THREAD

**Issue by nivedangowda** [aws/amazon-sagemaker-examples#3089]
I have built an anomaly detection model using AWS SageMaker inbuilt model: random cut forest.

    rcf = RandomCutForest(
    role=execution_role,
    instance_count=1,
    instance_type="ml.m5.xlarge",
    num_samples_per_tree=1000,
    num_trees=100,
    encrypt_inter_container_traffic=True,
    enable_network_isolation=True,
    enable_sagemaker_metrics=True)
and created the endpoint:-

    rcf_inference = rcf.deploy(
              initial_instance_count=4, instance_type="ml.m5.xlarge",
              endpoint_name='RCF-container2',
              enable_network_isolation=True)

But when I tried to get the prediction using the endpoint I am running into the following error:-

    results = rcf_inference.predict(df.values)

ModelError: An error occurred (ModelError) when calling the InvokeEndpoint operation: Received server error (0) from model with message "Amazon SageMaker could not get a response from the RCF-container2 endpoint. This can occur when CPU or memory utilization is high. To check your utilization, see Amazon CloudWatch. To fix this problem, use an instance type with more CPU capacity or memory."
I have tried with larger cpu instance but still I am getting the same issue. I guess the issue is functional.

Please help.

**Comment by ppagnone** [comment]
@nivedangowda  Could you comment your fix for this error please ? I have tried incrementing the instance type but the problem continue.
Thank you in advance

**Comment by nivedangowda** [comment]
@ppagnone take a subset of the data you want to predict the results and try it.
df_subset=df.iloc[:10,:]
results = rcf_inference.predict(df_subset.values)

This should work

**Comment by ppagnone** [comment]
@nivedangowda Thanks for your answer, my problem with the deploy of the model was because the model were not training correctly. Now I have resolved it.
Regards!

**Comment by SoulEvill** [comment]
> @nivedangowda Thanks for your answer, my problem with the deploy of the model was because the model were not training correctly. Now I have resolved it. Regards!

Hi @nivedangowda - I am running into the same issues, would you mind sharing more details? thanks a lot

**Comment by random1st** [comment]
@SoulEvill  @nivedangowda  Guys, the same problem, could you help, please?
