### ISSUE TITLE
[Example Request] HuggingFace EleutherAI GPT-J-6B Fine tuning on SageMaker using SageMaker Model Parallel

### ISSUE THREAD

**Issue by dhawalkp** [aws/amazon-sagemaker-examples#3151]
**Describe the use case example you want to see**
Show an example of training large [GPT-J EleutherAI 6B](https://huggingface.co/docs/transformers/model_doc/gptj) (https://huggingface.co/docs/transformers/model_doc/gptj) on SageMaker. Based on the size of the Model, it will not fit in a single GPU memory when its loaded in FP32. 

**How would this example be used? Please describe.**
Almost 6 months ago, [EleutherAI](https://www.eleuther.ai/) released [GPT-J 6B](https://huggingface.co/EleutherAI/gpt-j-6B), an open-source alternative to [OpenAIs GPT-3](https://openai.com/blog/gpt-3-apps/). [GPT-J 6B](https://huggingface.co/EleutherAI/gpt-j-6B) is the 6 billion parameter successor to [EleutherAIs](https://www.eleuther.ai/) GPT-NEO family, a family of transformer-based language models based on the GPT architecture for text generation.

[EleutherAI](https://www.eleuther.ai/)'s primary goal is to train a model that is equivalent in size to GPT⁠-⁠3 and make it available to the public under an open license.

Over the last 6 months, GPT-J gained a lot of interest from Researchers, Data Scientists, and even Software Developers, but it remained very challenging to fine tune GPT-J.

**Describe which SageMaker services are involved**
SageMaker Training, SageMaker Model Parallel, SageMaker Studio Notebook

**Describe what other services (other than SageMaker) are involved***
S3, IAM

**Describe which dataset could be used. Provide its location in s3://sagemaker-sample-files or another source.**
N/A

**Comment by dhawalkp** [comment]
The notebook for this is published here - https://github.com/aws/amazon-sagemaker-examples/tree/main/training/distributed_training/pytorch/model_parallel/gpt-j

**Comment by EilidhMc** [comment]
This is great! Thank you for sharing @dhawalkp :)  I had been trying to fine tune GPT-J on Sagemaker using the training script https://github.com/huggingface/transformers/blob/main/examples/pytorch/language-modeling/run_clm.py but I am running into Cuda memory errors.

Are there any examples of fine tuning GPT-J using SageMaker Model Parallel using your own training dataset rather than one from the datasets library?
