### ISSUE TITLE
[Example Request]Text Explainability for SageMaker BlazingText

### ISSUE THREAD

**Issue by dhawalkp** [aws/amazon-sagemaker-examples#3193]
**Describe the use case example you want to see**
SageMaker Clarify only takes CSV and JSON Lines as the input format for Explainability job. SageMaker BlazingText only supports JSON as the input format for inference and thus Clarify will not work as is to explain the predictions for SageMaker BlazingText. 

**How would this example be used? Please describe.**
This example will help all those customers who are looking to using Clarify for those models that do not support the input format required by Clarify.

**Describe which SageMaker services are involved**
SageMaker Clarify
SageMaker Training
SageMaker Hosting

**Describe what other services (other than SageMaker) are involved***
S3, IAM

**Describe which dataset could be used. Provide its location in s3://sagemaker-sample-files or another source.**
NA

**Comment by xgchena** [comment]
Thanks for sending the request here. Currently the SageMaker Clarify processing container doesn't support JSON format. One way to work with the BlazingText model is that you build your own model container to do the data transformation.

This SageMaker Clarify example notebook demonstrates how to build your own model and container that can work seamlessly with SageMaker Clarify processing jobs: https://github.com/aws/amazon-sagemaker-examples/blob/main/sagemaker_processing/fairness_and_explainability/fairness_and_explainability_byoc.ipynb

**Comment by xgchena** [comment]
Crossreference to the internal discussion: https://tiny.amazon.com/fqkadzg6

**Comment by dhawalkp** [comment]
I have already created a PR for this - https://github.com/aws/amazon-sagemaker-examples/pull/3194

**Comment by larroy** [comment]
Closing as the example notebook is merged.
