### ISSUE TITLE
[Bug Report]

### ISSUE THREAD

**Issue by caseyjconger** [aws/amazon-sagemaker-examples#3286]
**Link to the notebook**
sagemaker_processing/spark_distributed_data_processing/sagemaker-spark-processing.ipynb

**Describe the bug**
In the second and third examples (Example 2: Specify additional Python and jar file dependencies and Example 3: Run a Java/Scala Spark application) it uses a different dataset than the abalone dataset used in the prior example. I don't see where this other dataset is pulled in the notebook, and if I just clone the notebook and run in sagemaker studio (data science) it fails at that step because it can't find the dataset.

**To reproduce**
I just cloned the notebook and ran it on a sagemaker studio instance, and it fails because it can't find `./data/data.jsonl`

**Logs**
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
<ipython-input-12-3a6cffc65260> in <module>
      8 
      9 sagemaker_session.upload_data(
---> 10     path="./data/data.jsonl", bucket=bucket, key_prefix=input_prefix_sales
     11 )
     12 

/opt/conda/lib/python3.7/site-packages/sagemaker/session.py in upload_data(self, path, bucket, key_prefix, extra_args)
    231 
    232         for local_path, s3_key in files:
--> 233             s3.Object(bucket, s3_key).upload_file(local_path, ExtraArgs=extra_args)
    234 
    235         s3_uri = "s3://{}/{}".format(bucket, key_prefix)

/opt/conda/lib/python3.7/site-packages/boto3/s3/inject.py in object_upload_file(self, Filename, ExtraArgs, Callback, Config)
    322         ExtraArgs=ExtraArgs,
    323         Callback=Callback,
--> 324         Config=Config,
    325     )
    326 

/opt/conda/lib/python3.7/site-packages/boto3/s3/inject.py in upload_file(self, Filename, Bucket, Key, ExtraArgs, Callback, Config)
    146             key=Key,
    147             extra_args=ExtraArgs,
--> 148             callback=Callback,
    149         )
    150 

/opt/conda/lib/python3.7/site-packages/boto3/s3/transfer.py in upload_file(self, filename, bucket, key, callback, extra_args)
    286         )
    287         try:
--> 288             future.result()
    289         # If a client error was raised, add the backwards compatibility layer
    290         # that raises a S3UploadFailedError. These specific errors were only

/opt/conda/lib/python3.7/site-packages/s3transfer/futures.py in result(self)
    104             # however if a KeyboardInterrupt is raised we want want to exit
    105             # out of this and propogate the exception.
--> 106             return self._coordinator.result()
    107         except KeyboardInterrupt as e:
    108             self.cancel()

/opt/conda/lib/python3.7/site-packages/s3transfer/futures.py in result(self)
    263         # final result.
    264         if self._exception:
--> 265             raise self._exception
    266         return self._result
    267 

/opt/conda/lib/python3.7/site-packages/s3transfer/tasks.py in _main(self, transfer_future, **kwargs)
    253             # Call the submit method to start submitting tasks to execute the
    254             # transfer.
--> 255             self._submit(transfer_future=transfer_future, **kwargs)
    256         except BaseException as e:
    257             # If there was an exception raised during the submission of task

/opt/conda/lib/python3.7/site-packages/s3transfer/upload.py in _submit(self, client, config, osutil, request_executor, transfer_future, bandwidth_limiter)
    549         # Determine the size if it was not provided
    550         if transfer_future.meta.size is None:
--> 551             upload_input_manager.provide_transfer_size(transfer_future)
    552 
    553         # Do a multipart upload if needed, otherwise do a regular put object.

/opt/conda/lib/python3.7/site-packages/s3transfer/upload.py in provide_transfer_size(self, transfer_future)
    235         transfer_future.meta.provide_transfer_size(
    236             self._osutil.get_file_size(
--> 237                 transfer_future.meta.call_args.fileobj))
    238 
    239     def requires_multipart_upload(self, transfer_future, config):

/opt/conda/lib/python3.7/site-packages/s3transfer/utils.py in get_file_size(self, filename)
    243 
    244     def get_file_size(self, filename):
--> 245         return os.path.getsize(filename)
    246 
    247     def open_file_chunk_reader(self, filename, start_byte, size, callbacks):

/opt/conda/lib/python3.7/genericpath.py in getsize(filename)
     48 def getsize(filename):
     49     """Return the size of a file, reported by os.stat()."""
---> 50     return os.stat(filename).st_size
     51 
     52 

FileNotFoundError: [Errno 2] No such file or directory: './data/data.jsonl'

**Comment by MustafaWaheed91** [comment]
I see this issue as well as both the example notebook and readthedocs seem to show it.
