### ISSUE TITLE
Where is generate_synthetic_housing_data?

### ISSUE THREAD

**Issue by csetzkorn** [aws/amazon-sagemaker-examples#3436]
Hi all,

This is hopefully an easy one. Looking at:

[https://sagemaker-examples.readthedocs.io/en/latest/sagemaker-script-mode/sagemaker-script-mode.html](https://sagemaker-examples.readthedocs.io/en/latest/sagemaker-script-mode/sagemaker-script-mode.html)

and having done some fairly extensive searches, I cannot find:

generate_synthetic_housing_data

Does aynone know where the file is please? Thanks!

**Comment by jkroll-aws** [comment]
You can find this notebook on GitHub: https://github.com/aws/amazon-sagemaker-examples/blob/main/sagemaker-script-mode/sagemaker-script-mode.ipynb

And then the parent directory contains the generate_synthetic_housing_data script: https://github.com/aws/amazon-sagemaker-examples/blob/main/sagemaker-script-mode/generate_synthetic_housing_data.py

The ReadTheDocs website is a helpful resource for browsing, although I recommend cloning the entire repository when running examples yourself so the dependencies are available.
