### ISSUE TITLE
[Bug Report] TabTransformer/Gluon auto SM built-in FileNotFoundError: [Errno 2] No such file or directory: '/opt/ml/input/data/training/train/data.csv'

### ISSUE THREAD

**Issue by Rhuax** [aws/amazon-sagemaker-examples#3513]
**Describe the bug**
I'm trying to run a training experiment on sagemaker by using the newly added TabTransformer/AutoGluon-tabular algorithms. When the training starts it raises an exception "FileNotFoundError: [Errno 2] No such file or directory: '/opt/ml/input/data/training/train/data.csv'"
No matter how I pass my csv file, it expects a hardcoded data.csv file. It doesn't work even if I rename my training set to "data.csv".
**To reproduce**
```
from sagemaker import image_uris, model_uris, script_uris

train_model_id, train_model_version, train_scope = "autogluon-classification-ensemble", "*", "training"
training_instance_type = "ml.c4.2xlarge"

# Retrieve the docker image
train_image_uri = image_uris.retrieve(
    region=None,
    framework=None,
    model_id=train_model_id,
    model_version=train_model_version,
    image_scope=train_scope,
    instance_type=training_instance_type
)

# Retrieve the training script
train_source_uri = script_uris.retrieve(
    model_id=train_model_id, model_version=train_model_version, script_scope=train_scope
)

train_model_uri = model_uris.retrieve(
    model_id=train_model_id, model_version=train_model_version, model_scope=train_scope
)

training_dataset_s3_path = "s3://bucket/key/mytrain.csv"

s3_output_location = "s3://bucket/key2/"

from sagemaker import hyperparameters

# Retrieve the default hyper-parameters for training the model
hyperparameters = hyperparameters.retrieve_default(
    model_id=train_model_id, model_version=train_model_version
)

# [Optional] Override default hyperparameters with custom values
hyperparameters[
    "auto_stack"
] = "True"
print(hyperparameters)

from sagemaker.estimator import Estimator
from sagemaker.utils import name_from_base

training_job_name = "auto-gluon5"

# Create SageMaker Estimator instance
tabular_estimator = Estimator(
    role="myrole",
    image_uri=train_image_uri,
    source_dir=train_source_uri,
    model_uri=train_model_uri,
    entry_point="transfer_learning.py",
    instance_count=1,
    instance_type=training_instance_type,
    max_run=360000,
    hyperparameters=hyperparameters,
    output_path=s3_output_location
)

# Launch a SageMaker Training job by passing the S3 path of the training data
tabular_estimator.fit(
    {"training": training_dataset_s3_path}, logs=True, job_name=training_job_name
)
```

**Logs**
I'm attaching my job logs.
[log-events-viewer-result(1).csv](https://github.com/aws/amazon-sagemaker-examples/files/9198802/log-events-viewer-result.1.csv)
.

**Comment by Neo9061** [comment]
Hi @Rhuax! Thank you for using SageMaker built-in algorithms. The `training_dataset_s3_path` should be set as `s3://bucket/key` only for your case. Under the path `s3://bucket/key`, you need set up a directory `train` and `validation` (optional), where it contains `data.csv`, respectively. 

It is documented in the notebook:
`A S3 path should contain two sub-directories 'train/', and 'validation/' (optional). Each sub-directory contains a 'data.csv' file (The ABALONE dataset used in this example has been prepared and saved in training_dataset_s3_path shown below).`

We also have a new notebook that provides details on how to upload your dataset to S3 bucket to be used by the built-in algorithms:
https://github.com/aws/amazon-sagemaker-examples/blob/6ccaf6c3a71bd7c1508f507ec70590911af70d4c/introduction_to_applying_machine_learning/lightgbm_catboost_tabtransformer_autogluon_churn/churn-prediction-lightgbm-catboost-tabtransformer-autogluon.ipynb
Please review. Thanks and please let me know if you have any other question.

**Comment by Rhuax** [comment]
Hi Neo, thank you for your reply. Yes, indeed, I did like you said and now it works! Thank you again, I close this issue.
P.S. data.csv file should not be hardcoded like that btw
