### ISSUE TITLE
scikit_bring_your_own Dockerfile broken

### ISSUE THREAD

**Issue by tapomay** [aws/amazon-sagemaker-examples#354]
The space optimization by linking scipy libs with numpy is breaking for newer versions.

Issue identified in:
https://github.com/numpy/numpy/issues/11614

Broken Dockerfile:
https://github.com/awslabs/amazon-sagemaker-examples/blob/master/advanced_functionality/scikit_bring_your_own/container/Dockerfile

**Comment by tapomay** [comment]
Fixed in: https://github.com/awslabs/amazon-sagemaker-examples/issues/344
But this fix will prevent usage of future versions of numpy.

**Comment by seanpmorgan** [comment]
Thanks, this was fixed in #345
