### ISSUE TITLE
Can´t import Pandas in working_with_redshift_data.ipynb

### ISSUE THREAD

**Issue by lauracozma** [aws/amazon-sagemaker-examples#366]
Hi,

I am trying to connect to Redshift using the available provided example and it fails when trying to import pandas:  
AttributeError: module 'numpy' has no attribute '__version__' 

Specs: pandas 0.24 and numpy 0.15.

I´ve restarted the kernel, but the issue persists. 

!pip install numpy as an intermediary fix (refer to issue #280) is not solving the issue

Thanks,
Laura

**Comment by djarpin** [comment]
Hi @lauracozma - I'm unable to replicate your issue.  I was able to import and use both pandas and numpy after installing `psycopg2`.  Are you able to confirm that this bug happens with a new notebook instance?  And if so, exactly which cell is creating the problem?  Thanks.

**Comment by lauracozma** [comment]
Hi, 
This error happens when I copy a notebook (for instance using one of your already created examples). 
Also, if I create a new Sagemaker notebook instance it seems that I don´t get this error anymore.
It´s super weird, since I just copied another nothebook, and I have another similar error when importing the sagemaker library.

The way I succeeded working around this is to copy-paste all from the conda_python3 to another type of  notebook.

Thanks,
Laura

**Comment by djarpin** [comment]
Thanks, @lauracozma - Are you able to open up an AWS Support Case?  They should be able to access internal resources that would help troubleshoot your problem more quickly.

**Comment by hsl89** [comment]
Dear SageMaker Community,
             In our attempts to provide this repository with a better level of support             going forward, we’re closing issues that were opened prior to the v2 release of the SDK.             This is because we believe that over time many of the issues             posted were solved with the latest release or other recent changes to the repo.             This will help us reallocate resources towards issues that are            more likely to still be relevant today.            Some of the issues experienced now can be resolved by referencing the            v2 guide: https://sagemaker.readthedocs.io/en/stable/v2.html             In this guide, you can find simple solutions to common notebook errors,             like the renaming of parameters and classes.            If you believe your issue is still ongoing and you have updated error            messaging or other info, please re-open it, and we investigate the issue.
            Best Regards,
            AWS SageMaker Team
