### ISSUE TITLE
Custom Model Integration Image Recognition

### ISSUE THREAD

**Issue by murtuza07** [aws/amazon-sagemaker-examples#381]
Hi,

 I was able to successfully use the in-built models.  Now I want to integrate a custom computer vision model in Amazon SageMaker. Can you guys give an example of how to do this.

Using this openly available model: https://codelabs.developers.google.com/codelabs/tensorflow-for-poets/index.html#0

Regards,
Murtuza

**Comment by murtuza07** [comment]
Hi @djarpin  - Thanks for the response!!

I'll try your suggestions and let you know what happened!

Thanks a lot!

Regards,
Murtuza

**Comment by hsl89** [comment]
Dear SageMaker Community,
             In our attempts to provide this repository with a better level of support             going forward, we’re closing issues that were opened prior to the v2 release of the SDK.             This is because we believe that over time many of the issues             posted were solved with the latest release or other recent changes to the repo.             This will help us reallocate resources towards issues that are            more likely to still be relevant today.            Some of the issues experienced now can be resolved by referencing the            v2 guide: https://sagemaker.readthedocs.io/en/stable/v2.html             In this guide, you can find simple solutions to common notebook errors,             like the renaming of parameters and classes.            If you believe your issue is still ongoing and you have updated error            messaging or other info, please re-open it, and we investigate the issue.
            Best Regards,
            AWS SageMaker Team
