### ISSUE TITLE
Suggestion: DeepAR cat

### ISSUE THREAD

**Issue by pjebs** [aws/amazon-sagemaker-examples#388]
It would be nice if we can set arbitrary values for `cat` array rather than starting at 0.

We can then use our own internal number system rather than convert to cardinal series and track the correspondence.

**Comment by pjebs** [comment]
```
ClientError: Training set did not contain examples for all categories of the 1-th categorical feature. All values for cat in the range 0 <= cat < (cardinality = 2) need to be contained in the training set. Missing values are [0]
```

**Comment by geoalgo** [comment]
Hi pjebs, 

I understand your point. 

We took this decision to avoid letting misconfigurations or errors in the data-processing go through. Also, we want to avoid to have very sparse vectors as embedding needs to allocate memory for each class.

If you have sparse categories, I would suggest to use a default category for classes that do not occur frequently. 

I hope this helps.

**Comment by rtrench** [comment]
Hello, 
Would it not be possible to have the algorithm do the "cat" label encoding directly, instead of expecting cateogires in a closed interval?

**Comment by hsl89** [comment]
Dear SageMaker Community,
             In our attempts to provide this repository with a better level of support             going forward, we’re closing issues that were opened prior to the v2 release of the SDK.             This is because we believe that over time many of the issues             posted were solved with the latest release or other recent changes to the repo.             This will help us reallocate resources towards issues that are            more likely to still be relevant today.            Some of the issues experienced now can be resolved by referencing the            v2 guide: https://sagemaker.readthedocs.io/en/stable/v2.html             In this guide, you can find simple solutions to common notebook errors,             like the renaming of parameters and classes.            If you believe your issue is still ongoing and you have updated error            messaging or other info, please re-open it, and we investigate the issue.
            Best Regards,
            AWS SageMaker Team
