### ISSUE TITLE
[xgboost_customer_churn] Error on prediction request regarding columns of generated testData csv

### ISSUE THREAD

**Issue by nikospsa** [aws/amazon-sagemaker-examples#392]
Hello, I have created a c# application and I am trying to send request to a model - by using the aws sagemaker API - that it has being trained by running the xboost_customer_churn.ipynb. I have downloaded the test_data from the s3 bucket and when I am sending the request I am getting the following error:

> 'Unable to evaluate payload provided: Feature size of csv inference data 70 is not consistent with feature size of trained model 69'

If I remove a column I get a response but obviously this is not a solution because I don't know how this will affect the results.

Should I remove the Churn?_True column? It is the only one that makes sense

Attached you will find the csv file I am using.

[testData.zip](https://github.com/awslabs/amazon-sagemaker-examples/files/2328370/testData.zip)

Can you advise me on how to proceed? 

Thank you in advance

**Comment by hsl89** [comment]
Dear SageMaker Community,
             In our attempts to provide this repository with a better level of support             going forward, we’re closing issues that were opened prior to the v2 release of the SDK.             This is because we believe that over time many of the issues             posted were solved with the latest release or other recent changes to the repo.             This will help us reallocate resources towards issues that are            more likely to still be relevant today.            Some of the issues experienced now can be resolved by referencing the            v2 guide: https://sagemaker.readthedocs.io/en/stable/v2.html             In this guide, you can find simple solutions to common notebook errors,             like the renaming of parameters and classes.            If you believe your issue is still ongoing and you have updated error            messaging or other info, please re-open it, and we investigate the issue.
            Best Regards,
            AWS SageMaker Team
