### ISSUE TITLE
I am having an issue in getting inference for my forecasting data

### ISSUE THREAD

**Issue by sumedhvdatar** [aws/amazon-sagemaker-examples#400]
The data was used and the training was successful.

I am trying to write the customized inference script to get an inference for my forecasting data and I get the following error.

TypeError: 'builtin_function_or_method' object is not subscriptable

Stack trace details : 

TypeError                                 Traceback (most recent call last)
<ipython-input-46-a389e20ce533> in <module>()
      1 # print(time_series_training[:5])
----> 2 list_of_df = predictor.predict(time_series_testing)
      3 # actual_data = time_series[:5]

<ipython-input-34-287c750eac00> in predict(self, ts, cat, encoding, num_samples, quantiles)
     27         Return value: list of `pandas.DataFrame` objects, each containing the predictions
     28         """
---> 29         prediction_times = [x.index[-1]+1 for x in ts]
     30         req = self.__encode_request(ts, cat, encoding, num_samples, quantiles)
     31         res = super(DeepARPredictor, self).predict(req)

<ipython-input-34-287c750eac00> in <listcomp>(.0)
     27         Return value: list of `pandas.DataFrame` objects, each containing the predictions
     28         """
---> 29         prediction_times = [x.index[-1]+1 for x in ts]
     30         req = self.__encode_request(ts, cat, encoding, num_samples, quantiles)
     31         res = super(DeepARPredictor, self).predict(req)

This is the input inference json : 

{"instances": ["{\"start\":\"2018-05-02 00:00:00\",\"target\":[-0.36459741,0.55042065,0.59381338,-0.04289749,0.37203028,-0.33508443,-0.23058125,-0.85094498,-0.85707781,0.38844667,-0.15900809,1.54174953,1.54192149,-0.47851926,-0.55046993,1.59988586,-0.29810551,-0.64564913,-0.4236627,-0.63366214,-0.01922621,-0.71196562,0.45233032,-1.04631851,-1.24381427,0.00079984,-0.1563395,-0.19640894,-0.6171601,-0.81763158,1.83060745,-1.01264122,-0.73854367,0.77871271,0.52856842,-0.7157278,0.02415618,-0.00497848,-0.19142833,-0.19288987,-0.19175394,-0.19240375,-0.19562502,-0.19337495,-0.19353641,-0.18880607,-0.1906122,-0.19110224,-0.18847608,-0.18798015,-0.19434199,-0.18897087,-0.15807625,-0.15515858,-0.16018534,-0.1549623,-0.15769005,-0.15338388,-0.15710914,-0.19240375,-0.15788326,-0.1549623,-0.19288987,-0.1906122,-0.19594466,-0.2221173,-0.19642329,-0.19690092,-0.4218802,2.45831976,-0.4081377,-0.41738397,-0.41421528,-0.40143639,-0.11215113,-0.11451546,-0.11161927,-0.11215113,-0.11294446,-0.10946727,-0.1118855,-0.11027895,-0.10946727,-0.11320773,-0.10864981,-0.11268061,-0.10973846,-0.11000903,-0.11135244,-0.11027895,-0.10782644,-0.10503744,-0.11081693,-0.10946727,-0.10892294,-0.11054825,-0.11373253,-0.11081693,-0.11425505,-0.10727418,-0.11135244,-0.11425505,-0.11241617,-0.11555153,-0.1118855,-0.11027895,-0.10973846,-0.10973846,-0.11477531,-0.10810156,-0.11683437,-0.11632284,-0.11054825,-0.11215113,-0.11027895,-0.1118855,-0.11268061,-0.11425505,-0.11529334,-0.10616144,-0.11108499,-0.11000903,-0.10727418,-0.11215113,-0.1118855,-0.11320773,-0.10755065,-0.11135244,-0.10699703,-0.10727418,-0.10837601,-0.10946727,-0.10755065,-0.10475464,-0.10304224,-0.1067192,-0.10560087,-0.10475464,-0.10810156,-0.10699703,-0.10946727,-0.10837601,-0.1067192,-0.10837601,-0.10447111,-0.10864981,-0.10919543,-0.1067192,-0.10560087,-0.10560087,-0.10475464,-0.10919543,-0.10946727,-0.10946727,-0.10188534,0.,0.,0.,0.,0.,0.,0.,0.,-0.10531952,1.,0.,0.,0.,0.,0.,-0.10810156,-0.09981981,0.06808826,-0.11345134,-0.60872845,-0.71635056,1.13733724,1.75839707,-0.72155866,-0.81432909,-0.46546239,0.82316199,-0.06561195,-0.75069998,0.47221419,-0.29012746,1.01846108,0.43419786,-0.87092115,0.00702683,0.80963851,-0.67564453,-0.73261745,-0.70955464,-0.23450454,-0.43241036,0.46794488,-0.58586722,-0.5648003,-0.55280226,-0.52326429,-0.39256227,-1.04126053,1.45075189,-0.36955801,-0.52100344,-0.75598856,0.96188674,-0.71292208,-0.51469287,-0.51355125,0.65261631,1.07652719,-0.41901126,0.40223956,-0.85285391,0.90795837,0.74895531,0.70297317,0.5222796,0.44865037,-0.82049303,-1.11198611,0.29352679,-1.15478583,-1.24959966,-1.2347587,1.60494219,-0.27251745,-0.63171036,-0.74677933,-0.99760197,-0.93303777,-0.5507258,0.96751437,-0.26676812,-0.74265054,0.6745438,-0.51612885,0.44985449,1.34926359,0.75036555,-0.79955642,-0.13587545,1.83311473,-0.66472749,-0.80916118,-0.40162453,-0.3959442,-0.91759003,0.49635516,-0.93591404,1.7502337,-0.38644614,-0.96612576,-0.81569338,1.12134449,0.16324667,1.7361695,0.3640735,-0.65475231,0.93366626,0.6610324,0.69125231,0.62568593,0.43977023,-0.63168666,-0.64781404,-0.9165053,0.22201421,0.18883107,0.35127844,0.23851849,-0.76859238,0.40267917,0.20068468,0.57396624,1.50605632,1.30332603,0.76705295,0.64545821,0.723053,0.65768989,-0.3890279,-0.66564949,-0.74598783,-0.96484452,0.39407528,0.4123496,0.41684443,0.43701689,-0.72993796,0.53931764,0.41971069,0.56041674,1.41552614,1.0535714,0.28538934,0.67696161,0.66031109,0.60291641,0.68977513,-0.57958645,-0.56081028,-0.85511181,-0.14523485,-0.12643404,0.29130707,-0.05727643,-0.80632686,0.20490273,-0.05014923,0.55884332,1.53990978,1.50105289,1.27764594,-0.93366626,0.39263211,-0.73570315,-0.27850596,-0.34968701,0.98548797,-0.17326968,-0.17322684,1.74270247,-0.62790906,-0.74263919,0.73392253,-0.23670025,-0.7638072,-0.86848892,-0.92194418,0.17365086,0.78809319,-0.16039286,0.89232686,-0.74033214,0.17242593,1.12644356,-0.23089775,-0.29636513,-0.2387412,4.83402018,-0.03961914,-0.34579429,0.,-0.18005679,-0.2215412,-0.0349347,0.,-0.08583449,-0.09620813,-0.12354403,-0.15199057,-0.17448325,-0.37791433,-0.15826903,0.,0.,-0.40484166,-0.08445117,-0.11451546,-0.08410189,0.,-0.46159352,-0.09712574,0.,-1.3704192,-0.53851996,-0.06248361,0.,-0.16856606,0.,-0.10304224,-0.20610317,-0.08583449,-0.0555507,-0.09953288,-0.14916847,-0.27042225,-0.13974598,0.,0.,0.,-0.15574607,0.,0.,0.,0.,0.,-0.12426846,-0.11477531,-0.13779049,0.,-0.08514556,-0.1306186,0.,-0.12354403,0.,0.,-0.01319718,-0.02155403,-0.13844516,-0.09620813,-0.13038858,0.,0.,-0.07287076,-0.13822725,-0.13558715,0.,0.,-0.2387412,0.,-0.21791251,-0.07755384,0.,-0.23256639,0.,0.,0.,0.,0.,0.,-0.18731716,-0.09403352,-0.11108499,-0.06201375,-0.06523281,-0.17501239,0.,0.,0.,-0.4070726,0.,0.,-0.10012597,0.,0.,0.,-0.11081693,-0.02748009,9.98741899,-0.15594145,0.,0.,0.,-0.25033902,-0.19911699,-0.03735003,0.,-0.55808596,1.55873475,0.40782703,0.07273703,-0.65578221,0.42148854,-0.27059877,-0.38737116,2.6566234,-0.42173957,-0.59358641,0.52223792,-1.17770853,0.71291992,-0.37604727,-0.30166429,-0.21782901,-0.3531458,1.59231652,-0.38759524,0.3224274,-0.67627576,-0.13310613,-0.27476486,1.14234201,-0.07072099,1.10586123,1.30689392,0.26780806,-0.96289774,-0.65431089,-0.48085178,-0.43929029,-0.20137655,2.97837093,-0.59660626,-0.43780638,-0.55868762,-0.14593963,-0.47618566,-0.45992673,0.54141362,-0.76509804,4.16200723,0.0057722,-0.46254971,-0.44731897,2.20567376,-0.87003965,0.12441818,-0.44462679,-0.38442093,1.18522595,-0.48359481,-0.47888613,0.51635472,-0.63571513,-0.34770707,-0.14039221,2.03030918,-0.54467606,-0.26598613,0.68374513,2.36996309,1.23723218,1.88729775,-0.55389463,-0.44781786,-0.39026245,-0.19775408,-0.56593958,-0.00980287,0.13715697,0.6485442,0.63212872,-0.30111859,0.9473922,-0.71459208,-0.36946007,5.14536103,-0.17769603,-0.82570647,-0.4441198,-1.01803464,-0.64982837,-0.34004147,1.20397475,-0.0667429,1.92099867,0.91246094,-0.32381172,-0.11676188,-0.07058064,0.77108605,-0.04702175,-0.40414605,-0.36941968,-0.49080714,-0.46678052,-0.46079869,0.10208161,-0.47914552,-0.4795196,-1.54952869,-0.75144207,-0.71254047,1.52465649,-0.46085317,1.04133322,0.96496129,-0.7755022,-0.57536423,1.24435866,1.58365348,-0.87898323,-0.76274759,-0.62359618,0.56342182,0.60652573,0.82805436,0.11718884,-0.70197217,-0.15613661,-0.02286216,-0.45462356,0.28288232,-1.34555312,-0.12236131,0.50338093,-0.61022817,1.6625951,-0.40316709,0.71138443,0.25617911,-0.49511715,-0.43715172,-0.43538523,0.5603554,-0.17402813,-0.42707102,-0.91969005,-0.28753942,-0.86346595,-0.18255492,-0.11161927,-0.10616144,-0.10560087,-0.10727418,-0.10864981,-0.87052585,-1.0487319,0.85064814,1.28978684,0.,0.,-0.17235236,0.,-0.36516639,-0.13974598,-0.08445117,0.,0.,0.,-0.20271305,-0.08583449,0.,0.,-0.17919596,-0.8505818,-0.14337243,-0.10447111,0.,-0.21835055,0.,0.,0.,-0.06248361,0.,0.,-0.09982985,-0.02155403,-0.03961914,-0.22512219,9.98741899,0.,-0.0555507,-0.07165326,-0.08583449,0.,0.,0.,-0.38995684,-0.09276882,1.48482597,-0.14916847,-0.35612246,-0.22297919,-0.23778899,-0.22823585,-0.48182531,-0.53187896,-0.12060543,-0.22583288,-0.07446378,1.90360846,-0.30474552,-0.30097644,-0.30588158,-0.30780654,-0.30916062,-0.30769353,-0.30360665,-0.29624923,-0.29158756,-0.294856,-0.29217304,0.,9.49491649,-0.10810156,-0.69900737,-0.22985624,-0.54963529,0.11162393,-1.5709135,0.50338093,0.50065272,-0.75899148,-0.59093579,9.25056022,-0.55899173]}\n"], "configuration": {"output_types": ["mean", "quantiles", "samples"], "num_samples": 1, "quantiles": [0.1, 0.9]}}

Let me know if you need more information . i am stuck with the inference code and need help. Thanks!

**Comment by rshyamsundar** [comment]
@ sumedhvdatar - I think you are not passing the `time_series_testing` in the correct format to the `predict` method. From the stack trace, I see that you are using the inference code given in the Sagemaker-DeepAR demo notebook. The `predict` method in the notebook expects a list of Pandas time series as input. This is written as a convenience method for transforming Pandas time series to the request format that a trained DeepAR model expects (Line: req = self.__encode_request(ts, cat, encoding, num_samples, quantiles)).

Can you confirm if `time_series_testing` is in deed a list of Pandas time series?

**Comment by hsl89** [comment]
Dear SageMaker Community,
             In our attempts to provide this repository with a better level of support             going forward, we’re closing issues that were opened prior to the v2 release of the SDK.             This is because we believe that over time many of the issues             posted were solved with the latest release or other recent changes to the repo.             This will help us reallocate resources towards issues that are            more likely to still be relevant today.            Some of the issues experienced now can be resolved by referencing the            v2 guide: https://sagemaker.readthedocs.io/en/stable/v2.html             In this guide, you can find simple solutions to common notebook errors,             like the renaming of parameters and classes.            If you believe your issue is still ongoing and you have updated error            messaging or other info, please re-open it, and we investigate the issue.
            Best Regards,
            AWS SageMaker Team
