### ISSUE TITLE
Running an .ipynb file from Lambda function or Sagemaker Lifecycle Config

### ISSUE THREAD

**Issue by Geo-Joy** [aws/amazon-sagemaker-examples#403]
Hi I wanted to run an .ipynb file while starting a Sagemaker instance.
current status is:
Cloudwatch(**success**) ->  Lambda(**success**) - > Sagemaker instance(**success**) -> Running Particular Notebook (**_failed_**)

1.I tried using "Sagemaker Lifecycle" config with the code
`jupyter nbconvert --execute prediction-12hr.ipynb --ExecutePreprocessor.kernel_name=conda_tensorflow_p36`

but getting an error
`[NbConvertApp] Converting notebook prediction-12hr.ipynb to html
[NbConvertApp] Executing notebook with kernel: conda_tensorflow_p36
`
...
 `raise NoSuchKernel(kernel_name)
jupyter_client.kernelspec.NoSuchKernel: No such kernel named conda_tensorflow_p36
`

### on running 
`!conda env list'

#### conda environments:
base                  *  /home/ec2-user/anaconda3
JupyterSystemEnv         /home/ec2-user/anaconda3/envs/JupyterSystemEnv
chainer_p27              /home/ec2-user/anaconda3/envs/chainer_p27
chainer_p36              /home/ec2-user/anaconda3/envs/chainer_p36
mxnet_p27                /home/ec2-user/anaconda3/envs/mxnet_p27
mxnet_p36                /home/ec2-user/anaconda3/envs/mxnet_p36
python2                  /home/ec2-user/anaconda3/envs/python2
python3                  /home/ec2-user/anaconda3/envs/python3
pytorch_p27              /home/ec2-user/anaconda3/envs/pytorch_p27
pytorch_p36              /home/ec2-user/anaconda3/envs/pytorch_p36
tensorflow_p27           /home/ec2-user/anaconda3/envs/tensorflow_p27
tensorflow_p36           /home/ec2-user/anaconda3/envs/tensorflow_p36

2. Also tried injecting a python/bash code to run the instance startup, pausing the start-up code to wait untill conda instance is setup by sagemaker. 
**Still no luck**

Can someone suggest a plan to run .ipynb file in anyways possible.

**Comment by ChoiByungWook** [comment]
Hello @Geo-Joy,

I apologize for the late response.

Would using [runipy](https://pypi.org/project/runipy/) on lambda work for you?

**Comment by mas-dse-mhardist** [comment]
Try the following with the Sagemaker lifecycle config:

--------

sudo -u ec2-user -i <<'EOF'
pip install runipy
runipy /home/ec2-user/SageMaker/<path to execute prediction-12hr.ipynb> --html runreport.html

---------
The issue I have with the above is that it times out after 5 minutes and my script runs long. Suggest you time your .ipynb.

Also - each cell that runs will show up in CloudWatch.  You can watch as the notebook is running.

**Comment by utpal0401** [comment]
hello i'm facing the same issue, how to run a .ipynb file "/home/ec2-user/SageMaker/xxxxxxxxxx.ipynb" from Lambda function with s3 trigger. I'm using runipy package on lambda but how to use it to run a Ipython file on sagemaker . I'm New on AWS

**Comment by ravikhatri449** [comment]
This worked for me:)

#!/bin/bash

set -e

ENVIRONMENT=JupyterSystemEnv
NOTEBOOK_FILE=/home/ec2-user/SageMaker/xxxxx.ipynb

source /home/ec2-user/anaconda3/bin/activate "$ENVIRONMENT"

nohup jupyter nbconvert --ExecutePreprocessor.timeout=-1  --to notebook --execute "$NOTEBOOK_FILE" & 

source /home/ec2-user/anaconda3/bin/deactivate

**Comment by barbarasilveiraf** [comment]
> ok --execute "$NOTEBOOK_FILE" &
> 
> source /home/ec2-user/anaconda3/bin/deactivate

Hello @ravikhatri449 for me not show error in CloudWatch, but in some minutes the Machine SageMaker happer Failed. Did this happen to you?

**Comment by ravikhatri449** [comment]
Hey @barbarasilveiraf  can you elaborate the issue
In my situation, I'm running the notebook instance using Cloudwatch and  AWS  lambda and then executing the .ipynb file using lifecycle config mentioned above
Can you elaborate on the Machine  Sagemaker happer? What do you exactly mean by that

**Comment by AshrayManohar** [comment]
Thanks @ravikhatri449 it worked for me, the only change I had to make is to change "kernal_name" to "kernel_name"

**Comment by abhishekshankar891** [comment]
@ravikhatri449 - I need to run a notebook containing preprocessing steps using lambda can u help me with any helpful links?

**Comment by abhishekshankar891** [comment]
Hi we were able to make it work ,the thing we missed was creating repository in code commit ->https://aws.amazon.com/blogs/machine-learning/how-to-use-common-workflows-on-amazon-sagemaker-notebook-instances/ -> and moving the .ipynb file inside folder created in sagemaker . Hope this links helps newbies like us .

But our notebook normally runs for ore than 15 mins . Hence seems its failing in our case. Please provide any suggestion . Thanks

**Comment by Refik1** [comment]
Mister @ravikhatri449 I did as in your description,my Lambda and cloudwatch for notebook insantce  is working very well but lifecycle configuration is not working with .ipynb file. I didn't get any error in Lifecycle Configuration and Lambda but .ipynb is not working. Can you or someone help me for this problem

**Comment by hsl89** [comment]
Dear SageMaker Community,
             In our attempts to provide this repository with a better level of support             going forward, we’re closing issues that were opened prior to the v2 release of the SDK.             This is because we believe that over time many of the issues             posted were solved with the latest release or other recent changes to the repo.             This will help us reallocate resources towards issues that are            more likely to still be relevant today.            Some of the issues experienced now can be resolved by referencing the            v2 guide: https://sagemaker.readthedocs.io/en/stable/v2.html             In this guide, you can find simple solutions to common notebook errors,             like the renaming of parameters and classes.            If you believe your issue is still ongoing and you have updated error            messaging or other info, please re-open it, and we investigate the issue.
            Best Regards,
            AWS SageMaker Team
