### ISSUE TITLE
Feature size different for trained model and inference data

### ISSUE THREAD

**Issue by anshulbh** [aws/amazon-sagemaker-examples#405]
I am running the XGBoost model on a data set with 11 features excluding the target variable. The train, test and validation splits are stored in my S3 bucket. I upload the data sets to S3 and give them as inputs to the model from there. When testing the model with test data by hitting the endpoint with the code below, I get the following error.

**Code**
```
xgb_predictor.content_type = 'text/csv'
xgb_predictor.serializer = csv_serializer
xgb_predictor.deserializer = None
def predict(data, rows=500):
    split_array = np.array_split(data, int(data.shape[0] / float(rows) + 1))
    predictions = ''
    for array in split_array:
        predictions = ','.join([predictions, xgb_predictor.predict(array).decode('utf-8')])

    return np.fromstring(predictions[1:], sep=',')

predictions = predict(test_data.as_matrix()[:, 1:])
```
**Error**
```
 ModelError                                Traceback (most recent call last)
<ipython-input-129-d9f7cce714df> in <module>()
      7     return np.fromstring(predictions[1:], sep=',')
      8 
----> 9 predictions = predict(train_data.as_matrix()[:, 1:])

<ipython-input-129-d9f7cce714df> in predict(data, rows)
      3     predictions = ''
      4     for array in split_array:
----> 5         predictions = ','.join([predictions, xgb_predictor.predict(array).decode('utf-8')])
      6 
      7     return np.fromstring(predictions[1:], sep=',')

~/anaconda3/envs/python3/lib/python3.6/site-packages/sagemaker/predictor.py in predict(self, data)
     84             request_args['Accept'] = self.accept
     85 
---> 86         response = self.sagemaker_session.sagemaker_runtime_client.invoke_endpoint(**request_args)
     87 
     88         response_body = response['Body']

~/anaconda3/envs/python3/lib/python3.6/site-packages/botocore/client.py in _api_call(self, *args, **kwargs)
    312                     "%s() only accepts keyword arguments." % py_operation_name)
    313             # The "self" in this scope is referring to the BaseClient.
--> 314             return self._make_api_call(operation_name, kwargs)
    315 
    316         _api_call.__name__ = str(py_operation_name)

~/anaconda3/envs/python3/lib/python3.6/site-packages/botocore/client.py in _make_api_call(self, operation_name, api_params)
    610             error_code = parsed_response.get("Error", {}).get("Code")
    611             error_class = self.exceptions.from_code(error_code)
--> 612             raise error_class(parsed_response, operation_name)
    613         else:
    614             return parsed_response

ModelError: An error occurred (ModelError) when calling the InvokeEndpoint operation: Received client error (400) from model with message "Unable to evaluate payload provided: Feature size of csv inference data 11 is not consistent with feature size of trained model 7".
```
I have tried both, CSV and libSVM formats and getting the same error.

**Comment by anshulbh** [comment]
The train and validation data has 11 features excluding the target variable but the model has only 7 which is causing the error when I pass test data. Could it be a bug in the model and the way is handles data?

**Comment by djarpin** [comment]
Hi @anshulbh - Could you provide a few example rows of what your training data looks like?  Feel free to mask it if it's confidential.

**Comment by anshulbh** [comment]
0,397,83968.18,37094.0,0.0,535019.09,618987.28,0,1,0,0,0
0,282,407936.78,0.0,0.0,802040.67,1209977.45,0,0,0,0,1
0,212,3603.63,249474.19,245870.56,0.0,0.0,0,0,0,1,0
0,355,303983.43,2864701.5,3168684.93,362257.7,58274.26,1,0,0,0,0
0,258,243767.94,45143.95,288911.88,10755223.59,10511455.65,1,0,0,0,0
0,204,152058.33,51606.0,0.0,0.0,152058.33,0,1,0,0,0
0,354,24828.05,0.0,0.0,0.0,0.0,0,0,0,1,0
0,288,119923.47,2112103.42,2232026.88,330228.2,210304.74,1,0,0,0,0
0,250,166165.86,0.0,0.0,2714884.51,2881050.37,0,1,0,0,0
0,185,260553.4,19737.0,0.0,52749.78,313303.18,0,1,0,0,0
0,137,33868.67,17117.29,0.0,18717228.86,18751097.53,0,1,0,0,0
0,205,226150.54,95012.0,321162.54,203279.07,0.0,1,0,0,0,0
0,331,124499.1,90621.48,0.0,162370.34,286869.44,0,1,0,0,0
0,137,3632.53,0.0,0.0,0.0,0.0,0,0,0,1,0
0,351,18598.35,11522.0,0.0,0.0,0.0,0,0,0,1,0
0,256,179608.49,745.0,0.0,875620.24,1055228.73,0,1,0,0,0
0,302,11627.83,10154.0,0.0,0.0,0.0,0,0,0,1,0
0,164,86162.68,0.0,0.0,8516982.65,8603145.33,0,1,0,0,0
0,8,408282.12,0.0,0.0,853935.25,1382676.85,0,1,0,0,0
0,160,49854.13,0.0,0.0,0.0,0.0,0,0,0,1,0
0,227,77975.89,171.0,0.0,0.0,0.0,0,0,0,1,0
0,45,81896.74,20757.0,0.0,3051719.1,3133615.83,0,0,0,0,1
0,44,9661.51,20548.0,10886.49,0.0,0.0,0,0,0,1,0
0,12,10514.47,239887.25,229372.78,0.0,0.0,0,0,0,1,0
0,298,112111.55,39633.0,0.0,33089.59,145201.15,0,1,0,0,0
0,203,193031.46,222989.0,29957.54,180947.37,373978.83,0,1,0,0,0
0,180,198804.57,0.0,0.0,463653.11,662457.69,0,1,0,0,0
0,277,952.41,6650.27,5697.85,0.0,0.0,0,0,0,1,0
0,14,598580.24,0.0,0.0,1570077.93,2168658.17,0,0,0,0,1
0,251,85121.28,0.0,0.0,1601069.55,1686190.83,0,1,0,0,0
0,161,743058.95,109817.0,0.0,183.86,743242.8,0,0,0,0,1
0,301,125008.15,0.0,0.0,571579.35,696587.51,0,1,0,0,0
0,214,109741.66,0.0,0.0,113322.57,223064.24,0,0,0,0,1
0,396,22859.43,69322.0,46462.57,0.0,0.0,0,0,0,1,0
0,304,106403.82,11280.0,0.0,634932.9,741336.72,0,1,0,0,0
0,260,245900.82,371.0,0.0,0.0,245900.82,0,1,0,0,0
0,43,28592.78,5021.0,33613.78,0.0,0.0,1,0,0,0,0
0,347,52570.67,3771135.1,3823705.77,1504682.42,1452111.75,1,0,0,0,0
0,358,16988967.91,0.0,0.0,31864069.72,48853037.63,0,0,0,0,1
0,379,43025.15,658.0,43683.15,1156016.68,1112991.53,1,0,0,0,0
0,17,91737.0,143890.83,52153.83,378428.74,470165.73,0,1,0,0,0
0,393,56562.51,14593.0,0.0,0.0,56562.51,0,1,0,0,0

The first value in each row is the binary target variable. The last five variables are also binary.

**Comment by EvanzzzZ** [comment]
Hi @anshulbh - I tried out with your sample data for both training and inference on SageMaker. I didn't come into any issue. Did you train your model outside of SageMaker?

**Comment by anshulbh** [comment]
Hi @EvanzzzZ  - I am attaching my Jupyter notebook and link to the data set. 

[https://www.kaggle.com/ntnu-testimon/paysim1](url)
[Finance-FraudDetection-Copy1.zip](https://github.com/awslabs/amazon-sagemaker-examples/files/2381378/Finance-FraudDetection-Copy1.zip)

**Comment by anshulbh** [comment]
Hi @EvanzzzZ @djarpin : I am facing that error when I use the data I referred to in the comment above. I have also attached my Jupyter notebook so you can reproduce the error.

**Comment by EvanzzzZ** [comment]
Hi @anshulbh: It looks like the notebook are training with libSVM format, but you're trying to inference it with csv data ?

**Comment by anshulbh** [comment]
Hi @djarpin : Could you please look into this? My use case is stalled because of this issue. Thanks!

**Comment by yijiezz** [comment]
Hi @anshulbh 

I run through the notebook, with training with libSVM and inference with libSVM, and didn't get any error.

The code block for csv inference has some other error complaining 
'list' object has no attribute 'as_matrix''

**Comment by rahulmca2008** [comment]
@anshulbh : Hi , I am also facing the same error : Received client error (400) from model with message "Unable to evaluate payload provided: Feature size of csv inference data 67 is not consistent with feature size of trained model 66".
Could you please suggest if you have come to know the solution. 

Regards,
Rahul

**Comment by anshulbh** [comment]
@rahulmca2008  I retrained the model on a fewer training features, removing 2-3 features which were highly imbalanced. They only had a few records of a particular category and I guess that was somehow a issue with the way Sagemaker algorithms work.  Give it a try.

**Comment by klostest** [comment]
@anshulbh I had a similar issue where I knew I was passing in the right number of features for inference but getting this same error. I noticed that it happened after I had been running two notebooks at the same time, so maybe that had something to do with it. I stopped and started the notebook instance but the error kept happening.

The next day, I deleted the entire input/output directory (`prefix`) in S3 that SageMaker had been interacting with, and started a new one from scratch. Things then worked as expected without any changes to the code in the notebook. I'm wondering if maybe there was a training job somewhere in the directory that was somehow corrupting other model training/inference. Anyways, if you can afford starting over with a new prefix directory in S3 it may work as well.

**Comment by hsl89** [comment]
Dear SageMaker Community,
             In our attempts to provide this repository with a better level of support             going forward, we’re closing issues that were opened prior to the v2 release of the SDK.             This is because we believe that over time many of the issues             posted were solved with the latest release or other recent changes to the repo.             This will help us reallocate resources towards issues that are            more likely to still be relevant today.            Some of the issues experienced now can be resolved by referencing the            v2 guide: https://sagemaker.readthedocs.io/en/stable/v2.html             In this guide, you can find simple solutions to common notebook errors,             like the renaming of parameters and classes.            If you believe your issue is still ongoing and you have updated error            messaging or other info, please re-open it, and we investigate the issue.
            Best Regards,
            AWS SageMaker Team

**Comment by george-chenvibes** [comment]
> @rahulmca2008 I retrained the model on a fewer training features, removing 2-3 features which were highly imbalanced. They only had a few records of a particular category and I guess that was somehow a issue with the way Sagemaker algorithms work. Give it a try.

Was your target variable also imbalanced?
