### ISSUE TITLE
Calling Sagemaker Endpoint from Android

### ISSUE THREAD

**Issue by murtuza07** [aws/amazon-sagemaker-examples#406]
Hi,

I have successfully deployed a sagemaker image classification model. 

How can I now call the endpoint from an Android and get the results?

And is it scalable enough to be in production? Can it handle 100's of requests each minute? And multiple requests at the same time?

And what's the rough costing per request?

Regards,
Murtuza

**Comment by djarpin** [comment]
Hi @murtuza07 - 
In general, we recommend using the AWS CLI or SDKs to invoke the endpoint when possible.  However, you can also make requests directly to the https URL.  [This forum thread](https://forums.aws.amazon.com/thread.jspa?messageID=834989&#834989) may be helpful.

SageMaker endpoints are frequently used in production environments.  The number of simultaneous requests that a single endpoint instance can handle will depend on the size of the instance, your model, and your input data.  You can deploy multiple instances behind the same endpoint though and setup autoscaling as shown in [this blog](https://aws.amazon.com/blogs/aws/auto-scaling-is-now-available-for-amazon-sagemaker/).

Details on SageMaker hosting pricing can be found on under "Model Deployment" in [this page](https://aws.amazon.com/sagemaker/pricing/).  In general, the cost is mostly instance hours, rather than per request.

Thanks.

**Comment by murtuza07** [comment]
Hi,

Thanks for the reply!!

Can you give an example of the Java Code used for invoking the endpoint? I'm not able to find an example.


Regards,
Murtuza

**Comment by djarpin** [comment]
Hi @murtuza07 -
Here's an example showing how to invoke a SageMaker endpoint using the Java AWS SDK for a spam prediction model.

```java
package com.amazonaws;

import java.nio.ByteBuffer;

import com.amazonaws.services.sagemakerruntime.AmazonSageMakerRuntime;
import com.amazonaws.services.sagemakerruntime.AmazonSageMakerRuntimeClientBuilder;
import com.amazonaws.services.sagemakerruntime.model.InvokeEndpointRequest;
import com.amazonaws.services.sagemakerruntime.model.InvokeEndpointResult;
import com.amazonaws.services.sagemakerruntime.model.AmazonSageMakerRuntimeException;

import com.amazonaws.auth.DefaultAWSCredentialsProviderChain;
import com.amazonaws.regions.Regions;
import com.amazonaws.client.builder.AwsClientBuilder.EndpointConfiguration;

import com.google.gson.Gson;
import com.google.gson.JsonArray;
import com.google.gson.JsonObject;
import com.google.gson.JsonParser;

import java.nio.charset.StandardCharsets;
import java.util.ArrayList;

public class Main {

    static String template = "" +
            "{\n" +
            "\"schema\": {\n" +
            "\"fields\": [{\n" +
                    "\"name\": \"text\",\n" +
                    "\"type\": \"string\"\n" +
            "}]\n" +
        "},\n" +
        "\"rows\": %s\n" +
        "}\n";

    static String[][] input =
        new String[][]{{"Congratulations To claim your prize call on 1212312 Unsubscribe send EURO SMS 08718727868. Over 18 only"},
                       {"Please send the TPS report as soon as possible"}};

    public static void main(String[] args) {
        AmazonSageMakerRuntime client = AmazonSageMakerRuntimeClientBuilder
                .standard()
                .withCredentials(new DefaultAWSCredentialsProviderChain())
                .build();

        InvokeEndpointRequest invokeEndpointRequest = new InvokeEndpointRequest();
        invokeEndpointRequest.setContentType("application/json");

        // Prepare the JSON payload.
        Gson gson = new Gson();
        String data = String.format(template, gson.toJson(input));

        System.out.println(data);

        try {
            invokeEndpointRequest.setBody(ByteBuffer.wrap(data.getBytes("UTF-8")));
        } catch (java.io.UnsupportedEncodingException e) {}
        invokeEndpointRequest.setEndpointName("spam-detector-2017-09-14-19-57-13");

        InvokeEndpointResult result = client.invokeEndpoint(invokeEndpointRequest);
        String body = StandardCharsets.UTF_8.decode(result.getBody()).toString();
        System.out.println("\n\n--------- Raw Results ----------");
        System.out.println(body);

        System.out.println("\n\n--------- Parsed Results ----------");
        JsonObject obj = new JsonParser().parse(body).getAsJsonObject();
        JsonArray rows = obj.get("rows").getAsJsonArray();

        for (int r = 0; r < rows.size(); r++) {
            JsonArray row = rows.get(r).getAsJsonArray();
            String text = row.get(0).getAsString();
            String isspam = row.get(row.size()-1).getAsFloat() > 0.5 ? "Spam    " : "Not Spam";
            System.out.printf("%s       %s\n", isspam, text);

        };
    }
}
```

**Comment by hsl89** [comment]
Dear SageMaker Community,
             In our attempts to provide this repository with a better level of support             going forward, we’re closing issues that were opened prior to the v2 release of the SDK.             This is because we believe that over time many of the issues             posted were solved with the latest release or other recent changes to the repo.             This will help us reallocate resources towards issues that are            more likely to still be relevant today.            Some of the issues experienced now can be resolved by referencing the            v2 guide: https://sagemaker.readthedocs.io/en/stable/v2.html             In this guide, you can find simple solutions to common notebook errors,             like the renaming of parameters and classes.            If you believe your issue is still ongoing and you have updated error            messaging or other info, please re-open it, and we investigate the issue.
            Best Regards,
            AWS SageMaker Team
