### ISSUE TITLE
[BUG] tensorflow_keras_CIFAR10 notebook not functional

### ISSUE THREAD

**Issue by tlelson** [aws/amazon-sagemaker-examples#409]
1. `utils.cifar10_download()` fails with `URLError`
2. Undefined globals. Ex: `HEIGHT, WIDTH, DEPTH, PREDICT_INPUTS`

**Comment by djarpin** [comment]
Hi @eL0ck - Thanks for the feedback.  I wasn't able to replicate either of the issues you mentioned.  Can you confirm:

1. You're running in a SageMaker notebook instance which has direct internet access enabled (i.e. "use SageMaker-provided internet access" was selected during notebook instance creation)?
2. When you're experiencing the undefined error?  Is it coming through in the CloudWatch logs during `estimator.fit(inputs)`?  Calling the `keras_model_fn()` defined within the notebook itself won't actually work.  It's there for illustrative purposes to detail the function needed for `cifar10_cnn.py`.

Thanks.

**Comment by tle-kablamo** [comment]
Hi @djarpin, thanks for your reply.  I blew it away and re-created it from the example and it worked fine end-to-end.
Thanks, it's a great example. Much appreciated.

**Comment by eL0ck** [comment]
Thanks @djarpin, after copying it again I found it worked as expected.  Great example, much appreciated.

**Comment by seanpmorgan** [comment]
Closing.
