### ISSUE TITLE
scikit_bring_your_own - reference to local_test folder

### ISSUE THREAD

**Issue by bogdanlalu** [aws/amazon-sagemaker-examples#411]
In _**scikit_bring_your_own.ipnb**_ in the section called _The parts of the sample container_ there is a file structure displayed and details below it (bullet points). 
In the bullet points it is mentioned about a _**local_test**_ folder but that folder is not displayed in the file structure above.
Where should that folder sit?

![image](https://user-images.githubusercontent.com/16867980/45622195-0e645400-ba7b-11e8-9141-52bc8b93ed38.png)

**Comment by djarpin** [comment]
Thanks for pointing this out, @bogdanlalu .  In this example, the `local_test` directory sits at the first level within the `container` directory.  I should note that a `local_test` directory isn't required to bring your own SageMaker container.  The file structure laid out in the scikit_bring_your_own example is more of a good practice for organization, rather than something that needs to be adhered to.

**Comment by hsl89** [comment]
Dear SageMaker Community,
             In our attempts to provide this repository with a better level of support             going forward, we’re closing issues that were opened prior to the v2 release of the SDK.             This is because we believe that over time many of the issues             posted were solved with the latest release or other recent changes to the repo.             This will help us reallocate resources towards issues that are            more likely to still be relevant today.            Some of the issues experienced now can be resolved by referencing the            v2 guide: https://sagemaker.readthedocs.io/en/stable/v2.html             In this guide, you can find simple solutions to common notebook errors,             like the renaming of parameters and classes.            If you believe your issue is still ongoing and you have updated error            messaging or other info, please re-open it, and we investigate the issue.
            Best Regards,
            AWS SageMaker Team
