### ISSUE TITLE
paths in train container

### ISSUE THREAD

**Issue by cnasri** [aws/amazon-sagemaker-examples#418]
Hello, 

I try to use sagemaker (i bring my own sickitlearn code)
I see in the rain file of the container repository there are these 3 paths : 
`input_path = prefix + 'input/data'`
```
output_path = os.path.join(prefix, 'output')
model_path = os.path.join(prefix, 'model')
```
and 

`# File mode, the input files are copied to the directory specified here.`
```
channel_name='training'
training_path = os.path.join(input_path, channel_name)
```

My question is how can I choose this path. Can i modify 'training' by 'train" for example?

**Comment by djarpin** [comment]
Hi @cnasri - "/opt/ml/input/data/" is fixed.  But, you can control the name of the channel directory (e.g. "training" vs "train").  SageMaker creates this directory automatically for you based on the channel(s) specified when you create your training job (more details in the [documentation](https://docs.aws.amazon.com/sagemaker/latest/dg/API_Channel.html#SageMaker-Type-Channel-ChannelName)).  If you're using the SageMaker Python SDK, the channel defaults to "training", but you can explicitly change it (and create multiple channels) using syntax like this:

```python
tree.fit({'<channel1_name>': data_location1,
          '<channel2_name>': data_location2})
```

**Comment by hsl89** [comment]
Dear SageMaker Community,
             In our attempts to provide this repository with a better level of support             going forward, we’re closing issues that were opened prior to the v2 release of the SDK.             This is because we believe that over time many of the issues             posted were solved with the latest release or other recent changes to the repo.             This will help us reallocate resources towards issues that are            more likely to still be relevant today.            Some of the issues experienced now can be resolved by referencing the            v2 guide: https://sagemaker.readthedocs.io/en/stable/v2.html             In this guide, you can find simple solutions to common notebook errors,             like the renaming of parameters and classes.            If you believe your issue is still ongoing and you have updated error            messaging or other info, please re-open it, and we investigate the issue.
            Best Regards,
            AWS SageMaker Team
