### ISSUE TITLE
20newsgroups Error on Tokenize and Lemmatize Step

### ISSUE THREAD

**Issue by patronical** [aws/amazon-sagemaker-examples#431]
ImportError: libncurses.so.6: cannot open shared object file:

**Comment by ChoiByungWook** [comment]
@patronical,

Can you please point me to the specific example that causes this problem?

**Comment by patronical** [comment]
I am working off this tutorial : https://aws.amazon.com/blogs/machine-learning/introduction-to-the-amazon-sagemaker-neural-topic-model/ 

I am stuck on this section: 
!pip install nltk
import nltk

I can install nltk, but I get this import error : 
Requirement already satisfied: nltk in /home/ec2-user/anaconda3/envs/mxnet_p36/lib/python3.6/site-packages (3.3)
Requirement already satisfied: six in /home/ec2-user/anaconda3/envs/mxnet_p36/lib/python3.6/site-packages (from nltk) (1.11.0)
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-23-694f9aadc4c8> in <module>()
      1 get_ipython().system('pip install nltk')
----> 2 import nltk
      3 #nltk.download('punkt')

~/anaconda3/envs/mxnet_p36/lib/python3.6/site-packages/nltk/__init__.py in <module>()
    135 from nltk.translate import *
    136 from nltk.sem import *
--> 137 from nltk.stem import *
    138 
    139 # Packages which can be lazily imported

~/anaconda3/envs/mxnet_p36/lib/python3.6/site-packages/nltk/stem/__init__.py in <module>()
     27 from nltk.stem.isri import ISRIStemmer
     28 from nltk.stem.porter import PorterStemmer
---> 29 from nltk.stem.snowball import SnowballStemmer
     30 from nltk.stem.wordnet import WordNetLemmatizer
     31 from nltk.stem.rslp import RSLPStemmer

~/anaconda3/envs/mxnet_p36/lib/python3.6/site-packages/nltk/stem/snowball.py in <module>()
     30 
     31 from nltk import compat
---> 32 from nltk.corpus import stopwords
     33 from nltk.stem import porter
     34 from nltk.stem.util import suffix_replace, prefix_replace

~/anaconda3/envs/mxnet_p36/lib/python3.6/site-packages/nltk/corpus/__init__.py in <module>()
     64 from nltk.tokenize import RegexpTokenizer
     65 from nltk.corpus.util import LazyCorpusLoader
---> 66 from nltk.corpus.reader import *
     67 
     68 abc = LazyCorpusLoader(

~/anaconda3/envs/mxnet_p36/lib/python3.6/site-packages/nltk/corpus/reader/__init__.py in <module>()
    103 from nltk.corpus.reader.categorized_sents import *
    104 from nltk.corpus.reader.comparative_sents import *
--> 105 from nltk.corpus.reader.panlex_lite import *
    106 
    107 # Make sure that nltk.corpus.reader.bracket_parse gives the module, not

~/anaconda3/envs/mxnet_p36/lib/python3.6/site-packages/nltk/corpus/reader/panlex_lite.py in <module>()
     13 
     14 import os
---> 15 import sqlite3
     16 
     17 from nltk.corpus.reader.api import CorpusReader

~/anaconda3/envs/mxnet_p36/lib/python3.6/sqlite3/__init__.py in <module>()
     21 # 3. This notice may not be removed or altered from any source distribution.
     22 
---> 23 from sqlite3.dbapi2 import *

~/anaconda3/envs/mxnet_p36/lib/python3.6/sqlite3/dbapi2.py in <module>()
     25 import collections.abc
     26 
---> 27 from _sqlite3 import *
     28 
     29 paramstyle = "qmark"

ImportError: libncurses.so.6: cannot open shared object file: No such file or directory

**Comment by patronical** [comment]
running this on an ml.t2.xlarge intance, out of Oregon.
Using the "ntm_20newsgroups_topic_model" template.
Notebook is labeled as conda_mxnet_p36.
notebook works normally through block:
data[10:13]  this reveals the article samples.

added block because it complained of a down-rev:
!pip install --upgrade pip

added block because it complained these weren't installed:
!pip install fasteners
!pip install importlib2
!pip install mxnet
!pip install onnx-mxnet
!pip install msgpack

Added an additional block because nltk isn't importing:
!sudo pip install --install-option="--target=/home/ec2-user/anaconda3/envs/mxnet_p36/lib/python3.6/site-packages" nltk

The reply from that block is:
Requirement already satisfied: nltk in /usr/local/lib/python2.7/site-packages
Requirement already satisfied: six in /usr/lib/python2.7/dist-packages (from nltk)

Added block:
import sys
sys.path.append('/home/ec2-user/anaconda3/envs/mxnet_p36/lib/python2.7/site-packages')
sys.path

output of system path:
['',
 '/home/ec2-user/src/cntk/bindings/python',
 '/home/ec2-user/anaconda3/envs/mxnet_p36/lib/python36.zip',
 '/home/ec2-user/anaconda3/envs/mxnet_p36/lib/python3.6',
 '/home/ec2-user/anaconda3/envs/mxnet_p36/lib/python3.6/lib-dynload',
 '/home/ec2-user/anaconda3/envs/mxnet_p36/lib/python3.6/site-packages',
 '/home/ec2-user/anaconda3/envs/mxnet_p36/lib/python3.6/site-packages/IPython/extensions',
 '/home/ec2-user/.ipython',
 '/home/ec2-user/anaconda3/envs/mxnet_p36/lib/python2.7/site-packages']

finally run block alone to test if nltk imports, (it doesn't):
import nltk

returns big output of import errors culminating in 
ImportError: libncurses.so.6: cannot open shared object file: No such file or directory

Please help with this situation.  Thanks!

**Comment by patronical** [comment]
Hi Dan,
I just updated the thread with more information.
This is a sagemaker sample - using prefab template.
running this on an ml.t2.xlarge intance, out of Oregon.
Using the "ntm_20newsgroups_topic_model" template.
Notebook is labeled as conda_mxnet_p36.
notebook works normally through block:
data[10:13] this reveals the article samples.
......
Thanks, Patrick

**Comment by ChoiByungWook** [comment]
@patronical,

Thank you so much for all the updates.

It seems there is a dependency issue. We are currently working towards a solution.

As a workaround, I believe upgrading sqlite and restarting the kernel should do it.

Feel free to run this command within a cell in the notebook.
!conda upgrade -y sqlite

Then restart the kernel and run all cells.

If you run into a problem with nltk stating that module 'nltk' has no attribute 'data'. You will have to do a...
1. pip uninstall nltk
2. pip install --upgrade nltk

I apologize for the experience. Please let me know if these workarounds work for you.

**Comment by patronical** [comment]
Thank you for the expert help and prompt response.
I was able to use this workaround successfully.

The only small issue I ran into seems to be related to mxnet.
During the wordcloud installation was some mxnet warnings:

mxnet-model-server 0.3 requires fasteners, which is not
installed.mxnet-model-server 0.3 requires importlib2, which is not
installed.mxnet-model-server 0.3 requires mxnet>=1.1, which is not
installed.mxnet-model-server 0.3 requires onnx-mxnet>=0.4.2, which is
not installed.distributed 1.21.8 requires msgpack, which is not
installed.


These look similar to the struggles I had earlier.

However, I was able to run the wordclouds with excellent results!


Gratefully, Patrick

**Comment by patronical** [comment]
This expert workaround worked successfully, I needed the sqlite upgrade only.
Thank you for the expert help and prompt response!

**Comment by ChoiByungWook** [comment]
Awesome!

Again, I apologize for this experience. We are working towards a fix, so that the workaround isn't needed.

**Comment by hsl89** [comment]
Dear SageMaker Community,
             In our attempts to provide this repository with a better level of support             going forward, we’re closing issues that were opened prior to the v2 release of the SDK.             This is because we believe that over time many of the issues             posted were solved with the latest release or other recent changes to the repo.             This will help us reallocate resources towards issues that are            more likely to still be relevant today.            Some of the issues experienced now can be resolved by referencing the            v2 guide: https://sagemaker.readthedocs.io/en/stable/v2.html             In this guide, you can find simple solutions to common notebook errors,             like the renaming of parameters and classes.            If you believe your issue is still ongoing and you have updated error            messaging or other info, please re-open it, and we investigate the issue.
            Best Regards,
            AWS SageMaker Team
