### ISSUE TITLE
[Example Request] SageMaker deployable models using quantized GGML format

### ISSUE THREAD

**Issue by billcai** [aws/amazon-sagemaker-examples#4388]
**Describe the use case example you want to see**
[GGML](https://github.com/ggerganov/llama.cpp) is a popular library used for LLM inference and supports multiple open-source LLM architectures, including Llama V2. Besides running on CPU/GPU, GGML has a quantization format that reduces memory usage, thus enabling LLMs to be deployed with more cost-effective instance types.

**How would this example be used? Please describe.**
I have a working version of a Docker image that implements the web server endpoints required by SageMaker, and have specifically tested this on Llama V2 13b chat and Llama V2 70b chat with g4dn.xlarge and g4dn.12xlarge instance types respectively. The example is designed to be configurable for other model architectures as well, i.e. you can package any other GGML-format weights into a .tar.gz archive, upload it to S3, and use it as a model artifact.

This example would be used by customers who would like to use instance types with more constrained resources, especially for deployment in AWS regions without certain instance types (e.g. g5.48xlarge or p4d.24xlarge).

**Describe which SageMaker services are involved**
SageMaker Real-Time Inference

**Describe what other services (other than SageMaker) are involved***
S3

**Describe which dataset could be used. Provide its location in s3://sagemaker-sample-files or another source.**
None

**Comment by MoaazZaki** [comment]
Hey @billcai, can you please share the example ? so curios.

**Comment by zf0x00** [comment]
@billcai nice

**Comment by billcai** [comment]
Will be closing this issue and not merging.

**Comment by ismaelc** [comment]
Any reasons why this was not merged? 

Also any plans for gguf?

**Comment by alifatmi** [comment]
@billcai i have follow your `[notebook](https://github.com/billcai/amazon-sagemaker-examples/blob/main/inference/generativeai/ggml-quantized-llm/ggml-quantized-llama-2-7b-chat-on-SageMaker.ipynb)` for 7B model  done all the steps but last in deployment it give this error i have get it form cloudwatch logs 
"error loading model: llama_model_loader: failed to load model from /opt/ml/model/llama-2-7b-chat.ggmlv3.q4_K_M.bin"
