### ISSUE TITLE
Keras model won't run

### ISSUE THREAD

**Issue by ajdinm** [aws/amazon-sagemaker-examples#460]
I tried to recreate tensorflow_keras_cifar10 example with my own keras model, but I'm not able to get valid training job.  I'm failing to find anything relevant online, and also I'm out of ideas.
Below is my code for `keras_model_fn`

```
def keras_model_fn(hyperparameters):
    model = Sequential()
    for layer in configs['model']['layers']:
        neurons = layer['neurons'] if 'neurons' in layer else None
        dropout_rate = layer['rate'] if 'rate' in layer else None
        activation = layer['activation'] if 'activation' in layer else None
        return_seq = layer['return_seq'] if 'return_seq' in layer else None
        input_timesteps = configs['data']['sequence_length'] if 'sequence_length' in configs['data'] else None
        input_dim = sum([feature['dim'] for feature in configs['data']
                         ['features']]) if 'input_dim' in layer else None
        recurrent_dropout = layer['recurrent_dropout'] if 'recurrent_dropout' in layer else 0
        name = layer["name"]

        if layer['type'] == 'dense':
            if input_dim is None:
                model.add(Dense(neurons, activation=activation, name=name))
            else:
                model.add(Dense(neurons, activation=activation,
                                input_shape=(input_dim,), name=name))
        if layer['type'] == 'lstm':
            model.add(LSTM(neurons, input_shape=(input_timesteps,
                                                 input_dim), return_sequences=return_seq, name=name))
        if layer['type'] == 'gru':
            model.add(GRU(neurons, input_shape=(input_timesteps,
                                                input_dim,), return_sequences=return_seq, name=name))
        if layer['type'] == 'dropout':
            model.add(Dropout(dropout_rate, name=name))
    model.compile(
        loss=configs['model']['loss'],
        optimizer=configs['model']['optimizer'],
        metrics=['accuracy']
    )
    return model
```

with  following layers:
```
		"layers": [
			{
				"type": "gru",
				"neurons": 10,
				"input_dim": True,
				"return_seq": False,
				"name": "inputs"
			},
			{
				"type": "dropout",
				"rate": 0.1,
				"name": "dropout"
			},
			{
				"type": "dense",
				"neurons": 1,
				"activation": "sigmoid",
				"name": "output"
			}
		]
```
On both local and cloud runs i get the following output in terminal:

```
algo-1-DSGJQ_1_3dfc6e418ee3 | 2018-11-08 15:24:21,472 INFO - tensorflow - Calling model_fn.
tmp1kktnt_algo-1-DSGJQ_1_3dfc6e418ee3 exited with code 137
```

One of things i've tried to do is use use custom keras version (2.2.2), which gave me the following error: 
```
Expected model argument to be Model, got keras.engine.sequential.Sequential
```

Finally, I tried to cast keras Sequential model back to tensorflow (on both keras version) and this yielded the following message:

```
algo-1-5WZJ6_1_b19d193b5113 |   File "/usr/local/lib/python2.7/dist-packages/tf_container/trainer.py", line 69, in train
algo-1-5WZJ6_1_b19d193b5113 |     estimator = self._build_estimator(run_config=run_config)
algo-1-5WZJ6_1_b19d193b5113 |   File "/usr/local/lib/python2.7/dist-packages/tf_container/trainer.py", line 96, in _build_estimator
algo-1-5WZJ6_1_b19d193b5113 |     return tf.keras.estimator.model_to_estimator(keras_model=model, config=run_config)
algo-1-5WZJ6_1_b19d193b5113 |   File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/estimator/keras.py", line 407, in model_to_estimator
algo-1-5WZJ6_1_b19d193b5113 |     'The given keras model has not been compiled yet. '
algo-1-5WZJ6_1_b19d193b5113 | ValueError: The given keras model has not been compiled yet. Please compile the model with `model.compile()` before calling `model_to_estimator()`.
```

even though i do compile model:
```
def convert_to_tf(keras_model): # keras_model is compiled before being sent to this function
    tfCompatibleMod = Model(keras_model) 
    tfCompatibleMod.compile(loss=configs['model']['loss'],
                            optimizer=configs['model']['optimizer'])
    estimator = model_to_estimator(keras_model=tfCompatibleMod)
    return estimator
```

**Comment by ChoiByungWook** [comment]
Hello @ajdinm,

I apologize for the late response.

Are you able to train your model with keras outside of SageMaker?

If so, there was a release with using TensorFlow on SageMaker through a new experience called [script mode](https://github.com/aws/sagemaker-python-sdk/tree/master/src/sagemaker/tensorflow#preparing-a-script-mode-training-script).

Please let me know if there is anything I can clarify.

**Comment by hsl89** [comment]
Dear SageMaker Community,
             In our attempts to provide this repository with a better level of support             going forward, we’re closing issues that were opened prior to the v2 release of the SDK.             This is because we believe that over time many of the issues             posted were solved with the latest release or other recent changes to the repo.             This will help us reallocate resources towards issues that are            more likely to still be relevant today.            Some of the issues experienced now can be resolved by referencing the            v2 guide: https://sagemaker.readthedocs.io/en/stable/v2.html             In this guide, you can find simple solutions to common notebook errors,             like the renaming of parameters and classes.            If you believe your issue is still ongoing and you have updated error            messaging or other info, please re-open it, and we investigate the issue.
            Best Regards,
            AWS SageMaker Team
