### ISSUE TITLE
Bug: HPO Boolean env always return True

### ISSUE THREAD

**Issue by ronteo** [aws/amazon-sagemaker-examples#466]
Calling 

object_type(value) on a bool will always return True.
e.g bool("False") will return True instead of false.

One solution is the following

 try:          
            value = self.hyperparameters_dict[key]
            
            #Ron fixing a bug with bool since bool("False") == True
            if(object_type==bool):
                valid = ["true", "false"]
                if(value.lower() not in valid):
                    raise ValueError("%s is not a valid bool value" % value)
                return value.lower() == "true"
            return object_type(value) if object_type else value
        except KeyError:
            return default

--------------------------------------------------------------------
https://github.com/awslabs/amazon-sagemaker-examples/blob/master/hyperparameter_tuning/keras_bring_your_own/trainer/environment.py

def get(self, key, default=None, object_type=None):
        """Has the same functionality of `dict.get`. Allows casting of the values using the additional attribute
        `object_type`:
        Args:
            key: hyperparameter name
            default: default hyperparameter value
            object_type: type that the hyperparameter wil be casted to.
        Returns:
        """
        try:
            value = self.hyperparameters_dict[key]
            return object_type(value) if object_type else value
        except KeyError:
            return default

**Comment by hsl89** [comment]
Dear SageMaker Community,
             In our attempts to provide this repository with a better level of support             going forward, we’re closing issues that were opened prior to the v2 release of the SDK.             This is because we believe that over time many of the issues             posted were solved with the latest release or other recent changes to the repo.             This will help us reallocate resources towards issues that are            more likely to still be relevant today.            Some of the issues experienced now can be resolved by referencing the            v2 guide: https://sagemaker.readthedocs.io/en/stable/v2.html             In this guide, you can find simple solutions to common notebook errors,             like the renaming of parameters and classes.            If you believe your issue is still ongoing and you have updated error            messaging or other info, please re-open it, and we investigate the issue.
            Best Regards,
            AWS SageMaker Team
