### ISSUE TITLE
sagemaker response is a bytearray, how to convert to json in Java

### ISSUE THREAD

**Issue by macsharma** [aws/amazon-sagemaker-examples#467]
I am using a seq2seq for multiple language translation. My sagemaker pytorch model returns json object.

In python SDK the bytearray (response from sagemaker) can be converted to json simply by using json.loads(respose). Can the same be done using Java? One idea is to convert it to string and then pass it to JSONobject, but it fails in the following scenario.

For seq2seq for various languages, the bytestring output (response) when converted to json.loads(response) gives the correct sentence with correct decoding of bytestring in python. However, there is no json.loads() in java and hence, converting bytestring to string and then to JSON is  not able to decode all the characters.
Any help in this scenario will be appreciated.

**Comment by ChoiByungWook** [comment]
Hello @macsharma,

I apologize for the late response.

I am not too sure what the best answer is as this is not my expertise, especially with two languages getting involved, however have you considered using a JSON library such as [GSON](https://github.com/google/gson/blob/master/UserGuide.md#object-examples) or [json-simple](https://code.google.com/archive/p/json-simple/)? Those libraries might have functions that can handle converting the bytestring to JSON.

Please let me know if there is anything I can clarify.

Thanks!

**Comment by hsl89** [comment]
Dear SageMaker Community,
             In our attempts to provide this repository with a better level of support             going forward, we’re closing issues that were opened prior to the v2 release of the SDK.             This is because we believe that over time many of the issues             posted were solved with the latest release or other recent changes to the repo.             This will help us reallocate resources towards issues that are            more likely to still be relevant today.            Some of the issues experienced now can be resolved by referencing the            v2 guide: https://sagemaker.readthedocs.io/en/stable/v2.html             In this guide, you can find simple solutions to common notebook errors,             like the renaming of parameters and classes.            If you believe your issue is still ongoing and you have updated error            messaging or other info, please re-open it, and we investigate the issue.
            Best Regards,
            AWS SageMaker Team
