### ISSUE TITLE
XGBoost predict_proba is not available while loading the model locally

### ISSUE THREAD

**Issue by sahithyaswaminathan** [aws/amazon-sagemaker-examples#479]
I have trained the XGboost model with objective:softprob and the trained model is stored in S3. But, when I try to load the saved model and use it for prediction, the object contains only "predict" attribute and not "predict_proba". Is there any standard method to get probability distribution from saved model than just the value. Also, please be noted that, I donot want to create sagemaker endpoint. I have used Sagemaker's inbuilt container for training

**Comment by richardonichol** [comment]
I also have this problem. Not returning probabilities cripples Sagemaker XGB in terms of its business value. It make it much harder to use it in complex ensembles for example

**Comment by richardonichol** [comment]
I was trying to use multi:softprob predict (and predict_proba) with batch mode rather than an endpoint and could not get it to work as expected. I also had other problems with batch mode so I have decided to just stick with an endpoint for now. multi:softprob predict() does seem to work as expected in that scenario.

**Comment by hsl89** [comment]
Dear SageMaker Community,
             In our attempts to provide this repository with a better level of support             going forward, we’re closing issues that were opened prior to the v2 release of the SDK.             This is because we believe that over time many of the issues             posted were solved with the latest release or other recent changes to the repo.             This will help us reallocate resources towards issues that are            more likely to still be relevant today.            Some of the issues experienced now can be resolved by referencing the            v2 guide: https://sagemaker.readthedocs.io/en/stable/v2.html             In this guide, you can find simple solutions to common notebook errors,             like the renaming of parameters and classes.            If you believe your issue is still ongoing and you have updated error            messaging or other info, please re-open it, and we investigate the issue.
            Best Regards,
            AWS SageMaker Team
