### ISSUE TITLE
How to load a model file, and host the endpoint in object_detection_pascalvoc_coco/object_detection_recordio_format.ipynb

### ISSUE THREAD

**Issue by jlwebuser** [aws/amazon-sagemaker-examples#480]
I followed the example all the way through the training step. I actually ran the training for several epochs and let it complete. It stored the model.tar.gz in the S3 output directory. 
Then I shut down. Now I want to resume with the example, host the model and  then run inference. Unless I re-train, the od_model will not be initialized.  Think I need something like the following to load and, and deploy the model but I am not clear what entry_point I should use.  Can someone please clarify. Thanks, 

```
import sagemaker
from sagemaker.mxnet.model import MXNetModel

sagemaker_session = sagemaker.Session()

model_file = "s3://deeplens-sagemaker-e1650c53-88e7-4905-84fb-c7eef9be563f/mydata/output/object-detection-2018-11-16-02-25-19-589/output/model.tar.gz" 
model_data = sagemaker.session.s3_input( model_file, distribution='FullyReplicated', content_type='application/x-sagemaker-model', s3_data_type='S3Prefix')

sagemaker_model = MXNetModel(model_data = 's3://' + sagemaker_session.default_bucket() + '/model/model.tar.gz', role = role, entry_point = '')
predictor = sagemaker_model.deploy(initial_instance_count=1, instance_type='ml.m4.xlarge')

#now i read in the images and send to the predictor
...
response = predictor.predict(data)

```

**Comment by ChoiByungWook** [comment]
Hello @jlwebuser,

I apologize for the late response. 

The entry point is a python file that contains functions that our SageMaker deep learning framework containers will consume and invoke for handling inferences. By default, MXNet will have default functions for handling [inferences](https://github.com/aws/sagemaker-mxnet-container/blob/master/src/sagemaker_mxnet_container/serving.py#L201) and loading the [model](https://github.com/aws/sagemaker-mxnet-container/blob/master/src/sagemaker_mxnet_container/serving.py#L43).

Seeing as you are using the predefined SageMaker MXNet container, you will need to provide a python file which handles your inference and model loading properly. If you are satisfied with the default functions, then please provide an empty python file, whose name corresponds to the entry point parameter.

Please let me know if there is anything I can clarify.

Thanks!

**Comment by LeaoGabriel** [comment]
The F. Problem is... what is the F. Python file that corresponds to the F. entry point?

**Comment by hsl89** [comment]
Dear SageMaker Community,
             In our attempts to provide this repository with a better level of support             going forward, we’re closing issues that were opened prior to the v2 release of the SDK.             This is because we believe that over time many of the issues             posted were solved with the latest release or other recent changes to the repo.             This will help us reallocate resources towards issues that are            more likely to still be relevant today.            Some of the issues experienced now can be resolved by referencing the            v2 guide: https://sagemaker.readthedocs.io/en/stable/v2.html             In this guide, you can find simple solutions to common notebook errors,             like the renaming of parameters and classes.            If you believe your issue is still ongoing and you have updated error            messaging or other info, please re-open it, and we investigate the issue.
            Best Regards,
            AWS SageMaker Team
