### ISSUE TITLE
What to do for TensorFlow BYOM when model is defined across many files?

### ISSUE THREAD

**Issue by mshseek** [aws/amazon-sagemaker-examples#487]
I am trying to deploy a trained TensorFlow estimator using the [Iris BYOM notebook ](https://github.com/awslabs/amazon-sagemaker-examples/blob/master/advanced_functionality/tensorflow_iris_byom/tensorflow_BYOM_iris.ipynb)as a guide.

I have a question about these lines:

```
from sagemaker.tensorflow.model import TensorFlowModel
sagemaker_model = TensorFlowModel(model_data = 's3://' + sagemaker_session.default_bucket() + '/model/model.tar.gz',
                                  role = role,
                                  entry_point = 'iris_dnn_classifier.py')
```

In my case, my model is defined across multiple files so I am unsure of what to put in the entry point.

For example, my script that defines the input functions, serving function and model is stored in a script named `amz_sagemaker.py` but that script itself is importing another script named `modelling`. So, if I put `entry_point='amz_sagemaker.py'` and proceed to deploy using:

```
predictor = sagemaker_model.deploy(initial_instance_count=1,
                                          instance_type='ml.m4.xlarge')
```
the deployment will fail with the message:

`ValueError: Error hosting endpoint bert-using-tf-model: Failed Reason:  The primary container for production variant AllTraffic did not pass the ping health check. Please check CloudWatch logs for this endpoint.`

Looking at the CloudWatch logs, the following line appears:

`ImportError: No module named modeling`

Does `TensorFlowModel` have something like a `source_dir` so that it will automatically upload all the source files that `entry_point` depends on? If not, what is the recommend way to get this model deployed on Sagemaker?

**Comment by seanpmorgan** [comment]
Closing. Pleast let us know if there are still issues with the proposed solutions
