### ISSUE TITLE
Data file ID for the US Census by counties

### ISSUE THREAD

**Issue by iPrithvi** [aws/amazon-sagemaker-examples#510]
Hi Team,

Can you give us the ID of the data file that you used in the example - https://github.com/awslabs/amazon-sagemaker-examples/blob/master/introduction_to_applying_machine_learning/US-census_population_segmentation_PCA_Kmeans/sagemaker-countycensusclustering.ipynb

I tried to look at the link provided - https://factfinder.census.gov/faces/nav/jsf/pages/index.xhtml
But there are a lot of different files there.

Best Regards,
iPrithvi.

**Comment by pdasamzn** [comment]
Hello iPrithvi,

The dataset was originally obtained from this link: https://www.kaggle.com/muonneutrino/us-census-demographic-data/home which has more explanation on where the data originated from. 

Thanks!

**Comment by hsl89** [comment]
Dear SageMaker Community,
             In our attempts to provide this repository with a better level of support             going forward, we’re closing issues that were opened prior to the v2 release of the SDK.             This is because we believe that over time many of the issues             posted were solved with the latest release or other recent changes to the repo.             This will help us reallocate resources towards issues that are            more likely to still be relevant today.            Some of the issues experienced now can be resolved by referencing the            v2 guide: https://sagemaker.readthedocs.io/en/stable/v2.html             In this guide, you can find simple solutions to common notebook errors,             like the renaming of parameters and classes.            If you believe your issue is still ongoing and you have updated error            messaging or other info, please re-open it, and we investigate the issue.
            Best Regards,
            AWS SageMaker Team
