### ISSUE TITLE
Loosing Tensorflow Graph in custom flask endpoint | Randomly working and then stop

### ISSUE THREAD

**Issue by jaiswalvineet** [aws/amazon-sagemaker-examples#520]
Hi there, 

I have created a custom tensorflow container which save the final model in pickle file, now to serve I use Flask application as mentioned in custom sci-kit example i.e. read pickle file from location and finally serve it as endpoint.

This application is working fine but strangely after random 4-5 calls, its showing tensorflow graph reference error

ValueError: Tensor("TensorSliceDataset:0", shape=(), dtype=variant) must be from the same graph as Tensor("Iterator:0", shape=(), dtype=resource).

Even if don't do anything like 5 mins then again it works without any change and after few calls its again giving same error, this application working all fine on local.

Seems its Sagemaker problem, can you please help me in this regard, I tried everything I know but still no luck.
  
Thanks in Advance

**Comment by hsl89** [comment]
Dear SageMaker Community,
             In our attempts to provide this repository with a better level of support             going forward, we’re closing issues that were opened prior to the v2 release of the SDK.             This is because we believe that over time many of the issues             posted were solved with the latest release or other recent changes to the repo.             This will help us reallocate resources towards issues that are            more likely to still be relevant today.            Some of the issues experienced now can be resolved by referencing the            v2 guide: https://sagemaker.readthedocs.io/en/stable/v2.html             In this guide, you can find simple solutions to common notebook errors,             like the renaming of parameters and classes.            If you believe your issue is still ongoing and you have updated error            messaging or other info, please re-open it, and we investigate the issue.
            Best Regards,
            AWS SageMaker Team
