### ISSUE TITLE
How to use GPU instances with my Bring Your Own PyTorch container

### ISSUE THREAD

**Issue by aybchan** [aws/amazon-sagemaker-examples#522]
I'm trying to make use of GPUs for training a network in PyTorch. I have a 'Bring Your Own' container.

If I use the AWS provided containers, I can just look for the SM environment variables such as SM_NUM_GPUS as in [here](https://github.com/awslabs/amazon-sagemaker-examples/blob/d73e8cb736945fd589e30cee676cdf3b31d583ea/advanced_functionality/pytorch_extending_our_containers/container/cifar10/cifar10.py#L167) to configure my code for distributed compute.

I'm building my own container with Ubuntu as a base, and when I log the environment variables I don't get these SM variables. So how do I get these variables? Any pointers would be appreciated.

**Comment by ChoiByungWook** [comment]
These SM variables are set by our common container framework package.
https://github.com/aws/sagemaker-containers

How each of the different values get populated can be different. They can come from...

1. Hyperparameters sent to the SageMaker job. For [example](https://github.com/aws/sagemaker-containers/blob/master/src/sagemaker_containers/_env.py#L644).
2. Commands used to find out information on the local running instance. For example [SM_NUM_GPUS](https://github.com/aws/sagemaker-containers/blob/master/src/sagemaker_containers/_env.py#L286).
3. Environment variables sent to the container by SageMaker. https://docs.aws.amazon.com/sagemaker/latest/dg/API_ContainerDefinition.html#SageMaker-Type-ContainerDefinition-Environment

How the environment variables are written during training are displayed in the code snippets below:

- [Code that determines which values to set as environment variables.](https://github.com/aws/sagemaker-containers/blob/master/src/sagemaker_containers/_env.py#L620)
- [Code path that invokes code to set environment variables](https://github.com/aws/sagemaker-containers/blob/3bdea78df0e443ddd8986c5364649f87f4b2419c/src/sagemaker_containers/entry_point.py#L73)
- [Code that sets the environment variables](https://github.com/aws/sagemaker-containers/blob/master/src/sagemaker_containers/_env.py#L900)

Please let me know if there is anything I can clarify.

Thanks!

**Comment by aybchan** [comment]
Sorry I still have no idea how to actually use the sagemaker_container package to populate environment variables (such as SM_NUM_GPUS) so that my train script can access them. I have now included sagemaker_container in my Docker image packages, and in my train script I have added:

    import sagemaker_container
    ...

    if __name__ == '__main__':
        ...
        env = sagemaker_container.training_env()
        print('env', env)

This will only print 'env' in the logs.

**Comment by ChoiByungWook** [comment]
@aybchan,

Not a problem.

I believe most of this can be confusing without having worked with it before.

Essentially, the code that writes your hyperparameters and other configuration values to environment variables hasn't been invoked.

To get and set the environment variables please try the following:

```
env_vars = env.to_env_vars()
env.write_env_vars(env_vars)
```

With that, you should have access to some of the environment variables. If you are interested in seeing which environment variables are available please print the env_vars.

Please let me know if there is anything I can clarify.

Thanks!

**Comment by ChoiByungWook** [comment]
I think this issue would be useful and helpful to those in the https://github.com/aws/sagemaker-containers

If you feel that there are still more questions in regards to sagemaker-containers, please raise an issue there.

https://github.com/aws/sagemaker-containers/issues/new

**Comment by hsl89** [comment]
Dear SageMaker Community,
             In our attempts to provide this repository with a better level of support             going forward, we’re closing issues that were opened prior to the v2 release of the SDK.             This is because we believe that over time many of the issues             posted were solved with the latest release or other recent changes to the repo.             This will help us reallocate resources towards issues that are            more likely to still be relevant today.            Some of the issues experienced now can be resolved by referencing the            v2 guide: https://sagemaker.readthedocs.io/en/stable/v2.html             In this guide, you can find simple solutions to common notebook errors,             like the renaming of parameters and classes.            If you believe your issue is still ongoing and you have updated error            messaging or other info, please re-open it, and we investigate the issue.
            Best Regards,
            AWS SageMaker Team
