### ISSUE TITLE
tensorflow_bring_your_own out of date documentation.

### ISSUE THREAD

**Issue by ryanpeach** [aws/amazon-sagemaker-examples#527]
Hi,

The tensorflow_bring_your_own example is very much out of date. It should show an example using the script mode sdk, and without the need for a custom docker container, perhaps even with a pipe mode implementation. I think it should also include references on how to use a 'requirements.txt' file in script mode, how to deploy and do batch transform, etc. Maybe also a mention of the fact you can use keras in the container (which btw also works with pipe mode dataset, maybe an example of that would be good as well).

I have parsed these details from many such documentation files scattered in announcements and around the web. But a central location for how to flexibly do whatever you want without custom docker files or strict code templates would be nice.

**Comment by austinmw** [comment]
@ryanpeach if you have an example of how to use Pipe mode in conjunction with a BYO container and tensorflow.keras model would you mind sharing? :)

**Comment by icywang86rui** [comment]
Hi @ryanpeach 
The purpose of this bring_your_own sample is to show how to build containers which are compatible for SageMaker. This example is using TensorFlow but with BYO it's possible to use any ML frameworks or libraries. For using our official script mode TensorFlow containers we do have couple sample notebook here:

* [tensorflow_script_mode_using_shell_commands](https://github.com/awslabs/amazon-sagemaker-examples/blob/master/sagemaker-python-sdk/tensorflow_script_mode_using_shell_commands/tensorflow_script_mode_using_shell_commands.ipynb)
* [tensorflow_script_mode_quickstart](https://github.com/awslabs/amazon-sagemaker-examples/tree/master/sagemaker-python-sdk/tensorflow_script_mode_quickstart)
* [tensorflow_script_mode_horovod](https://github.com/awslabs/amazon-sagemaker-examples/tree/master/sagemaker-python-sdk/tensorflow_script_mode_horovod)

We are planning to add more notebooks on how to use PipeMode with script mode containers, etc. Hope the notebooks are helpful. Please let us know if you have more questions.

**Comment by austinmw** [comment]
@icywang86rui Hi, thanks for your answer. I've previously reviewed those three documents, and they are helpful for training. Details not included that would be helpful for future notebooks are:

- Pipe mode + Script mode (as you mentioned is being worked on)
- custom input functions for serving

Thanks.

**Comment by icywang86rui** [comment]
Thanks for the suggestions. I will add writing these new notebook to our backlog.

**Comment by hsl89** [comment]
Dear SageMaker Community,
             In our attempts to provide this repository with a better level of support             going forward, we’re closing issues that were opened prior to the v2 release of the SDK.             This is because we believe that over time many of the issues             posted were solved with the latest release or other recent changes to the repo.             This will help us reallocate resources towards issues that are            more likely to still be relevant today.            Some of the issues experienced now can be resolved by referencing the            v2 guide: https://sagemaker.readthedocs.io/en/stable/v2.html             In this guide, you can find simple solutions to common notebook errors,             like the renaming of parameters and classes.            If you believe your issue is still ongoing and you have updated error            messaging or other info, please re-open it, and we investigate the issue.
            Best Regards,
            AWS SageMaker Team
