### ISSUE TITLE
BYO model 

### ISSUE THREAD

**Issue by walidsliti** [aws/amazon-sagemaker-examples#548]
Hello,
I'am pursuing your sckit_BYOM  and i need help please 
I want to deploy my own algorithm which is a decision tree : 
1- I'am running the code on an ec2 machine and it's working so can I just pickle the model and upload it to s3 in format .tar.jz but I don't know what to do next 

2- if I have to create a training job then I need to change predict and train files but the problem I didn't understand what to change 

the problem is in the two cases I have to change the predict file in case1 and predic/train files in case 2 in order to create the image 

this is the code that I want to deploy : https://github.com/minhup/Energy-Disaggregation/blob/master/energy_disaggregation.ipynb just the part of the decision tree

Thank you very much

**Comment by djarpin** [comment]
Hi @walidsliti ,

Are you using scikit-learn?  It looks like that may be the case based on the code you linked to.  If so, you might consider using SageMaker's pre-built [scikit-learn container](https://github.com/aws/sagemaker-scikit-learn-container), which we also have an [example notebook](https://github.com/awslabs/amazon-sagemaker-examples/blob/master/sagemaker-python-sdk/scikit_learn_iris/Scikit-learn%20Estimator%20Example%20With%20Batch%20Transform.ipynb) for.

If you're trying to host a model trained outside of SageMaker and bring your own container, then you will need to update [predict.py](https://github.com/awslabs/amazon-sagemaker-examples/blob/master/advanced_functionality/scikit_bring_your_own/container/decision_trees/predictor.py) appropriately.  This includes reading in the right filename for the pickled model in your model.tar.gz, reading and transforming any input data that you'll pass for prediction, generating the predictions, and any post-processing.  Once this is done, you'll need to create a container/image with that code.

Either way, you won't need to create a SageMaker training job.  You can use the [`SKLearnModel`](https://github.com/aws/sagemaker-python-sdk/blob/master/src/sagemaker/sklearn/model.py#L40) object if you're using the pre-built scikit-learn container (in which case you may need to define `input_fn()`, `predict_fn()`, etc. in your entry_point).  Or a [`Model`](https://github.com/aws/sagemaker-python-sdk/blob/master/src/sagemaker/model.py#L35) object from the SageMaker Python SDK, point to your model.tar.gz in S3 and `.deploy()`.

Thanks.

**Comment by cliveseldon** [comment]
The predict code seems to only support CSV input:

https://github.com/awslabs/amazon-sagemaker-examples/blob/d2d492e6f80d5c9335885a17403f373671564ac1/advanced_functionality/scikit_bring_your_own/container/decision_trees/predictor.py#L71

How does this compare with https://github.com/aws/sagemaker-scikit-learn-container/blob/master/src/sagemaker_sklearn_container/serving.pyn which seems a more general sklearn container for SageMaker and looks like it handles a wider range of inputs?  Which should we use?

**Comment by walidsliti** [comment]
hi @djarpin,

thank you for your response, I want to ask how to load the model.tar.gz in s3 to opt/ml

thank you

**Comment by djarpin** [comment]
Hi @cliveseldon ,
You're right that, as is, the scikit-learn container is more general and handles a wider range of input content types.  However, you could also update the bring your own container example to handle just about any format you'd like.  In general, I'd say it's easier to use the pre-built scikit-learn container, so try that first, but there may be some specialized use cases where bringing your own container makes sense.

Hi @walidsliti ,
SageMaker automatically loads the model artifact from S3 to /opt/ml/model/ when the endpoint is deployed, so you don't need to take any special action.

**Comment by walidsliti** [comment]
HI @djarpin 
I'am pursuing the scikit bring your own and i'am using the same dockerfile and files in the container except the train file and I'am trying to deploy my random forest trained algorithm 

I pickled my model that I trained out of sagemaker and I put it in s3 in .tar.gz format, then I build and push a dockezr image to ECR with the code in push_and_build.sh file (without modifing the 4 files in the container for now ) then I created a model with the console by providing the location of the s3 bucket that contains the model.tar.gz and the path to the image in ECR. after that I create an endpoint configuration  that take the right model and finaly I create the endpoint with the right configuration but I have failure. 

I only modified the name of the model.pkl in predictor file 

Failure reason : The primary container for production variant variant-name-1 did not pass the ping health check. Please check CloudWatch logs for this endpoint.

in cloudwatch i found these errors:
*[2019-01-03 15:50:02,376] ERROR in app: Exception on /ping [GET]
*ImportError: libopenblasp-r0-8dca6697.3.0.dev.so: cannot open shared object file: No such file or directory
* "GET /ping HTTP/1.1" 500 291 "-" "AHC/2.0" from .fixes import _Sequence as Sequence

did I miss something ?

**Comment by djarpin** [comment]
Hi @walidsliti - Hopefully pull request #579 addresses your issue, but let us know if it doesn't.

**Comment by hsl89** [comment]
Dear SageMaker Community,
             In our attempts to provide this repository with a better level of support             going forward, we’re closing issues that were opened prior to the v2 release of the SDK.             This is because we believe that over time many of the issues             posted were solved with the latest release or other recent changes to the repo.             This will help us reallocate resources towards issues that are            more likely to still be relevant today.            Some of the issues experienced now can be resolved by referencing the            v2 guide: https://sagemaker.readthedocs.io/en/stable/v2.html             In this guide, you can find simple solutions to common notebook errors,             like the renaming of parameters and classes.            If you believe your issue is still ongoing and you have updated error            messaging or other info, please re-open it, and we investigate the issue.
            Best Regards,
            AWS SageMaker Team
