### ISSUE TITLE
deploy trained model 

### ISSUE THREAD

**Issue by walidsliti** [aws/amazon-sagemaker-examples#558]
HI @djarpin 
I'am pursuing the scikit bring your own and i'am using the same dockerfile and files in the container except the train file and I'am trying to deploy my random forest trained algorithm 

I pickled my model that I trained out of sagemaker and I put it in s3 in .tar.gz format, then I build and push a dockezr image to ECR with the code in push_and_build.sh file (without modifing the 4 files in the container for now ) then I created a model with the console by providing the location of the s3 bucket that contains the model.tar.gz and the path to the image in ECR. after that I create an endpoint configuration  that take the right model and finaly I create the endpoint with the right configuration but I have failure. 

I only modified the name of the model.pkl in predictor file 

Failure reason : The primary container for production variant variant-name-1 did not pass the ping health check. Please check CloudWatch logs for this endpoint.

in cloudwatch i found these errors:
*[2019-01-03 15:50:02,376] ERROR in app: Exception on /ping [GET]
*ImportError: libopenblasp-r0-8dca6697.3.0.dev.so: cannot open shared object file: No such file or directory
* "GET /ping HTTP/1.1" 500 291 "-" "AHC/2.0" from .fixes import _Sequence as Sequence

did I miss something ?

**Comment by djarpin** [comment]
Hi @walidsliti - Hopefully pull request #579 addresses your issue, but let us know if it doesn't.

**Comment by hsl89** [comment]
@walidsliti does the issue still persist?
