### ISSUE TITLE
DeepAR Electricity Dataset Confusion

### ISSUE THREAD

**Issue by pratham16** [aws/amazon-sagemaker-examples#567]
For electricity dataset, the DeepAR paper gives following configuration: context_length=168, prediction_length=24, and rolling forecast for 7 days.

The original electricity dataset has granularity of 15-minutes. The notebook instance provided on sagemaker converts granularity **from 15-minutes to 2-hours**. Also, this is an **average aggregation**.

My question is, whether same preprocessing is used in the DeepAR paper as well? From paper, it seems that granularity is 1-hour, and aggreation is nowhere mentioned. Please clarify. Thanks.

**Comment by geoalgo** [comment]
Hi pratham16,

For the paper, the granularity is indeed 1-hour, you can set `freq = 1H` in to the notebook and you would get the same split for the dataset that we used. 

For the aggregation, we use sum while the notebook use average. However, this should not change the result given the mean scaling applied to the input (and the metrics are scale free also).

Let me know if you have any other question.

**Comment by hsl89** [comment]
close for lack of activity, try here https://stackoverflow.com/questions/tagged/amazon-sagemaker
