### ISSUE TITLE
how to run the an .ipynb file through lambda

### ISSUE THREAD

**Issue by BryanWEI** [aws/amazon-sagemaker-examples#573]
hi guys, I have an .ipynb file which contains a lstm model, predict result and other logic. The problem is I want to run this file in a time throuth lamdba, but i cannot find any way to achieve my goal. It's very appreciated if someone can tell me how to do it. Thx!!~~~

**Comment by ChoiByungWook** [comment]
Hello @BryanWEI,

I apologize for the late response.

Would [runipy ](https://pypi.org/project/runipy/) fulfill your use case?

**Comment by abhishekshankar891** [comment]
How  can be run juypter notebook containing preprocessing steps and returning a csv from lambda function?

**Comment by hsl89** [comment]
@BryanWEI , try here https://stackoverflow.com/questions/tagged/amazon-sagemaker
