### ISSUE TITLE
[Feature Request] More BYO serving stack examples

### ISSUE THREAD

**Issue by austinmw** [aws/amazon-sagemaker-examples#575]
Hi, I've created a BYO tensorflow.keras container based on [sagemaker-tensorflow-serving-container](https://github.com/aws/sagemaker-tensorflow-serving-container) and then set up the serving stack in the same way as the example in [tensorflow_bring_your_own.ipynb](https://github.com/awslabs/amazon-sagemaker-examples/blob/master/advanced_functionality/tensorflow_bring_your_own/tensorflow_bring_your_own.ipynb). That example shows querying the endpoint with the format:

```
data = {'instances': numpy.asarray(image).astype(float).tolist()}
predictor.accept = 'application/json'
predictor.content_type = 'application/json'
predictor.serializer = json_serializer
predictor.deserializer = json_deserializer
```
The problem with this is that it's not compressed at all so the payload size is very large and I hit the 5 MiB limit too quickly. The max image dimensions I seem to be able to send before hitting this payload size limit is only (1,286,286,3). In batches of (128,128,3) images this amounts to a batch limit of only 4 before hitting 5 MiB.

The workaround I've seen mentioned of sending an S3 path is not an efficient alternative for many use cases, for example when the endpoint is part of a larger inference pipeline so the incoming image is not on S3 in the first place and would require both uploading and downloading.

So either being able to increase this 5 MiB limit, or showing how I can compress images in some other format while staying under this 5 MiB limit would be extremely useful. Maybe a gRPC TensorFlow Serving BYO container example? An example of how to use custom `input_fn`'s with TensorFlow Serving in BYO container or Script Mode format would be greatly appreciated. There's plenty of training example notebooks, but examples on the serving side have been a bit sparse in comparison.

**Comment by yangaws** [comment]
Hi @austinmw ,

Thanks for your request. We will put your request in the backlog. We cannot provide an ETA now but when we have one, we will come back to update this issue.

I don't think we can increase the 5mb limit in a simple way. The simpler improvement for now we can make is to add examples for how to split data (compress image as you suggested here).

And another suggestion I can make is, have you tried our feature `batch transform` (https://github.com/aws/sagemaker-python-sdk#sagemaker-batch-transform)? That's also a way to do inference and there's no 5mb limit. Does that work in your use case?
