### ISSUE TITLE
[Ray] Callback support

### ISSUE THREAD

**Issue by Guilherme-B** [aws/amazon-sagemaker-examples#583]
Having fixed major problems through #581, [callback](https://ray.readthedocs.io/en/latest/rllib-training.html#callbacks-and-custom-metrics) support is still missing.

Inserting them manually via training script causes an obvious crash: tune functions aren't serializable.

Are there plans on adding callback support? Custom metrics are extremely important for training.

**Comment by hsl89** [comment]
hi @Guilherme-B, does the issue still exist?

**Comment by Guilherme-B** [comment]
Hi @hsl89 ,

I believe it is fixed, thank you.
