### ISSUE TITLE
ClientError: Please use a GPU instance for training

### ISSUE THREAD

**Issue by ryanlim1616** [aws/amazon-sagemaker-examples#587]
I am using AWS Sage Maker free Tier to train a ML model. My notebook instance is a ml.t2.medium. When i start to train using a ml.m4.xlarge, it gives me the error "ClientError: Please use a GPU instance for training". Is that anyway i am able to train with the free tier instance?

**Comment by fandotli** [comment]
There is not enough information here, but you may have tried to train a model using an algorithm that only supports GPU instance. You may switch to an algorithm that can run on CPU instance so that you can use the free tier ml.m4.xlarge for training.
