### ISSUE TITLE
TensorFlowModel with Python 3, no official docker image exists to pull

### ISSUE THREAD

**Issue by austinmw** [aws/amazon-sagemaker-examples#609]
I've trained a Tensorflow Estimator using Script Mode with framework_version='1.12' and python_version='py3', trained on a GPU instance. When I try to call deploy from this estimator, it only works if I select deployment instance type as GPU. If I try to deploy to a CPU or CPU+EIA, pulling the corresponding docker image fails. 

I started to find a workaround which involves the intermediate step of creating a TensorFlowModel from the trained estimator and then deploying from this model using the training job artifacts instead of deploying from the estimator directly. The problem with this workaround is that it does not seem to support Python 3. If I set the TensorFlowModel py_version='py3', docker fails to find any corresponding image to pull. 

So, it seems that there is no official Sagemaker TensorFlow 1.12.0 EIA python 3 docker image for serving? If that's the case, it currently does not seem possible to train with Script Mode using python 3 and then deploy to an EIA. Please let me know if I've missed something. Selecting a GPU instance type works as expected.

**Comment by laurenyu** [comment]
hi @austinmw, unfortunately there are no TF + Python 3 + EIA serving images at this time. I've added an item to our backlog for this, which we're always reprioritizing based on customer feedback.

In the meantime, please use the Python 2 version for serving instead. Apologies for the inconvenience.

**Comment by ChoiByungWook** [comment]
For reference:

https://github.com/awslabs/amazon-sagemaker-examples/issues/613
https://stackoverflow.com/questions/54485769/sagemaker-deploying-to-eia-from-tf-script-mode-python3

**Comment by ChoiByungWook** [comment]
Wanted to clarify for those that are stumbling on this thread that there are always non-EIA supported versions of the same framework in SageMaker. This can be used in the Python SDK by not specifying an `accelerator_type` when calling `deploy`.

For more information on Elastic Inference (EI) please see: https://docs.aws.amazon.com/sagemaker/latest/dg/ei.html

**Comment by seanpmorgan** [comment]
Closing as this is out of date and now supported:
https://github.com/aws/deep-learning-containers/blob/master/available_images.md
