### ISSUE TITLE
Incompatible test file in advanced_functionality\scikit_bring_your_own

### ISSUE THREAD

**Issue by david-waterworth** [aws/amazon-sagemaker-examples#610]
There's a minor error with scikit_bring_your_own test data

Lines 56/57 of predictor.py do the following

```
# Drop first column, since sample notebook uses training data to show case predictions
data.drop(data.columns[[0]],axis=1,inplace=True)
```

i.e. they appear to expect a file in the format y,x1,x2,x3,x4 and drop y

but the sample file local_tests/payload.csv only contains 4 columns, there's no y value in the file. So an exception is thrown saying n_samples is 3 not 4.

**Comment by IvyBazan** [comment]
This issue has been fixed and is no longer present in the notebook
