### ISSUE TITLE
Deep AR Flexible prediction length 

### ISSUE THREAD

**Issue by engineeryashsaxena** [aws/amazon-sagemaker-examples#616]
I have created a DeepAR model taking '1D' as time frequency and prediction length as 1 .
But my business needs forecasts for different periods , such as 3 days, 5 days , 4 days, 10 days etc. that is it needs to give flexible days , what is the best approach to achieve this ?

**Comment by jaheba** [comment]
Hello,
I would suggest training a model with `prediction_length` of `10` (or the longest prediction length you will be using) and use that model to for all of you forecast by just slicing the time-span you need.

The quality of the forecast should stay the same and there is no need to train different models, if all other parameters stay the same.

**Comment by engineeryashsaxena** [comment]
Thanks @jaheba  , I tried the same and it worked.
One more thing I want to know : Is there any way to apply transfer learning to the existing DeepAR model ? . For example , if new data is to be given to the model then do we have to retrain the model or transfer learning can be achieved in some way.

**Comment by jaheba** [comment]
Hello Yash,
at the moment it is not possible to continue learning an existing model with new data, so you'd have to retrain the model.

However, the already trained model can also be used to predict on new time series, as long as they are structurally similar to the ones the model was trained on. Nonetheless, it makes sense to regularly train a new model when more data is available (e.g. once a week or month).

**Comment by engineeryashsaxena** [comment]
Okay @jaheba , thanks a lot for the help !! 👍
