### ISSUE TITLE
Unsupported content-type application/x-image while invoking a CNN model deployed at Sagemaker

### ISSUE THREAD

**Issue by nahidalam** [aws/amazon-sagemaker-examples#619]
I have a tensorflow/keras based CNN model deployed in Sagemaker. 

Now to invoke the inference, I followed this [tutorial](https://aws.amazon.com/blogs/machine-learning/classify-your-own-images-using-amazon-sagemaker/) 

Below code snippet

```
def inferImage(endpoint_name):
    # Load the image bytes
    img = open('./shoe.jpg', 'rb').read()
    runtime = boto3.Session().client(service_name='sagemaker-runtime')

    # Call your model for predicting which object appears in this image.
    response = runtime.invoke_endpoint(
        EndpointName=endpoint_name,
        ContentType='application/x-image',
        Body=bytearray(img))
    response_body = response['Body']
    print(response_body.read()) 
```

When I run this code, I get error 

`Unsupported content-type application/x-image`

What am I missing?

**Comment by ChoiByungWook** [comment]
Hello @nahidalam,

For clarification, can you point me to the specific ECR image you are using to host your model?

Thanks!

**Comment by prameshbajra** [comment]
Hi @nahidalam , did you solve this? 
Mind sharing how ?

**Comment by nahidalam** [comment]
@prameshbajra no could not solve it. But I moved to a different approach of hosting custom model through docker on SageMaker so did not have to solve it this way.

**Comment by prameshbajra** [comment]
@nahidalam  Thank you for the reply.

For future readers,
I kind of got it working:

```
from sagemaker.tensorflow.serving import Predictor

predictor = Predictor(endpoint_name = "<Your endpoint name here>")
```

Then I constructed the body like:

```
import cv2
import numpy as np

headers = {"content-type": "application/json"}
image_content = cv2.imread("<PATH to the image>",
                           1).astype('uint8').tolist()
body = {"instances": [{"inputs": image_content}]}
```

Just make sure that the body is under 5mb limit or else this will throw a `Connection closed  error`. i.e Try with small images. (This is the reason I said, I kind of got it working). After that the predictions can be generated from:

```
results = predictor.predict(body)
```

Happy deploying. :)

**Comment by samirlenka** [comment]
OPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.
Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs).



Got the above issue after following the current above step.

**Comment by prameshbajra** [comment]
> OPub data rate exceeded.
> The notebook server will temporarily stop sending output
> to the client in order to avoid crashing it.
> To change this limit, set the config variable
> `--NotebookApp.iopub_data_rate_limit`.
> Current values:
> NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
> NotebookApp.rate_limit_window=3.0 (secs).
> 
> Got the above issue after following the steps.

Hi @samirlenka ,

Can you please let me know the configuration/name of the instance you used to deploy your model to?

Also, a brief background information about your task can be of help. Consider providing it if possible.
