### ISSUE TITLE
tensorflow_bring_your_own errors out in 'local' mode.

### ISSUE THREAD

**Issue by sermolin** [aws/amazon-sagemaker-examples#622]
Run example *unchanged*. You should be able to easily reproduce it. 
Line 
      estimator.fit('file:///tmp/cifar-10-data') 
gave the following error:
..................
=[DT_FLOAT, DT_INT32], _device="/job:localhost/replica:0/task:0/device:CPU:0"](OneShotIterator)]]\n\n'
algo-1-8udyt_1  | 
tmp7e6hbc8__algo-1-8udyt_1 exited with code 255
Aborting on container exit...
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
~/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/sagemaker/local/image.py in train(self, input_data_config, output_data_config, hyperparameters, job_name)
    132         try:
--> 133             _stream_output(process)
    134         except RuntimeError as e:

~/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/sagemaker/local/image.py in _stream_output(process)
    588     if exit_code != 0:
--> 589         raise RuntimeError("Process exited with code: %s" % exit_code)
    590 

RuntimeError: Process exited with code: 255

During handling of the above exception, another exception occurred:

RuntimeError                              Traceback (most recent call last)
<ipython-input-21-bc9bcfdbe743> in <module>()
     11                       hyperparameters=hyperparameters)
     12 
---> 13 estimator.fit('file:///tmp/cifar-10-data')
     14 
     15 predictor = estimator.deploy(1, instance_type)

~/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/sagemaker/estimator.py in fit(self, inputs, wait, logs, job_name)
    234         self._prepare_for_training(job_name=job_name)
    235 
--> 236         self.latest_training_job = _TrainingJob.start_new(self, inputs)
    237         if wait:
    238             self.latest_training_job.wait(logs=logs)

~/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/sagemaker/estimator.py in start_new(cls, estimator, inputs)
    576             train_args['image'] = estimator.train_image()
    577 
--> 578         estimator.sagemaker_session.train(**train_args)
    579 
    580         return cls(estimator.sagemaker_session, estimator._current_job_name)

~/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/sagemaker/session.py in train(self, input_mode, input_config, role, job_name, output_config, resource_config, vpc_config, hyperparameters, stop_condition, tags, metric_definitions, enable_network_isolation, image, algorithm_arn, encrypt_inter_container_traffic)
    318         LOGGER.info('Creating training-job with name: {}'.format(job_name))
    319         LOGGER.debug('train request: {}'.format(json.dumps(train_request, indent=4)))
--> 320         self.sagemaker_client.create_training_job(**train_request)
    321 
    322     def compile_model(self, input_model_config, output_model_config, role,

~/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/sagemaker/local/local_session.py in create_training_job(self, TrainingJobName, AlgorithmSpecification, OutputDataConfig, ResourceConfig, InputDataConfig, **kwargs)
     72         training_job = _LocalTrainingJob(container)
     73         hyperparameters = kwargs['HyperParameters'] if 'HyperParameters' in kwargs else {}
---> 74         training_job.start(InputDataConfig, OutputDataConfig, hyperparameters, TrainingJobName)
     75 
     76         LocalSagemakerClient._training_jobs[TrainingJobName] = training_job

~/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/sagemaker/local/entities.py in start(self, input_data_config, output_data_config, hyperparameters, job_name)
     68         self.state = self._TRAINING
     69 
---> 70         self.model_artifacts = self.container.train(input_data_config, output_data_config, hyperparameters, job_name)
     71         self.end = datetime.datetime.now()
     72         self.state = self._COMPLETED

~/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/sagemaker/local/image.py in train(self, input_data_config, output_data_config, hyperparameters, job_name)
    136             # which contains the exit code and append the command line to it.
    137             msg = "Failed to run: %s, %s" % (compose_command, str(e))
--> 138             raise RuntimeError(msg)
    139 
    140         artifacts = self.retrieve_artifacts(compose_data, output_data_config, job_name)

RuntimeError: Failed to run: ['docker-compose', '-f', '/tmp/tmp7e6hbc8_/docker-compose.yaml', 'up', '--build', '--abort-on-container-exit'], Process exited with code: 255

**Comment by hsl89** [comment]
does the issue still persists?
