### ISSUE TITLE
Can't upgrade tensorflow_bring_your_own to TF container 1.12.  KeyError: 'sagemaker_region'

### ISSUE THREAD

**Issue by sermolin** [aws/amazon-sagemaker-examples#623]
Copied example from SageMaker Examples of Jupyter Notebook Home. I upgraded to TF container 1.12. 
Code line 
    tree.fit(data_location)
gave the following error:
INFO:sagemaker:Creating training-job with name: sagemaker-keras-text-classification-2019-02-13-21-48-30-029
328296961357
us-west-2
328296961357.dkr.ecr.us-west-2.amazonaws.com/sagemaker-keras-text-classification
2019-02-13 21:48:30 Starting - Starting the training job...
2019-02-13 21:48:33 Starting - Launching requested ML instances......
2019-02-13 21:49:36 Starting - Preparing the instances for training...
2019-02-13 21:50:29 Downloading - Downloading input data
2019-02-13 21:50:29 Training - Downloading the training image...
2019-02-13 21:50:57 Uploading - Uploading generated training model
2019-02-13 21:50:57 Failed - Training job failed
.
2019-02-13 21:50:55,745 WARNING - root - error reading log_level, using INFO
2019-02-13 21:50:55,745 INFO - root - running container entrypoint
2019-02-13 21:50:55,745 INFO - root - starting train task
2019-02-13 21:50:55,760 WARNING - root - error reading log_level, using INFO
2019-02-13 21:50:55,760 INFO - container_support.training - Training starting
2019-02-13 21:50:55,764 ERROR - container_support.training - uncaught exception during training: 'sagemaker_region'
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/container_support/training.py", line 31, in start
    env = TrainingEnvironment()
  File "/usr/local/lib/python2.7/dist-packages/container_support/environment.py", line 223, in __init__
    self.sagemaker_region = self.hyperparameters[ContainerEnvironment.SAGEMAKER_REGION_PARAM_NAME]
KeyError: 'sagemaker_region'

ValueErrorTraceback (most recent call last)
<ipython-input-7-45ea951f7753> in <module>()
     11                        sagemaker_session=sess)
     12 
---> 13 tree.fit(data_location)

/home/ec2-user/anaconda3/envs/tensorflow_p27/lib/python2.7/site-packages/sagemaker/estimator.pyc in fit(self, inputs, wait, logs, job_name)
    236         self.latest_training_job = _TrainingJob.start_new(self, inputs)
    237         if wait:
--> 238             self.latest_training_job.wait(logs=logs)
    239 
    240     def _compilation_job_name(self):

/home/ec2-user/anaconda3/envs/tensorflow_p27/lib/python2.7/site-packages/sagemaker/estimator.pyc in wait(self, logs)
    586     def wait(self, logs=True):
    587         if logs:
--> 588             self.sagemaker_session.logs_for_job(self.job_name, wait=True)
    589         else:
    590             self.sagemaker_session.wait_for_job(self.job_name)

/home/ec2-user/anaconda3/envs/tensorflow_p27/lib/python2.7/site-packages/sagemaker/session.pyc in logs_for_job(self, job_name, wait, poll)
   1168 
   1169         if wait:
-> 1170             self._check_job_status(job_name, description, 'TrainingJobStatus')
   1171             if dot:
   1172                 print()

/home/ec2-user/anaconda3/envs/tensorflow_p27/lib/python2.7/site-packages/sagemaker/session.pyc in _check_job_status(self, job, desc, status_key_name)
    868             reason = desc.get('FailureReason', '(No reason provided)')
    869             job_type = status_key_name.replace('JobStatus', ' job')
--> 870             raise ValueError('Error for {} {}: {} Reason: {}'.format(job_type, job, status, reason))
    871 
    872     def wait_for_endpoint(self, endpoint, poll=5):

ValueError: Error for Training job sagemaker-keras-text-classification-2019-02-13-21-48-30-029: Failed Reason: AlgorithmError: uncaught exception during training: 'sagemaker_region'
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/container_support/training.py", line 31, in start
    env = TrainingEnvironment()
  File "/usr/local/lib/python2.7/dist-packages/container_support/environment.py", line 223, in __init__
    self.sagemaker_region = self.hyperparameters[ContainerEnvironment.SAGEMAKER_REGION_PARAM_NAME]
KeyError: 'sagemaker_region'
-----------------
Process of upgrading to TF container 1.12:
# 1.12 TF container for AIM410.
# Create the SageMaker TensorFlow Container Python package.
cd ~
git clone https://github.com/aws/sagemaker-tensorflow-container.git
cd sagemaker-tensorflow-containers
python setup.py sdist

#. Copy your Python package to “final” Dockerfile directory that you are building.
cp dist/sagemaker_tensorflow_container-1.0.0.tar.gz docker/1.12.0/final/py2
cd docker/1.12.0/final/py2/
# from https://pypi.org/project/tensorflow/#files get the appropriate python whl file via wget. Example 

# Build container
docker build -t tensorflow-base:1.12.0-cpu-py2 \
--build-arg framework_installable=tensorflow-1.12.0-cp27-cp27mu-manylinux1_x86_64.whl\
 -f Dockerfile.cpu .

# list docker images to check
docker images
# expected output:
#REPOSITORY           TAG                 IMAGE ID            CREATED             SIZE
#tensorflow-base      1.12.0-cpu-py2      6a9fb46608ab        14 seconds ago      1.12GB
#ubuntu               16.04               7e87e2b3bf7a        3 weeks ago         117MB
#tensorflow/serving   1.12.0              d42952c6f8a6        3 months ago        230MB
-----

I then replaced the line in the Docker file that came with the example to point to TF 1.12 image:
'FROM tensorflow/tensorflow:1.8.0-py3'  =>  'FROM tensorflow-base:1.12.0-cpu-py2'
and executed shell docker-related  command script in Jupyter notebook. the container built without errors. 

I also tried the same on a different BYOC example (https://github.com/aws-samples/amazon-sagemaker-keras-text-classification) which has a somewhat simpler docker file. Got the same error.

**Comment by ChoiByungWook** [comment]
Hello @sermolin,

I apologize for the inconvenience. It seems that the stacktrace points to an environment variable not being initialized. The corresponding code is here: https://github.com/aws/sagemaker-containers/blob/r1.0/src/container_support/environment.py#L48 which get's populated through an environment variable here: https://github.com/aws/sagemaker-containers/blob/r1.0/src/container_support/environment.py#L224

I believe if you use the Python SDK this parameter gets passed in properly as shown here: https://github.com/aws/sagemaker-python-sdk/blob/ab1f7587bf1c35a54549cc676c273dea356301e4/src/sagemaker/estimator.py#L855

Unfortunately, this means we have to be dependent on the SageMaker Python SDK.

**Comment by hsl89** [comment]
does the issue still persist with sagemaker python sdk v2?
