### ISSUE TITLE
[Feature Requests] Multi-model endpoints and endpoint organization

### ISSUE THREAD

**Issue by austinmw** [aws/amazon-sagemaker-examples#627]
I was surprised to find that although I can fit five models into a single endpoint for load balancing and inference pipelines, I'm not able to directly call individual models. Besides cost factors, this would be really useful for organizational purposes. For example, if I have multiple model versions that I'd like all stood-up and accessible for real-time inference at the same time, the endpoint console interface can quickly get cluttered.

similarly, providing a way to categorize/organize endpoints within the console would be nice. For example having categories such as staging and production, then subfolders of vision, nlp, reinforcement models, etc. would be a nice addition to the UI.

Lastly, allowing longer endpoint names would be appreciated.

**Comment by hsl89** [comment]
any update?
