### ISSUE TITLE
exec: "serve": executable file not found in $PATH error 

### ISSUE THREAD

**Issue by sujithaperumal** [aws/amazon-sagemaker-examples#628]
I get exec: "serve": executable file not found in $PATH error when trying to create an endpoint. Any help would be appreciated. Thanks!

**Comment by austinmw** [comment]
@sujithaperumal are you using a custom docker image and/or entry point?

**Comment by SarmadBashir** [comment]
@sujithaperumal i am getting the same error. Found any solution to the problem?

**Comment by prathameshd9** [comment]
Same here. Please keep me in the loop.

**Comment by ledinhkien** [comment]
I'm assuming that you are referring to the endpoint of the custom docker image.

You have to grant permission for it. eg: I put it at the end of the Dockerfile
```sh
RUN chmod +x /opt/program/serve
```

**Comment by ricoms** [comment]
I had the same problem as OP and @ledinhkien comment was the solution for me, thanks!

**Comment by harinathselvaraj** [comment]
@ricoms What was the solution. I couldn't find @ledinkein comment. 
@sujithaperumal @austinmw I am facing the same error. Please help

**Comment by d33kayyy** [comment]
> 
> 
> I'm assuming that you are referring to the endpoint of the custom docker image.
> 
> You have to grant permission for it. eg: I put it at the end of the Dockerfile
> 
> ```shell
> RUN chmod +x /opt/program/serve
> ```

@harinathselvaraj this is the one you're looking for

**Comment by seanpmorgan** [comment]
As mentioned "serve' is the default entrypoint for inference containers. In your dockerfile you may need to make sure it's executable. Closing as there isn't a specific dockerfile or example referenced.
