### ISSUE TITLE
Predicting with features using deepar

### ISSUE THREAD

**Issue by doron31** [aws/amazon-sagemaker-examples#629]
I am trying to use deep-ar model in order tp forecast multiple time series with dynamic features. 
I think I might be using the API wrong as the model seems to predict very poorly on days with the dynamic features set to 1 (which has a strong uplift effect).
Previously i was using the deepar_synthetic notebook for reference but today I was looking at the DeepAR-Electricity example and noticed some differences:

In the predict method in DeepARPredictor class in Electricity notebook, I noticed that the ts input is documented as a pandas series, whereas in the deepar_synthetic it reads to be a list of pandas series object.
The latter is the way I was using the predict method:

predictor.predict(time_series_training, cat = encode_list
                                       ,dynamic_feat = test_regressor_list)

where time_series_training is a list of pandas series

**Comment by benidis** [comment]
Hi doron31,

The DeepARPredictor classes in the two notebooks are slightly different. You can use the one you prefer.

**Comment by hsl89** [comment]
any update?
