### ISSUE TITLE
PyTorch 1.0 Neo compilation fails

### ISSUE THREAD

**Issue by austinmw** [aws/amazon-sagemaker-examples#642]
I created a new notebook instance (default instance type), and updated the pytorch_36 kernel to v1.0.0 with `conda update -y -n root conda && conda install -y pytorch-cpu==1.0.0 torchvision-cpu -c pytorch`. I then opened the example notebook `pytorch_torchvision_neo.ipynb` with this kernel and updated the `framework_version` argument to 1.0.0. Neo compilation then fails in code cell 3. 

The failure reason in console actually says to upgrade to version 1.0, so it should be supported, but the notebook seems to only work when using the default version 0.4.0:

> Failure reason
> Client Error: InputConfiguration: Invalid PyTorch model or input-shape mismatch. Make sure that inputs are lexically ordered and of the correct dimensionality. Upgrade to PyTorch 1.0 and use torch.jit.trace() and torch.jit.save() to export your model. Also cast your model with eval() before exporting.

-----
I also tried jit tracing, setting to eval and jit saving, but get the same error. I did so by modifying code cell 1 to this:

```python
import torch
import torchvision.models as models
import tarfile

jit_model = torch.jit.trace(models.resnet18(pretrained=True), torch.ones(1,3,224,224))
jit_model.eval()
torch.jit.save(jit_model, 'model.pth')

with tarfile.open('model.tar.gz', 'w:gz') as f:
    f.add('model.pth')
```

**Comment by Koin-Flipper** [comment]
Please use the following version of PyTorch:
```
conda install pytorch=0.4.1 -c pytorch
```
Export your model with `torch.save()`.

**Comment by austinmw** [comment]
@Koin-Flipper Why do I need to use pytorch 0.4 when my error message says to use 1.0? 

(My models are not compatible with 0.4 anyway)

**Comment by miroenev** [comment]
Observing the same error using PyTorch 1.0.0 as well as PyTorch v 0.4.1 with the approaches below:
1. using the torch.jit.trace, torch.jit.save export method (as well as casting to eval) 
2. using torch.onnx  (ONNX v1.3.0)

Have tried every variation of the data input specification described on the Neo compilation <a href='https://docs.aws.amazon.com/sagemaker/latest/dg/neo-troubleshooting.html'>troubleshooting docs</a>

**Comment by austinmw** [comment]
@miroenev I talked with the SM Neo team on the phone and was told that pytorch 1.0 introduced a bug between release candidates, so only 0.4 is supported until this is fixed on their side.

**Comment by miroenev** [comment]
thanks for heads up @austinmw

**Comment by Least1924** [comment]
@austinmw have you solved this problem? i am meeting the same one....

**Comment by Least1924** [comment]
@miroenev have you solved this problem? i am meeting the same one....

**Comment by KoinFlyp** [comment]
Use the following commands to export a PyTorch model:
```
trace = torch.jit.trace(model.float().eval(), torch.zeros(input_shape).float())
trace.save(‘model.pth’)
```
Note that PyTorch 1.0.1 must be installed:
```
pip install torch==1.0.1 -f https://download.pytorch.org/whl/cpu/stable
```

**Comment by apivovarov** [comment]
Sagemaker notebook has pytorch-1.1.0 pre-installed.
But Model Compilation service expects model saved by `pytorch-0.4.0` or `pytorch-1.0.1`

Solution to the issue:
```
# 1. do not install `pytorch-cpu` and `torchvision-cpu`.

# 2. Downgrade pytorch version to 1.0.1
!conda install -y pytorch=1.0.1 -c pytorch 

# 3. import pytorch and check that version is 1.0.1 (but not 1.1.0)
import torch 
torch.__version__
```
Continue to run notebook steps: https://github.com/awslabs/amazon-sagemaker-examples/blob/master/sagemaker_neo_compilation_jobs/pytorch_torchvision/pytorch_torchvision_neo.ipynb

**Comment by farleyschaefer** [comment]
@apivovarov I have a similar issue (https://github.com/awslabs/amazon-sagemaker-examples/issues/986). Does this mean that Neo will strictly only work if I save my weights using `pytorch-0.4.0` or `pytorch-1.0.1`. Is this documented anywhere else?

**Comment by vdabravolski** [comment]
I tried to rerun notebook with downgraded version of PyTorch (both. 1.0.0 and 1.0.1) and got the same error. 

@apivovarov any other recommendations?

**Comment by amanzw** [comment]
@vdabravolski you can follow steps:
1. pytorch version 1.2.0
`pip3 install torch==1.2.0 torchvision==0.4.0`
2. JIT
```
resnet18 = models.resnet18(pretrained=True).float().eval()
rand_input = torch.rand([1,3,224,224])
trace = torch.jit.trace(resnet18, rand_input)
torch.jit.save(trace, 'model.pth')
```
3.
`framework_version = '1.2.0' `

**Comment by hsl89** [comment]
any update?

**Comment by mrtj** [comment]
Currently, Neo does not support any more frame_work versions 1.2 for pytorch. For compilation target "linux" e "nvidia" accelerator only pytorch 1.7 and 1.8 are supported. I tried tracing my model with pytorch 1.2, 1.4 and 1.7 and compiling it specifying `framework_version = '1.7'` and `framework_version = '1.8'`, in all cases failing the compilation with the a very similar error:

> ClientError: InputConfiguration: TVM cannot convert the PyTorch model. Invalid model or input-shape mismatch. Make sure that inputs are lexically ordered and of the correct dimensionality

How can we compile a custom model for linux/nvidia end of 2021?
