### ISSUE TITLE
Outdated Documentation

### ISSUE THREAD

**Issue by shaharj** [aws/amazon-sagemaker-examples#697]
In one of the earlier steps, the example notebook code suggests to use `urllib.request` however this library has been deprecated.  I encountered a `ImportError: No module named request` error.  One should instead just import `urllib` and write `urllib.urlretrieve`.

**Comment by neelamgehlot** [comment]
Hi @shaharj,
Which notebook are you referring to?

Thanks,
Neelam

**Comment by ngrayluna** [comment]
Hi @shaharj, when you ran into the error, did you check if you had `requests` installed?  By default, it is not a built-in module. You'll have to install it yourself: https://stackoverflow.com/questions/17309288/importerror-no-module-named-requests

As of Python 3.8.3,  `urllib.request` is not deprecated (yet). It might be in the future:
https://docs.python.org/3/library/urllib.request.html#legacy-interface

**Comment by seanpmorgan** [comment]
Closing. Please let us know if there are still issues with the proposed solution
