### ISSUE TITLE
couldn`t import sagemaker.rl

### ISSUE THREAD

**Issue by goodboychan** [aws/amazon-sagemaker-examples#705]
Hi,
I`m trying to use sagemaker.rl for hyperparameter tuning.
But When I execute the example notebook, error is occurred:
No module named 'sagemaker.rl'

Is there any requirements to use RLEstimator? I already installed sagemaker-python-sdk, used basic AMI.

Thanks in advance.

**Comment by yijiezz** [comment]
Hi @goodboychan 

Can you provide more details about your setup?
Are you running the notebook in your local machine or in SageMaker notebook instance?
Also, what python version and sagemaker version you are using.
You can use `python -c "import sagemaker; print(sagemaker.__version__)` to see the version of the sagemaker-python-sdk.
Are you able to use other modules from the sdk, but not sagemaker.rl ?

There is not extra requirements for using RLEstimator if you install the sdk properly.

Thanks

**Comment by seanpmorgan** [comment]
Closing as this appears to be not related to anything specific in this repo. Please let us know if you still need assistance.
