### ISSUE TITLE
Security issue -- bad links in notebooks

### ISSUE THREAD

**Issue by rabowskyb** [aws/amazon-sagemaker-examples#776]
There are bad links in at least two of the transfer learning notebooks in https://github.com/awslabs/amazon-sagemaker-examples/tree/master/introduction_to_amazon_algorithms/imageclassification_caltech.

Specifically, the following link in those notebooks is bad:  http://data.dmlc.ml/mxnet/data/caltech-256/.  It asks users to go through some kind of "security check" and install a browser extension.  

I recommend removing the link and simplifying the text in those sections of the notebooks as follows:  "The Caltech 256 dataset consist of images from 256 categories plus a clutter category. It has a total of 30000 images, with a minimum of 80 images and a maximum of about 800 images per category.  The image classification algorithm can take two types of input formats. The first is a recordio format, and the other is a lst format. In this example, we will use the recordio format."

**Comment by pccornel** [comment]
Closing as not reproducible. I went through all of these links but did get any kind of "security check" nor install a browser extension.
