### ISSUE TITLE
internal error in deepar sagemaker - TypeError: unsupported operand type(s) for +=: 'Timestamp' and 'str

### ISSUE THREAD

**Issue by NicolaiHarich** [aws/amazon-sagemaker-examples#780]
Hi everyone,
I get a strange internal error, when I start a deepar training on Sagemaker. 

There is obviously some type incompatibility going on, as it tries to concatenate a Timestamp with a string. But I don't know what exactly the cause is (it's located in "/opt/amazon/bin/sagemaker-train", line 11).
I've already check my input format. The time format seems to be correct - it's like in the documentation (e.g. "2009-11-01 00:00:00").

Here is the Traceback:

> Traceback (most recent call last):
> File "/opt/amazon/bin/sagemaker-train", line 11, in <module>
> load_entry_point('AIAlgorithmsSDK==1.0', 'console_scripts', 'sagemaker-train')()
> File "/opt/amazon/lib/python2.7/site-packages/ai_algorithms_sdk/train.py", line 85, in main
> sdk_error = convert_to_algorithm_error(e)
> File "/opt/amazon/lib/python2.7/site-packages/ai_algorithms_sdk/base/exceptions.py", line 27, in convert_to_algorithm_error
> return AlgorithmError(message, exception)
> File "/opt/amazon/lib/python2.7/site-packages/ai_algorithms_sdk/base/exceptions.py", line 216, in __init__
> exit_code=EXIT_CODE_ALGORITHM_ERROR)
> File "/opt/amazon/lib/python2.7/site-packages/ai_algorithms_sdk/base/exceptions.py", line 147, in __init__
> formatted_message = BaseSdkError._format_exception_message(message, caused_by)
> File "/opt/amazon/lib/python2.7/site-packages/ai_algorithms_sdk/base/exceptions.py", line 175, in _format_exception_message
> formatted_message += " (caused by
> {}
> )".format(caused_by.__class__.__name__)
> **TypeError: unsupported operand type(s) for +=: 'Timestamp' and 'str'**

For any help I would be really appreciated. Thank you!

Best,
Nico

**UPDATE:**

Apparently this error somehow is caused by the used **time frequency,** which is '2W'. If I change it to 'W' it works just fine. But [according to the documentation](https://docs.aws.amazon.com/en_en/sagemaker/latest/dg/deepar_hyperparameters.html) '2W' should also work. 

> Valid values: An integer followed by M, W, D, H, or min. For example, 5min. 

It seems that this is a bug...

**Comment by seanpmorgan** [comment]
Thanks for reporting. Was fixed in https://github.com/aws/amazon-sagemaker-examples/pull/1490
