### ISSUE TITLE
predictor.py in scikit-bring-your-own needs to be modified

### ISSUE THREAD

**Issue by stefannatu** [aws/amazon-sagemaker-examples#794]
The transformation function in predictor.py in the scikit-bring-your-own drops the first column (since the training data was used in testing) but the payload.csv actually doesn't contain the labels anymore. So this line of code which removes the first column (below) needs to be removed from the code in order for it to correctly test the payload on the local instance.

# Drop first column, since sample notebook uses training data to show case predictions
data.drop(data.columns[[0]],axis=1,inplace=True)

**Comment by seanpmorgan** [comment]
Thanks this was fixed in https://github.com/aws/amazon-sagemaker-examples/pull/771
