### ISSUE TITLE
Performing Inference on single text using deployed Doc2Vec

### ISSUE THREAD

**Issue by PeterDykas** [aws/amazon-sagemaker-examples#824]
I am new to asking github issues so please remove this if this is not the correct place for questions. 

I followed the doc2vec sample notebook(https://github.com/awslabs/amazon-sagemaker-examples/blob/master/introduction_to_applying_machine_learning/object2vec_document_embedding/object2vec_document_embedding.ipynb)  and deployed the model.  My goal is to be able to send requests for the embedding of a single document to the endpoint from a lambda.  I am using the following code:

```
import boto3
import json
runtime= boto3.client('runtime.sagemaker')

def lambda_handler(event, context):
    ENDPOINT_NAME = 'object2vec-2019-07-25-01-05-51-633'
    
    payload = []
    payload.append({'in0': [135556, 0, 1177, 1216, 150107, 7428, 236788, 170159, 242245, 10, 1178, 117937, 7436, 54019, 114321, 236788, 233944, 65353, 114321, 222729, 88998, 1439]})
    response = runtime.invoke_endpoint(EndpointName=ENDPOINT_NAME,
                                       Body=json.dumps(payload))
    result = json.loads(response['Body'].read().decode())
    print(result)
    
    return "worked"
```

However I am getting the error :

```
  "errorMessage": "An error occurred (ModelError) when calling the InvokeEndpoint operation: Received client error (400) from model with message \"unable to evaluate payload provided\". See https://us-east-1.console.aws.amazon.com/cloudwatch/home?region=us-east-1#logEventViewer:group=/aws/sagemaker/Endpoints/object2vec-2019-07-25-01-05-51-633 in account 236475725625 for more information.",
```
I am trying to emulate the input that was shown in the notebook.

My questions would be:
1. What am I doing wrong with  my call to the endpoint?
2. Can I add automatic text preprocessing to the endpoint so that I can pass strings rather than their tokenized versions?

**Comment by pnpnpn** [comment]
1. Have you tried using the predictor instead? https://sagemaker.readthedocs.io/en/stable/predictors.html The notebook you linked to has an example of using `predictor.predict`. 

2. Object2Vec does not have automatic text preprocessing. You can however add the preprocessing to your lambda.

**Comment by alansalimov** [comment]
having the same issue, passing a `.jsonl` file of that format to doc2vec transformer and getting a  `unable to evaluate payload provided` error

**Comment by hsl89** [comment]
Dear SageMaker Community,
                 In our attempts to provide this repository with a better level of support                 going forward, we’re closing issues that were opened prior to the v2 release of the SDK.                 This is because we believe that over time many of the issues                 posted were solved with the latest release or other recent changes to the repo.                 This will help us reallocate resources towards issues that are                more likely to still be relevant today.                Some of the issues experienced now can be resolved by referencing the                v2 guide: https://sagemaker.readthedocs.io/en/stable/v2.html                 In this guide, you can find simple solutions to common notebook errors,                 like the renaming of parameters and classes.                If you believe your issue is still ongoing and you have updated error                messaging or other info, please re-open it, and we investigate the issue.
                Best Regards,
                AWS SageMaker Team
