### ISSUE TITLE
Build and push docker image - error

### ISSUE THREAD

**Issue by bauerjan93** [aws/amazon-sagemaker-examples#827]
I tried to run the deepracer_rl.ipynb with different instances. It always fails at the "Build and push docker image" part. I did everything as described  in the Readme file and tried several different instances.

Here is the output it produces:

---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
~/SageMaker/amazon-sagemaker-examples/reinforcement_learning/rl_deepracer_robomaker_coach_gazebo/common/docker_utils.py in _execute(command, quiet)
    167     try:
--> 168         _stream_output(process)
    169     except RuntimeError as e:

~/SageMaker/amazon-sagemaker-examples/reinforcement_learning/rl_deepracer_robomaker_coach_gazebo/common/docker_utils.py in _stream_output(process)
    195     if exit_code != 0:
--> 196         raise RuntimeError("Process exited with code: %s" % exit_code)
    197 

RuntimeError: Process exited with code: 1

During handling of the above exception, another exception occurred:

RuntimeError                              Traceback (most recent call last)
<timed exec> in <module>()

~/SageMaker/amazon-sagemaker-examples/reinforcement_learning/rl_deepracer_robomaker_coach_gazebo/common/docker_utils.py in build_and_push_docker_image(repository_name, dockerfile, build_args)
     38     base_image = _find_base_image_in_dockerfile(dockerfile)
     39     _ecr_login_if_needed(base_image)
---> 40     _build_from_dockerfile(repository_name, dockerfile, build_args)
     41     ecr_tag = push(repository_name)
     42     return ecr_tag

~/SageMaker/amazon-sagemaker-examples/reinforcement_learning/rl_deepracer_robomaker_coach_gazebo/common/docker_utils.py in _build_from_dockerfile(repository_name, dockerfile, build_args)
     49 
     50     print("Building docker image %s from %s" % (repository_name, dockerfile))
---> 51     _execute(build_cmd)
     52     print("Done building docker image %s" % repository_name)
     53 

~/SageMaker/amazon-sagemaker-examples/reinforcement_learning/rl_deepracer_robomaker_coach_gazebo/common/docker_utils.py in _execute(command, quiet)
    171         # which contains the exit code and append the command line to it.
    172         msg = "Failed to run: %s, %s" % (command, str(e))
--> 173         raise RuntimeError(msg)
    174 
    175 

RuntimeError: Failed to run: ['docker', 'build', '-t', 'sagemaker-docker-cpu', '-f', 'Dockerfile', '.', '--build-arg', 'CPU_OR_GPU=cpu', '--build-arg', 'AWS_REGION=us-east-1'], Process exited with code: 1

**Comment by Java1Guy** [comment]
Any news on this? I am getting the same :(

**Comment by hsl89** [comment]
Dear SageMaker Community,
                 In our attempts to provide this repository with a better level of support                 going forward, we’re closing issues that were opened prior to the v2 release of the SDK.                 This is because we believe that over time many of the issues                 posted were solved with the latest release or other recent changes to the repo.                 This will help us reallocate resources towards issues that are                more likely to still be relevant today.                Some of the issues experienced now can be resolved by referencing the                v2 guide: https://sagemaker.readthedocs.io/en/stable/v2.html                 In this guide, you can find simple solutions to common notebook errors,                 like the renaming of parameters and classes.                If you believe your issue is still ongoing and you have updated error                messaging or other info, please re-open it, and we investigate the issue.
                Best Regards,
                AWS SageMaker Team
