### ISSUE TITLE
small bug in object2vec_multilabel_genre_classification.ipynb: function get_plots

### ISSUE THREAD

**Issue by jameszh** [aws/amazon-sagemaker-examples#828]
The `get_plots` function in object2vec_multilabel_genre_classification.ipynb only gets half of movie plots, it skips every 2nd "MV:"

Thanks,
James

**Comment by hsl89** [comment]
Dear SageMaker Community,
                 In our attempts to provide this repository with a better level of support                 going forward, we’re closing issues that were opened prior to the v2 release of the SDK.                 This is because we believe that over time many of the issues                 posted were solved with the latest release or other recent changes to the repo.                 This will help us reallocate resources towards issues that are                more likely to still be relevant today.                Some of the issues experienced now can be resolved by referencing the                v2 guide: https://sagemaker.readthedocs.io/en/stable/v2.html                 In this guide, you can find simple solutions to common notebook errors,                 like the renaming of parameters and classes.                If you believe your issue is still ongoing and you have updated error                messaging or other info, please re-open it, and we investigate the issue.
                Best Regards,
                AWS SageMaker Team
