### ISSUE TITLE
Pytorch - Bring your own model

### ISSUE THREAD

**Issue by LouisBB** [aws/amazon-sagemaker-examples#832]
Hello,

I'm sorry this is not really an issue. I just don't really know where to post this.

Is there an easy way to bring an already trained pytorch model to sagemaker ?

The PyTorchModel class requires a model_data that satisfies the sagemaker model format and I don't know how to build a tar.gz sagemaker model from my .pth pytorch model.

Maybe a workaround would be to retrain locally using the sagemaker SDK but it would mean installing docker-compose and nvidia-docker and I would have to fit a model that I don't want to fit in order to be able to upload it to s3 in the right format. So it is not so great.

Any help would be appreciated

**Comment by jsanders67** [comment]
Have you tried to tar your .pth file and deploying the model to that endpoint using that tar ball? It would be the `model_data` param outlined here: https://sagemaker.readthedocs.io/en/stable/using_pytorch.html#deploy-endpoints-from-model-data. There is even a code example of how to do this (adapted below):

```bash
tar -czf model.tar.gz my_model.pth
aws s3 cp model.tar.gz s3://my-bucket/my-path/model.tar.gz
```

When you deploy a model to an endpoint, SageMaker will just download and untar your file and the PyTorch container may just be able to take it from there.

If that does not work out-of-the-box, then it looks like you can write your own function to load your model. See (these docs)[https://sagemaker.readthedocs.io/en/stable/using_pytorch.html#the-sagemaker-pytorch-model-server], it looks like

**Comment by hsl89** [comment]
Dear SageMaker Community,
                 In our attempts to provide this repository with a better level of support                 going forward, we’re closing issues that were opened prior to the v2 release of the SDK.                 This is because we believe that over time many of the issues                 posted were solved with the latest release or other recent changes to the repo.                 This will help us reallocate resources towards issues that are                more likely to still be relevant today.                Some of the issues experienced now can be resolved by referencing the                v2 guide: https://sagemaker.readthedocs.io/en/stable/v2.html                 In this guide, you can find simple solutions to common notebook errors,                 like the renaming of parameters and classes.                If you believe your issue is still ongoing and you have updated error                messaging or other info, please re-open it, and we investigate the issue.
                Best Regards,
                AWS SageMaker Team
