### ISSUE TITLE
Bug: DeepAR: ClientError: training time series consist of only zeros

### ISSUE THREAD

**Issue by pjebs** [aws/amazon-sagemaker-examples#834]
I think this should not be an error. If the training time series consists of only zeros (in my use case this is a legitimate possibility), DeepAR should have a very easy time generating a model. A little child could probably predict the next one million points.

**Comment by jaheba** [comment]
Hello @pjebs, thanks for pointing this out and we are looking into it.

**Comment by hsl89** [comment]
Dear SageMaker Community,
                 In our attempts to provide this repository with a better level of support                 going forward, we’re closing issues that were opened prior to the v2 release of the SDK.                 This is because we believe that over time many of the issues                 posted were solved with the latest release or other recent changes to the repo.                 This will help us reallocate resources towards issues that are                more likely to still be relevant today.                Some of the issues experienced now can be resolved by referencing the                v2 guide: https://sagemaker.readthedocs.io/en/stable/v2.html                 In this guide, you can find simple solutions to common notebook errors,                 like the renaming of parameters and classes.                If you believe your issue is still ongoing and you have updated error                messaging or other info, please re-open it, and we investigate the issue.
                Best Regards,
                AWS SageMaker Team
