### ISSUE TITLE
unable to subscribe to AWS Marketplace offering for aws_marketplace/using_model_packages/auto_insurance/

### ISSUE THREAD

**Issue by sermolin** [aws/amazon-sagemaker-examples#839]
Deep Vision vehicle recognition AWS offering returns error upon subscription:
"Your subscription failed. Please, try again".
<img width="898" alt="Screen Shot 2019-08-07 at 9 25 58 AM" src="https://user-images.githubusercontent.com/25041537/62639956-686d4280-b8f5-11e9-8666-66cfe8b24ef7.png">

**Comment by hsl89** [comment]
Dear SageMaker Community,
                 In our attempts to provide this repository with a better level of support                 going forward, we’re closing issues that were opened prior to the v2 release of the SDK.                 This is because we believe that over time many of the issues                 posted were solved with the latest release or other recent changes to the repo.                 This will help us reallocate resources towards issues that are                more likely to still be relevant today.                Some of the issues experienced now can be resolved by referencing the                v2 guide: https://sagemaker.readthedocs.io/en/stable/v2.html                 In this guide, you can find simple solutions to common notebook errors,                 like the renaming of parameters and classes.                If you believe your issue is still ongoing and you have updated error                messaging or other info, please re-open it, and we investigate the issue.
                Best Regards,
                AWS SageMaker Team
