### ISSUE TITLE
object_detection_incremental_training - missing matplotlib magic

### ISSUE THREAD

**Issue by russau** [aws/amazon-sagemaker-examples#843]
I think the [object_detection_incremental_training.ipynb](https://github.com/awslabs/amazon-sagemaker-examples/blob/master/introduction_to_amazon_algorithms/object_detection_pascalvoc_coco/object_detection_incremental_training.ipynb) notebook is missing a [matplotlib](https://ipython.readthedocs.io/en/stable/interactive/magics.html#magic-matplotlib) magic. I get a nicer output if I add `%matplotlib inline` to the notebook.

Before:

![image](https://user-images.githubusercontent.com/167762/62825137-cbf8a980-bb5b-11e9-9269-12726cf013db.png)

After:

![image](https://user-images.githubusercontent.com/167762/62825147-e763b480-bb5b-11e9-9e6c-b089940dc79f.png)

**Comment by hsl89** [comment]
Dear SageMaker Community,
                 In our attempts to provide this repository with a better level of support                 going forward, we’re closing issues that were opened prior to the v2 release of the SDK.                 This is because we believe that over time many of the issues                 posted were solved with the latest release or other recent changes to the repo.                 This will help us reallocate resources towards issues that are                more likely to still be relevant today.                Some of the issues experienced now can be resolved by referencing the                v2 guide: https://sagemaker.readthedocs.io/en/stable/v2.html                 In this guide, you can find simple solutions to common notebook errors,                 like the renaming of parameters and classes.                If you believe your issue is still ongoing and you have updated error                messaging or other info, please re-open it, and we investigate the issue.
                Best Regards,
                AWS SageMaker Team
