### ISSUE TITLE
PyTorch 1.1 Neo compilation fails

### ISSUE THREAD

**Issue by vadimAnyVision** [aws/amazon-sagemaker-examples#846]
Hi,
Im trying to compile network that was done in PyTorch 1.1 and my compilation fails.
the error I get is "ClientError: InputConfiguration: Incompatible ONNX model"
how can I understand what is the problem (i.e if the network is not compatible or something else?)?
thanks

**Comment by mnuyens** [comment]
In general that error means that Sagemaker Neo was unable to convert the model from its base framework into the form that Neo uses to optimize the model. Without more information about the specific compilation job I can't give you anymore information.

**Comment by austinmw** [comment]
As of a couple months ago Neo compilation didn't support Pytorch 1.0.0, let alone 1.1.0+. The recommended version was 0.4.0. I opened up a ticket to see if there's been any updates to this.

**Comment by lokeshgupta1975** [comment]
Can you please try again, we have recently added support for PT 1.2 to Neo compilation service

**Comment by hsl89** [comment]
Dear SageMaker Community,
                 In our attempts to provide this repository with a better level of support                 going forward, we’re closing issues that were opened prior to the v2 release of the SDK.                 This is because we believe that over time many of the issues                 posted were solved with the latest release or other recent changes to the repo.                 This will help us reallocate resources towards issues that are                more likely to still be relevant today.                Some of the issues experienced now can be resolved by referencing the                v2 guide: https://sagemaker.readthedocs.io/en/stable/v2.html                 In this guide, you can find simple solutions to common notebook errors,                 like the renaming of parameters and classes.                If you believe your issue is still ongoing and you have updated error                messaging or other info, please re-open it, and we investigate the issue.
                Best Regards,
                AWS SageMaker Team
