### ISSUE TITLE
How to pass multiple inputs into SparkML BlazingText model in a single request

### ISSUE THREAD

**Issue by vincentnqt** [aws/amazon-sagemaker-examples#847]
I followed the example in this [notebook](https://github.com/awslabs/amazon-sagemaker-examples/blob/master/advanced_functionality/inference_pipeline_sparkml_blazingtext_dbpedia/inference_pipeline_sparkml_blazingtext_dbpedia.ipynb) and was able to get it working successfully when passing a single input into the model. However, when I tried to pass multiple inputs when invoking the model's endpoint, only one prediction output is returned by the model. 

Sample Inputs: `{"data": ["this tone is catchy", "the lyrics are terrible"]}`
Output: `{"label": ["__label__1"], "prob": [1.0000100135803223]}`

Does anyone know if it is possible to pass multiple inputs and get multiple prediction outputs by invoking the model's endpoint (and not using batch transform)?

**Comment by hsl89** [comment]
Dear SageMaker Community,
                 In our attempts to provide this repository with a better level of support                 going forward, we’re closing issues that were opened prior to the v2 release of the SDK.                 This is because we believe that over time many of the issues                 posted were solved with the latest release or other recent changes to the repo.                 This will help us reallocate resources towards issues that are                more likely to still be relevant today.                Some of the issues experienced now can be resolved by referencing the                v2 guide: https://sagemaker.readthedocs.io/en/stable/v2.html                 In this guide, you can find simple solutions to common notebook errors,                 like the renaming of parameters and classes.                If you believe your issue is still ongoing and you have updated error                messaging or other info, please re-open it, and we investigate the issue.
                Best Regards,
                AWS SageMaker Team
