### ISSUE TITLE
Inconsistent results

### ISSUE THREAD

**Issue by varshney016** [aws/amazon-sagemaker-examples#850]
Hi All,

I  just run below notebook
"https://github.com/awslabs/amazon-sagemaker-examples/blob/master/advanced_functionality/xgboost_bring_your_own_model/xgboost_bring_your_own_model.ipynb".
and see results
![xgbbost_awslab](https://user-images.githubusercontent.com/18576227/63329514-b9e2ec00-c34f-11e9-9beb-674740c59883.PNG)

why the output of `print(floatArr)` and `print(bt.predict_proba(point_X))` is not exactly same???

Note: I ran the above notebook with xgboost regression on my data-set with suitable modifications, for almost all test data points, outputs of regression are different in `model.predict()` and endpoint response with difference in the value as much as 1.94

**Comment by aws-patlin** [comment]
Hi @varshney016, sorry for the late response.

What kind of data was `point_X` from, and how did you load that data? We recently discovered a [bug](https://github.com/dmlc/xgboost/issues/5456) in upstream XGBoost that was causing incorrect predictions on CSV data loaded into DMatrix directly from a file. This may be the cause of the differences you're seeing.

**Comment by aaronmarkham** [comment]
Please reopen if you're still seeing this problem.
