### ISSUE TITLE
Running a DeepAR trained model locally

### ISSUE THREAD

**Issue by eoghanmull** [aws/amazon-sagemaker-examples#854]
Having a trained a DeepAR model in the cloud I am looking to use the resulting model.tar.gz to run inference on my local computer. Despite my best efforts I cannot find documentation showing how to run the model locally, the only option that is recommended is to create an aws sagemaker endpoint which I was using until the cost of same became too expensive.

Can a trained deepAR model be run for inference on a local machine?

**Comment by OscarVanL** [comment]
Look into AWS GreenGrass for this, Amazon make you use some proprietary tool in order to use your models offline or locally - and they charge for the privilege. Although I can't seem to work out how to use it on DeepAR anyway, they have _no examples_ on how to do it.

**Comment by buchart** [comment]
You cannot train SageMaker's built-in algorithms locally but can do local training on SageMaker's deep learning frameworks.

**Comment by hsl89** [comment]
Dear SageMaker Community,
                 In our attempts to provide this repository with a better level of support                 going forward, we’re closing issues that were opened prior to the v2 release of the SDK.                 This is because we believe that over time many of the issues                 posted were solved with the latest release or other recent changes to the repo.                 This will help us reallocate resources towards issues that are                more likely to still be relevant today.                Some of the issues experienced now can be resolved by referencing the                v2 guide: https://sagemaker.readthedocs.io/en/stable/v2.html                 In this guide, you can find simple solutions to common notebook errors,                 like the renaming of parameters and classes.                If you believe your issue is still ongoing and you have updated error                messaging or other info, please re-open it, and we investigate the issue.
                Best Regards,
                AWS SageMaker Team
