### ISSUE TITLE
Can't Pull ECR Image in Local Mode on Local Machine

### ISSUE THREAD

**Issue by cvrooman** [aws/amazon-sagemaker-examples#858]
Hi There, 

I'm trying to test the linear learner [example](https://github.com/awslabs/amazon-sagemaker-examples/blob/master/sagemaker-python-sdk/scikit_learn_inference_pipeline/Inference%20Pipeline%20with%20Scikit-learn%20and%20Linear%20Learner.ipynb) notebook on my local machine usinge 'local mode'. I seem to be running into an issue during the step "Fit a LinearLearner Model with the preprocessed data".

"Error response from daemon: pull access denied for 382416733822.dkr.ecr.us-east-1.amazonaws.com/linear-learner, repository does not exist or may require 'docker login': denied: User: arn:aws:iam::<account id>:user/<username> is not authorized to perform: ecr:BatchGetImage on resource: arn:aws:ecr:us-east-1:382416733822:repository/linear-learner"

Does this step require a SageMaker notebook instance in the cloud? 

I've given the account administrative privileges to ECR and used "aws ecr get-login --no-include-email --registry-ids 382416733822 --region us-east-1" to authenticate docker.

**Comment by austinmw** [comment]
see if passing a local session works:

```
from sagemaker.local import local_session
my_local_session = local_session.LocalSession()
my_local_session.config = {'local': {'local_code': True}}

 sagemaker_session=my_local_session
instance_type='local' # or 'local_gpu'
```

**Comment by ori-n** [comment]
I'm getting the same error. I just trying passing a local session but it didn't help

**Comment by silverfoxf7** [comment]
hey @cvrooman I rant into something similar and noticed that I was using the new AWS CLI v2, which deprecated the `get-login` command.  Instead, I had to use: `aws ecr get-login-password --region ${region} | docker login --username AWS --password-stdin ${account}.dkr.ecr.${region}.amazonaws.com`

**Comment by hsl89** [comment]
Dear SageMaker Community,
                 In our attempts to provide this repository with a better level of support                 going forward, we’re closing issues that were opened prior to the v2 release of the SDK.                 This is because we believe that over time many of the issues                 posted were solved with the latest release or other recent changes to the repo.                 This will help us reallocate resources towards issues that are                more likely to still be relevant today.                Some of the issues experienced now can be resolved by referencing the                v2 guide: https://sagemaker.readthedocs.io/en/stable/v2.html                 In this guide, you can find simple solutions to common notebook errors,                 like the renaming of parameters and classes.                If you believe your issue is still ongoing and you have updated error                messaging or other info, please re-open it, and we investigate the issue.
                Best Regards,
                AWS SageMaker Team
