### ISSUE TITLE
Better Documentation regarding Sagemaker ?

### ISSUE THREAD

**Issue by shafaypro** [aws/amazon-sagemaker-examples#863]
I was wondering if we could have better documentation regarding machine learning algorithms, instead of Jupyter notebook with comments, there could be a video/ sphinx based documentation which could help a lot in case of AWS Sagemaker?, not staying to AWS but generally for the algorithms as well. Along with the Sagemaker Algorithms reference of how they are working (just the general flow not the inner complete details)

**Comment by hsl89** [comment]
Dear SageMaker Community,
                 In our attempts to provide this repository with a better level of support                 going forward, we’re closing issues that were opened prior to the v2 release of the SDK.                 This is because we believe that over time many of the issues                 posted were solved with the latest release or other recent changes to the repo.                 This will help us reallocate resources towards issues that are                more likely to still be relevant today.                Some of the issues experienced now can be resolved by referencing the                v2 guide: https://sagemaker.readthedocs.io/en/stable/v2.html                 In this guide, you can find simple solutions to common notebook errors,                 like the renaming of parameters and classes.                If you believe your issue is still ongoing and you have updated error                messaging or other info, please re-open it, and we investigate the issue.
                Best Regards,
                AWS SageMaker Team
