### ISSUE TITLE
How to deploy an existing model trained using Sagemaker's built-in algorithms

### ISSUE THREAD

**Issue by VicXue** [aws/amazon-sagemaker-examples#864]
Hi,

I'm using the Sagemaker's built-in Semantic Segmentation algorithm and I strictly followed the [example](https://github.com/awslabs/amazon-sagemaker-examples/blob/master/introduction_to_amazon_algorithms/semantic_segmentation_pascalvoc/semantic_segmentation_pascalvoc.ipynb). I managed to run my program in the notebook successfully and it outputs the model into my S3 bucket. Now, I want to deploy a trained model for inference. 

I have done some research and after reading the [documentation](https://sagemaker.readthedocs.io/en/stable/using_mxnet.html#deploy-endpoints-from-model-data), I think I need to do something like this: 
```
mxnet_model = MXNetModel(model_data='s3://bucket/model.tar.gz', 
role='SageMakerRole', entry_point='transform_script.py')
predictor = mxnet_model.deploy(instance_type='ml.c4.xlarge', initial_instance_count=1)
```

What troubles me is the transform_script.py. After reading through the #216, I think in this python file I need to add a model_fn() function in order to load the model correctly. The model.tar.gz in the S3 bucket contains three files, which are hyperparams.json, model_best.params and model_algo-1. According to this [documentation](https://docs.aws.amazon.com/sagemaker/latest/dg/cdf-training.html), the model_algo-1 is the serialized model. Then, I tried to implement the model_fn() function like this: 

```
import mxnet as mx
def model_fn(model_dir):
    """
    Load the model. Called once when hosting service starts.
    :param: model_dir The directory where model files are stored.
    :return: a model 
    """
    net = mx.ndarray.load('{}/model_algo-1'.format(model_dir))
    return net
```

However, this is not working, as it results in the same ping health check issue because of this error: 

> ValueError: Unsupported model type: dict

At this stage, I'm not sure how to construct the model_fn function correctly in order to load the model. Can you please give me some suggestions?

**Comment by Ali-Parandeh** [comment]
Hi Vic,

You need to do `os.system(unzip model_algo-1)` I believe before passing it to `mx.ndarray.load()`.

Have a look at my [notebook](https://github.com/beginners-machine-learning-london/intro_to_unsupervised_ml_with_AWS_Sagemaker/blob/master/exercises/Intro%20to%20Unsupervised%20ML%20with%20AWS%20Sagemaker%20-%20Solutions.ipynb) to see how I have deserialised my model.

Look at `ln(19)` onwards in the notebook. 

Let me know if this resolves the issue.

**Comment by VicXue** [comment]
@Ali-Parandeh 
Hi Ali,

Thank you for offering help. I have seen this [forum page](https://forums.aws.amazon.com/message.jspa?messageID=863331) before, where that guy also unzipped the model_algo-1 file. However, my unzip command returns status code 2304, the same as shown in your notebook. What does this status code stand for? When I tried to unzip the model_algo-1 file in Linux, the unzip command says 

> cannot find zipfile directory in one of model_algo-1 or model_algo-1.zip, and cannot find model_algo-1.ZIP, period.

Nonetheless, whether I unzip the model_algo-1 or not, does not change the output of the load command. `SS_model_params = mx.ndarray.load("model_algo-1")` . The SS_model_params looks like this:

> {'layer3.2.bn3.beta': 
> [-0.05149289 -0.06148966 -0.10767566 ... -0.02368157 -0.07451027
>  -0.06600171]
> <NDArray 1024 @cpu(0)>, 'layer3.0.conv3.weight': 
> [[[[-0.00205779]]
> 
>   [[ 0.01004015]]
> 
>   [[-0.00498903]]
> 
>   ...
> [[ 0.00285471]]
> 
>   [[ 0.00490467]]
> 
>   [[-0.01265643]]]]
> <NDArray 1024x256x1x1 @cpu(0)>, 'conv1.1.running_var': 
> [5.6051939e-45 5.0486924e-05 5.6051939e-45 1.5008974e-02 1.9769181e-02
>  6.7603961e-03 3.5629801e-02 2.1420400e-01 2.5002372e-02 2.3836270e-05
>  6.1273009e-02 3.7571763e-06 1.6219148e-02 9.9418424e-03 2.9494298e-05
>  1.6259832e-02 2.4062607e-02 2.8162761e-02 2.2140786e-03 1.0047865e-02
>  8.9971432e-03 1.5272610e-02 5.6051939e-45 5.6051939e-45 2.6367275e-02
>  2.0670548e-01 1.8550303e-02 3.3706877e-02 5.6051939e-45 1.0255229e-02
>  4.3102046e-03 1.1064210e-10 5.6051939e-45 1.4833592e-02 1.1454555e-02
>  2.2633800e-01 1.5470413e-02 6.6074481e-06 5.6051939e-45 8.2642096e-04
>  1.2695887e-03 5.6051939e-45 1.5276832e-02 1.5952846e-02 9.2826605e-02
>  8.6446524e-02 7.8113914e-02 1.1752672e-02 5.6327754e-03 2.4644753e-02
>  2.2085987e-01 2.2932021e-05 5.6051939e-45 9.8516187e-03 2.8602563e-02
>  1.1938198e-02 2.1081407e-02 1.4156575e-02 4.7568221e-02 2.7534842e-02
>  2.0073473e-02 1.4408455e-02 9.1348648e-02 1.6187033e-02]
> <NDArray 1024 @cpu(0)>, 'layer2.0.conv1.weight': 
> [[[[ 0.02403444]]
> 
>   [[ 0.0025383 ]]
> .....

It seems like these are all the weight values from all the layers in the model, but how can I go from here is something I'm not sure of. I presume this is different to your Kmeans_model_params, as `pd.DataFrame(SS_model_params[0].asnumpy())` results in 

> KeyError: 0.

Also, it looks like your cluster_centroids_kmeans variable stores lon/lat result data instead of model's weights. Can you tell me how your Kmeans_model_params looks like and what kind of data it stores?

Thank you,
Victor

**Comment by Ali-Parandeh** [comment]
It looks like SS_model_params is a dictionary of keys and you are using a convolutional neural network so you will have a more complicated data structure for storing your weights and biases.

To answer your question, my model output was just 10 coordinates because the model is an unsupervised machine learning model (Kmeans) which has clustered 80,000 data points into 10 clusters and those 10 coordinates are the mean coordinates of each cluster. It's a useful application for geospatial data when you have lots of it.

In summary, I think you need to convert your `SS_model_params` to a list before passing it to the `mx.ndarray.load()`. Maybe you got the error below because  `SS_model_params` was a dictionary? I think your ML algorithm has stored your trained weights and biases in a dictionary format so need to figure out how to convert it into a data format that the `mx.ndarray.load()` expects.

In regards to the `2304` status code, I'm not too sure. Is that 4 status codes or 1? The [unzip](https://linux.die.net/man/1/unzip) says `0` is normal.

**Comment by VicXue** [comment]
@Ali-Parandeh 
I see. Thank you for the clarification. In the SageMaker's Semantic Segmentation [documentation](https://docs.aws.amazon.com/sagemaker/latest/dg/semantic-segmentation.html), they said they are using the Gluon framework for their implementation. I found out that you can [load a gluon model parameters](https://gluon.mxnet.io/chapter03_deep-neural-networks/serialization.html#Saving-and-loading-the-parameters-of-gluon-models), but it seems I need to reconstruct all the layers, which I'm not sure how Sagemaker implements it. All I want to do is reload a trained model, in my case, do you know what the simplest way to do that is? Does converting a dictionary to a list gonna help? Also, how do I  carry on after converting it to a list? Sorry, if there are too many questions.

**Comment by weiwei-liu** [comment]
[Incremental training](https://docs.aws.amazon.com/sagemaker/latest/dg/incremental-training.html) might worth trying, since  it can build a new model based on existing trained one.

**Comment by hsl89** [comment]
Dear SageMaker Community,
                 In our attempts to provide this repository with a better level of support                 going forward, we’re closing issues that were opened prior to the v2 release of the SDK.                 This is because we believe that over time many of the issues                 posted were solved with the latest release or other recent changes to the repo.                 This will help us reallocate resources towards issues that are                more likely to still be relevant today.                Some of the issues experienced now can be resolved by referencing the                v2 guide: https://sagemaker.readthedocs.io/en/stable/v2.html                 In this guide, you can find simple solutions to common notebook errors,                 like the renaming of parameters and classes.                If you believe your issue is still ongoing and you have updated error                messaging or other info, please re-open it, and we investigate the issue.
                Best Regards,
                AWS SageMaker Team

**Comment by taroko-mooncake** [comment]
Still having this issue
