### ISSUE TITLE
source_dir or dependencies for Batch Transform of a SKLearn model?

### ISSUE THREAD

**Issue by liamFerris** [aws/amazon-sagemaker-examples#868]
Hey,

I'm currently using a SKLearn training job (in which I have a .tar.gz module install - the solution will have no outside internet access, hence the offline dependency). I am using both the `source_dir` and `dependency` parameters. This seems to be working well.

My issue is when I try to do the same thing for a batch transform job. My code currently looks like this:

```
model = SKLearnModel(
        model_data=MODEL_INPUT,
        entry_point=SAGEMAKER_ENTRY,
        role=IAM_ROLE,
        source_dir=SOURCE_DIRECTORY,
        dependencies=LIB_DIRECTORY,
        framework_version=FRAMEWORK_VERSION,
        sagemaker_session=sagemaker_session)

transformer = model.transformer(
        instance_count=1,
        instance_type=INSTANCE_TYPE,
        output_path=PREDICTION_OUTPUT,
        max_payload=100,
        assemble_with = 'Line',
        strategy='MultiRecord',
        accept='text/csv')
```

However in CloudWatch I am told that the module.tar.gz can not be found and as a result the batch transform job fails. 

Am I misunderstanding how this is supposed to work? Is this a bug? How can I achieve the desired functionality (offline dependency install within SKLearn batch transform?)

**Comment by hsl89** [comment]
Dear SageMaker Community,
                 In our attempts to provide this repository with a better level of support                 going forward, we’re closing issues that were opened prior to the v2 release of the SDK.                 This is because we believe that over time many of the issues                 posted were solved with the latest release or other recent changes to the repo.                 This will help us reallocate resources towards issues that are                more likely to still be relevant today.                Some of the issues experienced now can be resolved by referencing the                v2 guide: https://sagemaker.readthedocs.io/en/stable/v2.html                 In this guide, you can find simple solutions to common notebook errors,                 like the renaming of parameters and classes.                If you believe your issue is still ongoing and you have updated error                messaging or other info, please re-open it, and we investigate the issue.
                Best Regards,
                AWS SageMaker Team
