### ISSUE TITLE
Error in 'object_detection_image_json_format.ipynb' SageMaker Example

### ISSUE THREAD

**Issue by biranchi2018** [aws/amazon-sagemaker-examples#873]
I am getting the below error, even if i start with empty aws S3 bucket

import shutil

train_jsons = jsons[:4452]
val_jsons = jsons[4452:]

#Moving training files to the training folders
for i in train_jsons:
    image_file = './val2017/'+i.split('.')[0]+'.jpg'
    shutil.move(image_file, './train/')
    shutil.move('./generated/'+i, './train_annotation/')

#Moving validation files to the validation folders
for i in val_jsons:
    image_file = './val2017/'+i.split('.')[0]+'.jpg'
    shutil.move(image_file, './validation/')
    shutil.move('./generated/'+i, './validation_annotation/')
    
    

Error                                     Traceback (most recent call last)
<ipython-input-11-165be9fa5d1a> in <module>()
      7 for i in train_jsons:
      8     image_file = './val2017/'+i.split('.')[0]+'.jpg'
----> 9     shutil.move(image_file, './train/')
     10     shutil.move('./generated/'+i, './train_annotation/')
     11 

~/anaconda3/envs/mxnet_p36/lib/python3.6/shutil.py in move(src, dst, copy_function)
    540         real_dst = os.path.join(dst, _basename(src))
    541         if os.path.exists(real_dst):
--> 542             raise Error("Destination path '%s' already exists" % real_dst)
    543     try:
    544         os.rename(src, real_dst)

Error: Destination path './train/000000306437.jpg' already exists

**Comment by hsl89** [comment]
Dear SageMaker Community,
                 In our attempts to provide this repository with a better level of support                 going forward, we’re closing issues that were opened prior to the v2 release of the SDK.                 This is because we believe that over time many of the issues                 posted were solved with the latest release or other recent changes to the repo.                 This will help us reallocate resources towards issues that are                more likely to still be relevant today.                Some of the issues experienced now can be resolved by referencing the                v2 guide: https://sagemaker.readthedocs.io/en/stable/v2.html                 In this guide, you can find simple solutions to common notebook errors,                 like the renaming of parameters and classes.                If you believe your issue is still ongoing and you have updated error                messaging or other info, please re-open it, and we investigate the issue.
                Best Regards,
                AWS SageMaker Team
