### ISSUE TITLE
mxnet_mnist.ipynb is not compatible with JupyterLab

### ISSUE THREAD

**Issue by mckev-amazon** [aws/amazon-sagemaker-examples#875]
The HTML widget used to draw the number in the predictor cell in the mxnet_mnist.ipynb example does not function as expected in JupyterLab (any version), while it works fine in Jupyter Classic.

This notebook may need to be reworked to remove or replace this widget so that it works in JuptyerLab.

(Error seen: "NameError: name 'data' is not defined")

**Comment by hsl89** [comment]
Dear SageMaker Community,
                 In our attempts to provide this repository with a better level of support                 going forward, we’re closing issues that were opened prior to the v2 release of the SDK.                 This is because we believe that over time many of the issues                 posted were solved with the latest release or other recent changes to the repo.                 This will help us reallocate resources towards issues that are                more likely to still be relevant today.                Some of the issues experienced now can be resolved by referencing the                v2 guide: https://sagemaker.readthedocs.io/en/stable/v2.html                 In this guide, you can find simple solutions to common notebook errors,                 like the renaming of parameters and classes.                If you believe your issue is still ongoing and you have updated error                messaging or other info, please re-open it, and we investigate the issue.
                Best Regards,
                AWS SageMaker Team
