### ISSUE TITLE
deepar-future prediction in sagemaker

### ISSUE THREAD

**Issue by monikabala** [aws/amazon-sagemaker-examples#883]
Hi,
I am having data from 1st feb 2019 to 10th sep 2019. Want to predict after 10th sep 2019 for univariate. I am not using any dynamic features . I have splited the data for train from
1st feb to 31st aug 2019 and for test from 1st sep to 10th sep. 

If it's correct, what i have to give it in max predict date, start date and end date?? what are the hyperparameters i have to set?? where i have to make changes in the code?? can i predict after 10th sep 2019??

**Comment by hsl89** [comment]
Dear SageMaker Community,
                 In our attempts to provide this repository with a better level of support                 going forward, we’re closing issues that were opened prior to the v2 release of the SDK.                 This is because we believe that over time many of the issues                 posted were solved with the latest release or other recent changes to the repo.                 This will help us reallocate resources towards issues that are                more likely to still be relevant today.                Some of the issues experienced now can be resolved by referencing the                v2 guide: https://sagemaker.readthedocs.io/en/stable/v2.html                 In this guide, you can find simple solutions to common notebook errors,                 like the renaming of parameters and classes.                If you believe your issue is still ongoing and you have updated error                messaging or other info, please re-open it, and we investigate the issue.
                Best Regards,
                AWS SageMaker Team
