### ISSUE TITLE
entrypoint with relative path fails to execute

### ISSUE THREAD

**Issue by pdasamzn** [aws/amazon-sagemaker-examples#893]
I have setup my sklearn estimator as follows:

```
ske = SKLearn(entry_point='my_package/train.py',
             source_dir='./my_package_directory',
             train_instance_type='ml.m5.4xlarge',
             role=role,
             output_path='s3://my_bucket/location'
             sagemaker_session=session) 

ske.fit( ...) 

``` 

When the `fit` method executes, the sagemaker training job fails with the following error:

`AlgorithmError: ExecuteUserScriptError: Command "/usr/bin/python3 -m my_package/train`

Digging deeper I noticed that inside the container the `.py` extension of the original entrypoint gets stripped off here:
https://github.com/aws/sagemaker-containers/blob/a84f48a1ede4aa7dd96dbd050d27ac540d8ce59b/src/sagemaker_containers/_process.py#L81

Suggested change would be to replace `/` with '.' apart from stripping out the `.py`

**Comment by austinmw** [comment]
try just setting it to:

```
source_dir='my_package_directory',
entry_point='train.py'
```

**Comment by hsl89** [comment]
Dear SageMaker Community,
                 In our attempts to provide this repository with a better level of support                 going forward, we’re closing issues that were opened prior to the v2 release of the SDK.                 This is because we believe that over time many of the issues                 posted were solved with the latest release or other recent changes to the repo.                 This will help us reallocate resources towards issues that are                more likely to still be relevant today.                Some of the issues experienced now can be resolved by referencing the                v2 guide: https://sagemaker.readthedocs.io/en/stable/v2.html                 In this guide, you can find simple solutions to common notebook errors,                 like the renaming of parameters and classes.                If you believe your issue is still ongoing and you have updated error                messaging or other info, please re-open it, and we investigate the issue.
                Best Regards,
                AWS SageMaker Team
