### ISSUE TITLE
Inference pipeline transformer unable to parse CSV

### ISSUE THREAD

**Issue by DanyalAndriano** [aws/amazon-sagemaker-examples#898]
I created an inference pipeline, with the first container as a sklearn preprocessor and the second an xgboost classifier. The pipeline works and I am able to run a transform job with the preprocessor and fit that data with the xgboost classifier. I am able to pass a single `text/csv` payload for inference.

However, when I try and run a single batch transform job, I get the following errors:

```
2019-10-08T14:43:15.635:[sagemaker logs]: MaxConcurrentTransforms=1, MaxPayloadInMB=40, BatchStrategy=SINGLE_RECORD
2019-10-08T14:43:45.016:[sagemaker logs]: sagemaker-xgboost-sentiment-classification/sklearn-xgboost-sentiment-classification/inference-pipeline/train/batch_train2.csv: ClientError: 400
2019-10-08T14:43:45.016:[sagemaker logs]: sagemaker-xgboost-sentiment-classification/sklearn-xgboost-sentiment-classification/inference-pipeline/train/batch_train2.csv:
2019-10-08T14:43:45.016:[sagemaker logs]: sagemaker-xgboost-sentiment-classification/sklearn-xgboost-sentiment-classification/inference-pipeline/train/batch_train2.csv: Message:
2019-10-08T14:43:45.016:[sagemaker logs]: sagemaker-xgboost-sentiment-classification/sklearn-xgboost-sentiment-classification/inference-pipeline/train/batch_train2.csv: Failed to parse input as CSV: bare " in non quoted field found near: pine kernels and chickpeas - Yum!; ""Tarama"" - tastefully smooth!; ""Pita bread"" - crisp deliciousness on the outside!; ""Village Greek Salad"" - super fresh!; ""Skinny Lamb Chops"" and ""Skinny Pork Chops"" - both chops needed more seasoning
```

I understand that the issue is parsing the csv. My questions are:
1) why is this not happening when a transform job is initially run on container 1 (the preprocessor)?
2) How should I save the csv file to work? Or, how can I change my `input_fn` to deal with this issue? I would use json, but the xgboost algorithm only takes `text/csv`. 

Here is my `input_fn`:

```
def input_fn(input_data, content_type):
    """Parse input data payload

    We currently only take csv input. Since we need to process both labelled
    and unlabelled data we first determine whether the label column is present
    by looking at how many columns were provided.
    """
    if content_type == 'text/csv':
        # Read the raw input data as CSV.
        df = pd.read_csv(StringIO(input_data), header=None, encoding='utf-8')
        
        if len(df.columns) == len(feature_columns_names) + 1:
            # This is a labelled example, includes the label column
            df.columns = feature_columns_names + [label_column]
        elif len(df.columns) == len(feature_columns_names) + 2:
            # This is labelled data with class weights
            df.columns = feature_columns_names + [label_column] + [weights_column]
        elif len(df.columns) == len(feature_columns_names):
            # This is an unlabelled example with no weights
            df.columns = feature_columns_names

        return df
    else:
        raise ValueError("{} not supported by script!".format(content_type))
```

**Comment by Aloha106** [comment]
> "why is this not happening when a transform job is initially run on container 1 (the preprocessor)?"
Are these two jobs have the same configurations? Could you share the DataProcessing configuration in both jobs and the complete CSV line that has parsing issue?

**Comment by DanyalAndriano** [comment]
Here is the config for the first transformation:
```
transformer = sklearn_preprocessor.transformer(
    instance_count=1, 
    instance_type='ml.c5.xlarge',
    assemble_with = 'Line',
    max_payload = 35,
    accept = 'text/csv')
transformer.transform(train_data, content_type='text/csv')
```
And the second:
```
transformer = sagemaker.transformer.Transformer(
    model_name = model_name,
    instance_count = 1,
    instance_type = 'ml.m4.xlarge',
    strategy = 'SingleRecord',
    assemble_with = 'Line',
    max_payload = 40,
    output_path = output_data_path,
    base_transform_job_name='serial-inference-batch',
    sagemaker_session=sagemaker_session,
    accept = CONTENT_TYPE_CSV)

transformer.transform(data = batch_input, 
                      job_name = job_name,
                      content_type = CONTENT_TYPE_CSV, 
                      split_type = 'Line',
                      join_source='Input')
```
The second is being run on the entire inference pipeline: container1 (preprocessor) + container2 (xgboost). 

The full csv line:
`"Enjoyed a feast of quality, freshly prepared Greek food:  ""Fried Halloumi"" - always a favourite!; ""Zucchini Fries"" - crispy and lightly seasoned, seriously addictive!;  ""Hummus Loaded"" - what an elevation of textures and taste with the added ingredients of pomegranate, feta, red onion, pine kernels and chickpeas - Yum!;  ""Tarama"" - tastefully smooth!;  ""Pita bread"" - crisp deliciousness on the outside!;  ""Village Greek Salad"" - super fresh!;  ""Skinny Lamb Chops"" and ""Skinny Pork Chops"" - both chops needed more seasoning, though perhaps this may have impeded on the taste of their secret tangy chop dip. The chops also needed more grill colour; It was served with the best tasting chips! - sorry Steers!;  ""King Prawns"" - Perfectly grilled and succulent!  For dessert, we had the ""Corrugated Baklava"" - a reconstructed version of the traditional baklava. Texturally, there was too much crunch of the corrugated phyllo pastry along with the chopped mixed nuts. It would have been far too dry without the vanilla ice cream. I prefer the compact traditional baklava rolls, which they also serve.  Overall a fabulous generously portioned delicious feast, superb service, warm and hospitable ambience as well as great value overall!  I will definitely return to try out the rest of the menu, along with their current ""Nikos Dozen"" Queen Prawn Special - 13 (Yes - 13!) Queen Prawns served with chips for R140 only!!! (This special is exclusive to Alice Lane, Sandton)  There's safe and secure parking in the same building block as the restaurant. The parking entrance is on Alice Lane. Plentiful and delicious!"`

**Comment by andremoeller** [comment]
Hey @DanyalAndriano ,

It seems like the CSV parser is failing to understand the double double quotes `""` -- would you be able to filter them out, or replace them by single double quotes? You could do this with a `def output_fn` to post-process the data and replace `""` with `"`.

**Comment by hsl89** [comment]
Dear SageMaker Community,
                 In our attempts to provide this repository with a better level of support                 going forward, we’re closing issues that were opened prior to the v2 release of the SDK.                 This is because we believe that over time many of the issues                 posted were solved with the latest release or other recent changes to the repo.                 This will help us reallocate resources towards issues that are                more likely to still be relevant today.                Some of the issues experienced now can be resolved by referencing the                v2 guide: https://sagemaker.readthedocs.io/en/stable/v2.html                 In this guide, you can find simple solutions to common notebook errors,                 like the renaming of parameters and classes.                If you believe your issue is still ongoing and you have updated error                messaging or other info, please re-open it, and we investigate the issue.
                Best Regards,
                AWS SageMaker Team

**Comment by oleg131** [comment]
I still have this in 2023
