### ISSUE TITLE
PyTorch Neo Compilation version

### ISSUE THREAD

**Issue by austinmw** [aws/amazon-sagemaker-examples#900]
Now that the the PyPi version of PyTorch is at v1.3.0, does Neo compilation still require rolling all the way back to v0.4.0? 

If so, is there any ETA for when this will be updated? I think this versioning issue is preventing a lot of people from making any use of this feature.

**Comment by hcho3** [comment]
@austinmw I agree that `pytorch_torchvision` is not terribly useful. Neo service currently supports PyTorch 1.0, and we are planning to add support for PyTorch 1.2 in a few weeks. Let us add example notebooks that use PyTorch 1.0.

**Comment by hsl89** [comment]
Dear SageMaker Community,
                 In our attempts to provide this repository with a better level of support                 going forward, we’re closing issues that were opened prior to the v2 release of the SDK.                 This is because we believe that over time many of the issues                 posted were solved with the latest release or other recent changes to the repo.                 This will help us reallocate resources towards issues that are                more likely to still be relevant today.                Some of the issues experienced now can be resolved by referencing the                v2 guide: https://sagemaker.readthedocs.io/en/stable/v2.html                 In this guide, you can find simple solutions to common notebook errors,                 like the renaming of parameters and classes.                If you believe your issue is still ongoing and you have updated error                messaging or other info, please re-open it, and we investigate the issue.
                Best Regards,
                AWS SageMaker Team
