### ISSUE TITLE
gluon_recommender_system: Command to copy review data from S3 fails due to S3 permissions

### ISSUE THREAD

**Issue by rizblie** [aws/amazon-sagemaker-examples#901]
In the 3rd cell, the instruction
!aws s3 cp s3://amazon-reviews-pds/tsv/amazon_reviews_us_Digital_Video_Download_v1_00.tsv.gz /tmp/recsys/

fails with
fatal error: An error occurred (403) when calling the HeadObject operation: Forbidden

This is due to the way the permissions are set on the S3 object - which allows unauthenticated access but fails if the customer is authenticated!

This is probably best fixed by fixing the S3 permissions for this object. Alternatively a workaround is to add the following option to the s3 cp instruction:
--no-sign-request

**Comment by hsl89** [comment]
Dear SageMaker Community,
                 In our attempts to provide this repository with a better level of support                 going forward, we’re closing issues that were opened prior to the v2 release of the SDK.                 This is because we believe that over time many of the issues                 posted were solved with the latest release or other recent changes to the repo.                 This will help us reallocate resources towards issues that are                more likely to still be relevant today.                Some of the issues experienced now can be resolved by referencing the                v2 guide: https://sagemaker.readthedocs.io/en/stable/v2.html                 In this guide, you can find simple solutions to common notebook errors,                 like the renaming of parameters and classes.                If you believe your issue is still ongoing and you have updated error                messaging or other info, please re-open it, and we investigate the issue.
                Best Regards,
                AWS SageMaker Team
