### ISSUE TITLE
LDA-Science.ipynb generate_griffiths_data() error

### ISSUE THREAD

**Issue by yibeichenmcdermott** [aws/amazon-sagemaker-examples#902]
I was running the example and cannot proceed at this line:

`known_alpha, known_beta, documents, topic_mixtures = generate_griffiths_data(
    num_documents=num_documents, num_topics=10)`

Here is the output:

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-5-b8fb4c0de8c1> in <module>()
      2 num_documents = 6000
      3 known_alpha, known_beta, documents, topic_mixtures = generate_griffiths_data(
----> 4     num_documents=num_documents, num_topics=10)
      5 # num_topics, vocabulary_size = known_beta.shape
      6 

~/SageMaker/lda_topic_modeling_2019-10-11/generate_example_data.py in generate_griffiths_data(num_documents, average_document_length, num_topics, alpha, eta, seed)
    112             topic_index = np.argmax(word_topic)
    113             topic_word_distribution = beta[topic_index]
--> 114             word = sp.stats.multinomial.rvs(1, topic_word_distribution, size=1).reshape(vocabulary_size)
    115             documents[m] += word
    116 

~/anaconda3/envs/mxnet_p36/lib/python3.6/site-packages/scipy/stats/_multivariate.py in rvs(self, n, p, size, random_state)
   3218         n, p, npcond = self._process_parameters(n, p)
   3219         random_state = self._get_random_state(random_state)
-> 3220         return random_state.multinomial(n, p, size)
   3221 
   3222 

mtrand.pyx in numpy.random.mtrand.RandomState.multinomial()

common.pyx in numpy.random.common.check_array_constraint()

ValueError: pvals < 0, pvals > 1 or pvals contains NaNs

**Comment by lefnire** [comment]
Same issue

**Comment by lefnire** [comment]
Possible lead: [numpy.random.mtrand.RandomState.multinomial](https://numpy.org/doc/1.17/reference/random/generated/numpy.random.mtrand.RandomState.multinomial.html)

> The probability inputs should be normalized. As an implementation detail, the value of the last entry is ignored and assumed to take up any leftover probability mass, but this should not be relied on. A biased coin which has twice as much weight on one side as on the other should be sampled like so:

```python
>>> np.random.multinomial(100, [1.0 / 3, 2.0 / 3])  # RIGHT
array([38, 62]) # random
```

> not like:

```python
>>> np.random.multinomial(100, [1.0, 2.0])  # WRONG
Traceback (most recent call last):
ValueError: pvals < 0, pvals > 1 or pvals contains NaNs
```

If I `print(topic_word_distribution)` [generate_example_data.py#L114](https://github.com/awslabs/amazon-sagemaker-examples/blob/master/introduction_to_amazon_algorithms/lda_topic_modeling/generate_example_data.py#L114), it seems normalized: https://gist.github.com/lefnire/ad710182a847efcf29a1ce71fa80971b

**Comment by Robinspecteur** [comment]
I've found a solution here: https://www.e-learn.cn/topic/2637790
From what I gather, this has to do with numpy casting implicitly the values... Not sure about the details, but this works:
```for m in range(num_documents):
        document_length = document_lengths[m]
        theta = thetas[m]
        **theta = np.asarray(theta).astype('float64')
        theta = theta / np.sum(theta)**
        topic = sp.stats.multinomial.rvs(1, theta, size=document_length)  # precompute topics for performance
        # generate word counts within document
        for n in range(document_length):
            word_topic = topic[n]
            topic_index = np.argmax(word_topic)
            topic_word_distribution = beta[topic_index]
            **topic_word_distribution = np.asarray(topic_word_distribution).astype('float64')
            topic_word_distribution = topic_word_distribution / np.sum(topic_word_distribution)**
            word = sp.stats.multinomial.rvs(1, topic_word_distribution, size=1).reshape(vocabulary_size)
            documents[m] += word```
The lines I added are in bold.

**Comment by premsridhar** [comment]
hi, I am still getting issues. Is there any solution to this?

**Comment by zorrofox** [comment]
I have some workaround for this issue to normalize the np array in [line 104](https://github.com/awslabs/amazon-sagemaker-examples/blob/d7cc61826e8ebf13fdddb576b93e445d3b15a60b/introduction_to_amazon_algorithms/ntm_synthetic/generate_example_data.py#L104) and [line 111](https://github.com/awslabs/amazon-sagemaker-examples/blob/d7cc61826e8ebf13fdddb576b93e445d3b15a60b/introduction_to_amazon_algorithms/ntm_synthetic/generate_example_data.py#L111).

Line 104:
```
theta = thetas[m] / np.sum(thetas[m])
```

Line 111:
```
topic_word_distribution = beta[topic_index] / np.sum(beta[topic_index])
```

**Comment by austinlasseter** [comment]
@zorrofox -- I attempted the workaround you suggested in `generate_example_data.py` but I continue to get the same error.

**Comment by zorrofox** [comment]
@austinlasseter Do you restart the Jupyter Kernel?

**Comment by duderevolucion** [comment]
For reference, the error noted at the beginning of this thread:
    ValueError: pvals < 0, pvals > 1 or pvals contains NaNs

This error is caused by a floating point precision issue in the script.  This causes in some instances the topic-word distributions not to sum to 1.0 prior to calling scipy.stats.multinomial.rvs.  

A fixed version of this script can be found at https://github.com/duderevolucion/aws-sagemaker-lda-example.  That repository also contains an updated version of the lda example in https://github.com/awslabs/amazon-sagemaker-examples that works with the Sagemaker Python SDK Version 2.x.

**Comment by haratyma** [comment]
@duderevolucion thanks works now!
