### ISSUE TITLE
mleap Jar will stop sparking working on Zeppelin notebook

### ISSUE THREAD

**Issue by greatzt** [aws/amazon-sagemaker-examples#909]
After I follow the following steps to add mleap jar to /usr/lib/spark/jars,  the spark session can be created on Zeppelin notebook or Jupyter notebook which is connect to EMR.  The EMR release I am using is 5.27 and Spark version is 2.4.4. can anyone help?

You need to have the MLeap JAR in the classpath to be successfully able to use it during model serialization. Please download the JAR (it is an assembly/fat JAR) from the following link using wget:

https://s3-us-west-2.amazonaws.com/sparkml-mleap/0.9.6/jar/mleap_spark_assembly.jar

and put it in /usr/lib/spark/jars in all the nodes.

**Comment by ChoiByungWook** [comment]
Hello @greatzt,

Apologies for the late response.

Would it possible for you to provide a reference/link to the documentation that you are following?

Thanks!

**Comment by greatzt** [comment]
> Hello @greatzt,
> 
> Apologies for the late response.
> 
> Would it possible for you to provide a reference/link to the documentation that you are following?
> 
> Thanks!

the link is https://github.com/awslabs/amazon-sagemaker-examples/blob/master/sagemaker-python-sdk/sparkml_serving_emr_mleap_abalone/sparkml_serving_emr_mleap_abalone.ipynb

**Comment by hsl89** [comment]
Dear SageMaker Community,
                 In our attempts to provide this repository with a better level of support                 going forward, we’re closing issues that were opened prior to the v2 release of the SDK.                 This is because we believe that over time many of the issues                 posted were solved with the latest release or other recent changes to the repo.                 This will help us reallocate resources towards issues that are                more likely to still be relevant today.                Some of the issues experienced now can be resolved by referencing the                v2 guide: https://sagemaker.readthedocs.io/en/stable/v2.html                 In this guide, you can find simple solutions to common notebook errors,                 like the renaming of parameters and classes.                If you believe your issue is still ongoing and you have updated error                messaging or other info, please re-open it, and we investigate the issue.
                Best Regards,
                AWS SageMaker Team
