### ISSUE TITLE
How to load a trained SM model object from S3 back into my Jupyter Lab?

### ISSUE THREAD

**Issue by konradsemsch** [aws/amazon-sagemaker-examples#911]
Let's say I have successfully executed the training job and the model object is now stored on S3. But let's say that I has to close my JL session then and after a couple of days I wanted to go back to my modelling exercise and validate the model using the Batch Transform API or just do any predictions on the model. How can I load back this model object into my JL session without the need of retraining it?

Could you point me to some resources where this is described? So far I was only able to find ones where the e.g.: ```sklearn``` model object is being worked with in a single JL session.

**Comment by dleen** [comment]
Hi @konradsemsch,

You are correct that you should not need to retrain to reload the model object. The process should be the same as loading an existing model. This is described here: https://sagemaker.readthedocs.io/en/stable/overview.html#byo-model

Thanks for using Sagemaker!

**Comment by hsl89** [comment]
Dear SageMaker Community,
                 In our attempts to provide this repository with a better level of support                 going forward, we’re closing issues that were opened prior to the v2 release of the SDK.                 This is because we believe that over time many of the issues                 posted were solved with the latest release or other recent changes to the repo.                 This will help us reallocate resources towards issues that are                more likely to still be relevant today.                Some of the issues experienced now can be resolved by referencing the                v2 guide: https://sagemaker.readthedocs.io/en/stable/v2.html                 In this guide, you can find simple solutions to common notebook errors,                 like the renaming of parameters and classes.                If you believe your issue is still ongoing and you have updated error                messaging or other info, please re-open it, and we investigate the issue.
                Best Regards,
                AWS SageMaker Team
