### ISSUE TITLE
Documentation - Missing Image

### ISSUE THREAD

**Issue by jeffbarr** [aws/amazon-sagemaker-examples#920]
In machine_learning_workflow_abalone.ipynb , the section "Building a machine learning workflow" starts with the text "e2e_pipeline.png" . This looks like a formatting error; the image is in the source code but is not displayed.

**Comment by shunjd** [comment]
Hi Jeff,

It appears that we cannot see the "e2e_pipeline.png" when previewing the [notebook](https://github.com/awslabs/amazon-sagemaker-examples/blob/master/step-functions-data-science-sdk/machine_learning_workflow_abalone/machine_learning_workflow_abalone.ipynb) on github. But if we open the notebook in Jupyter notebook either locally or on SageMaker, the image is there.

Thanks,
Shunjia

**Comment by vladdoster** [comment]
@jeffbarr & @shunjd,

I fixed the issue I think. I have opened a PR.

**Comment by hsl89** [comment]
Dear SageMaker Community,
                 In our attempts to provide this repository with a better level of support                 going forward, we’re closing issues that were opened prior to the v2 release of the SDK.                 This is because we believe that over time many of the issues                 posted were solved with the latest release or other recent changes to the repo.                 This will help us reallocate resources towards issues that are                more likely to still be relevant today.                Some of the issues experienced now can be resolved by referencing the                v2 guide: https://sagemaker.readthedocs.io/en/stable/v2.html                 In this guide, you can find simple solutions to common notebook errors,                 like the renaming of parameters and classes.                If you believe your issue is still ongoing and you have updated error                messaging or other info, please re-open it, and we investigate the issue.
                Best Regards,
                AWS SageMaker Team
