### ISSUE TITLE
[Question] By default, does hosting Sagemaker endpoint handles parallel requests?

### ISSUE THREAD

**Issue by velociraptor111** [aws/amazon-sagemaker-examples#923]
When there are multiple concurrent InvokeEndpoint requests being called to a deployed AWS Sagemaker endpoint, how is it being handled?

I have deployed an endpoint with a P3.2xlarge instance. Currently one job takes around ~45 seconds to process. I have tried sending 4 different InvokeEndpoint requests at the same time and I noticed from CloudWatch logs that the jobs are being done serially depending on which request arrives first. ~~I suspect there is some sort of queue internally within the server model itself.~~

I am aware of automatic scaling as described here: https://aws.amazon.com//blogs/machine-learning/load-test-and-optimize-an-amazon-sagemaker-endpoint-using-automatic-scaling/ but my question is by default does aws sagemaker not allow concurrent requests being handled at the same time?

## UPDATE
Upon further investigation and testing here are some additional information. 
I have deployed an ml.m4xlarge instance that simply sleeps for 45 seconds inside the transform function. Looks somewhat like

```python
def transform_fn(model, request_body, content_type, accept_type):       
    request_body_dict = json.loads(request_body)
    time.sleep(45)
    ...
```

Furthermore, I have set the server timeout to be 420 seconds like so. 
```python
sagemaker_model = MXNetModel(model_data = 's3://' + sagemaker_session.default_bucket() + '/model/yolo_object_person_detector.tar.gz',
                             role = role, 
                             entry_point = 'load_testing_entrypoint.py',
                             py_version='py3',
                             framework_version='1.4.1',
                             sagemaker_session = sagemaker_session,
                            env = {'SAGEMAKER_MODEL_SERVER_TIMEOUT' : '420' })

predictor = sagemaker_model.deploy(
                            initial_instance_count=1,
                            instance_type='ml.m4.xlarge',
                            endpoint_name='load-testing')
```

I tried sending 9 consecutive requests and monitored how they are being executed and what I've found is that there is no specific order in which the requests are being handled.

A few questions I have from this experiment is:
1) Does AWS Sagemaker not process requests concurrently? Meaning, I would expect the server being able to handle two requests at the same time?
2) From the client's side, how is it handling the case when the server is busy? I notice that it internally does retries for about 3 times after every 60 seconds if the request is not being handled
3) Within each of the 60 seconds time window, how is the client code calling the Endpoint? Is it constantly calling after every 1,2,4,6,8 seconds ? 

Here is the client side code 
```python
sagemaker_client = boto3.client('sagemaker-runtime')
response = sagemaker_client.invoke_endpoint(EndpointName='load-testing',Body=request_body)
```

**Comment by hsl89** [comment]
Dear SageMaker Community,
                 In our attempts to provide this repository with a better level of support                 going forward, we’re closing issues that were opened prior to the v2 release of the SDK.                 This is because we believe that over time many of the issues                 posted were solved with the latest release or other recent changes to the repo.                 This will help us reallocate resources towards issues that are                more likely to still be relevant today.                Some of the issues experienced now can be resolved by referencing the                v2 guide: https://sagemaker.readthedocs.io/en/stable/v2.html                 In this guide, you can find simple solutions to common notebook errors,                 like the renaming of parameters and classes.                If you believe your issue is still ongoing and you have updated error                messaging or other info, please re-open it, and we investigate the issue.
                Best Regards,
                AWS SageMaker Team

**Comment by naveen-marthala** [comment]
@velociraptor111, Now that v2 of SDK is out, could you learn how concurrent requests are being handled?
