### ISSUE TITLE
ML preprocessing code where to store and how to access it for both training and testing

### ISSUE THREAD

**Issue by gsandy9** [aws/amazon-sagemaker-examples#928]
Hello,

I am working on building an ML pipeline that would retrain the model every day and would make predictions.

- First, I wrote the preprocessing code (which does not use any scikit learn functions) that would transform my data and store the data on s3. 
- For the training, I am planning to use a simple Decision tree by using the prebuilt scikit learn container.

I am confused about how to use the preprocessing script for both training and inference to create a pipeline.

Sources looked into:

- [Scikit learn inference pipeline](https://github.com/awslabs/amazon-sagemaker-examples/tree/master/sagemaker-python-sdk/scikit_learn_inference_pipeline) - In this example, they have built a pipeline by creating a model for preprocessing and model for training.

**Comment by hsl89** [comment]
Dear SageMaker Community,
                 In our attempts to provide this repository with a better level of support                 going forward, we’re closing issues that were opened prior to the v2 release of the SDK.                 This is because we believe that over time many of the issues                 posted were solved with the latest release or other recent changes to the repo.                 This will help us reallocate resources towards issues that are                more likely to still be relevant today.                Some of the issues experienced now can be resolved by referencing the                v2 guide: https://sagemaker.readthedocs.io/en/stable/v2.html                 In this guide, you can find simple solutions to common notebook errors,                 like the renaming of parameters and classes.                If you believe your issue is still ongoing and you have updated error                messaging or other info, please re-open it, and we investigate the issue.
                Best Regards,
                AWS SageMaker Team
