### ISSUE TITLE
Tensorflow BYOM utilities incompatible with TF2.0

### ISSUE THREAD

**Issue by nikdin** [aws/amazon-sagemaker-examples#931]
Working through the example here:

https://github.com/awslabs/amazon-sagemaker-examples/tree/master/advanced_functionality/tensorflow_bring_your_own

One of the utility scripts breaks with TF2.0:

https://github.com/awslabs/amazon-sagemaker-examples/blob/master/advanced_functionality/tensorflow_bring_your_own/utils/generate_cifar10_tfrecords.py

This is due to some changes in the io package. 

Line 88 should be: 
{code}
with tf.io.gfile.GFile(filename, 'rb') as f:
{code}

Line 99 should be:
{code}
 with tf.io.TFRecordWriter(output_file) as record_writer:
{code}

**Comment by ChuyangDeng** [comment]
Hi @nikdin, thanks for using SageMaker, we currently do not support TensorFlow 2.0 yet. But it will be supported soon.

Thanks!

**Comment by hsl89** [comment]
Dear SageMaker Community,
                 In our attempts to provide this repository with a better level of support                 going forward, we’re closing issues that were opened prior to the v2 release of the SDK.                 This is because we believe that over time many of the issues                 posted were solved with the latest release or other recent changes to the repo.                 This will help us reallocate resources towards issues that are                more likely to still be relevant today.                Some of the issues experienced now can be resolved by referencing the                v2 guide: https://sagemaker.readthedocs.io/en/stable/v2.html                 In this guide, you can find simple solutions to common notebook errors,                 like the renaming of parameters and classes.                If you believe your issue is still ongoing and you have updated error                messaging or other info, please re-open it, and we investigate the issue.
                Best Regards,
                AWS SageMaker Team
