### ISSUE TITLE
Notebook simplification

### ISSUE THREAD

**Issue by jigsaw004** [aws/amazon-sagemaker-examples#944]
1. https://github.com/awslabs/amazon-sagemaker-examples/blob/714652a4f96fd764a247a4cee30425293db86c59/sagemaker-debugger/mnist_tensor_analysis/mnist_tensor_analysis.ipynb#L144-L151

The above lines attempt to just get the training job name and they aren't downloading tensors as the print statement indicates. 
```
estimator.latest_training_job.describe()
```
should suffice to describe the training job instead of getting the client.

2. https://github.com/awslabs/amazon-sagemaker-examples/blob/714652a4f96fd764a247a4cee30425293db86c59/sagemaker-debugger/mnist_tensor_analysis/mnist_tensor_analysis.ipynb#L171

can be simplified to
```
estimator.latest_job_debugger_artifacts_path()
```

**Comment by hsl89** [comment]
Dear SageMaker Community,
                 In our attempts to provide this repository with a better level of support                 going forward, we’re closing issues that were opened prior to the v2 release of the SDK.                 This is because we believe that over time many of the issues                 posted were solved with the latest release or other recent changes to the repo.                 This will help us reallocate resources towards issues that are                more likely to still be relevant today.                Some of the issues experienced now can be resolved by referencing the                v2 guide: https://sagemaker.readthedocs.io/en/stable/v2.html                 In this guide, you can find simple solutions to common notebook errors,                 like the renaming of parameters and classes.                If you believe your issue is still ongoing and you have updated error                messaging or other info, please re-open it, and we investigate the issue.
                Best Regards,
                AWS SageMaker Team
