### ISSUE TITLE
DeepAR Electricity Example Output File

### ISSUE THREAD

**Issue by Teleklatz** [aws/amazon-sagemaker-examples#963]
What is the best possible way to predict all the timeseries values and store it on a CSV/JSON file as an output?

**Comment by vafl** [comment]
The easiest way to predict all time series is to a sagemaker batch transformation:

https://docs.aws.amazon.com/sagemaker/latest/dg/deepar-in-formats.html

The output is in json lines format.

**Comment by hsl89** [comment]
Dear SageMaker Community,
                 In our attempts to provide this repository with a better level of support                 going forward, we’re closing issues that were opened prior to the v2 release of the SDK.                 This is because we believe that over time many of the issues                 posted were solved with the latest release or other recent changes to the repo.                 This will help us reallocate resources towards issues that are                more likely to still be relevant today.                Some of the issues experienced now can be resolved by referencing the                v2 guide: https://sagemaker.readthedocs.io/en/stable/v2.html                 In this guide, you can find simple solutions to common notebook errors,                 like the renaming of parameters and classes.                If you believe your issue is still ongoing and you have updated error                messaging or other info, please re-open it, and we investigate the issue.
                Best Regards,
                AWS SageMaker Team
