### ISSUE TITLE
How DeepAR handles non-continuous time stamps

### ISSUE THREAD

**Issue by tqdo** [aws/amazon-sagemaker-examples#966]
My data is hourly stock price. There is no missing values but everyday the data is only available from 10am to 4pm hourly. So there is a gap in the time stamps between 2 days (from 4pm until 10am the next day). 

Just curious how does DeepAR handle this type of data? Does it consider the gap in time stamps missing values? I don't want to just consider them hourly data starting from the 'start' time because I think the exact time stamp affects how DeepAR generates derived features.

**Comment by vafl** [comment]
DeepAR, currently does not support this. Your best bet is probably to use gluonts (I see you opened a similar issue there) and adapt the transformations/networks to your use case.

**Comment by hsl89** [comment]
Dear SageMaker Community,
                 In our attempts to provide this repository with a better level of support                 going forward, we’re closing issues that were opened prior to the v2 release of the SDK.                 This is because we believe that over time many of the issues                 posted were solved with the latest release or other recent changes to the repo.                 This will help us reallocate resources towards issues that are                more likely to still be relevant today.                Some of the issues experienced now can be resolved by referencing the                v2 guide: https://sagemaker.readthedocs.io/en/stable/v2.html                 In this guide, you can find simple solutions to common notebook errors,                 like the renaming of parameters and classes.                If you believe your issue is still ongoing and you have updated error                messaging or other info, please re-open it, and we investigate the issue.
                Best Regards,
                AWS SageMaker Team
