### ISSUE TITLE
Links are Broken in XGBoost Debugger Notebooks

### ISSUE THREAD

**Issue by jaredleekatzman** [aws/amazon-sagemaker-examples#972]
https://github.com/awslabs/amazon-sagemaker-examples/blob/714652a4f96fd764a247a4cee30425293db86c59/sagemaker-debugger/xgboost_realtime_analysis/xgboost-realtime-analysis.ipynb#L97-L98

The link to the XGBoost Classification notebooks are broken. The correct link should probably be: https://github.com/awslabs/amazon-sagemaker-examples/blob/master/introduction_to_amazon_algorithms/xgboost_mnist/xgboost_mnist.ipynb

**Comment by mchoi8739** [comment]
The link is based off of a commit.
In the actual notebook in the master branch, the XGBoost clssification notebook link works fine.

https://github.com/aws/amazon-sagemaker-examples/blob/master/sagemaker-debugger/xgboost_realtime_analysis/xgboost-realtime-analysis.ipynb
