### ISSUE TITLE
factorization-machine

### ISSUE THREAD

**Issue by araitats** [aws/amazon-sagemaker-examples#990]
amazon-sagemaker-examples/introduction_to_amazon_algorithms/factorization_machines_mnist/factorization_machines_mnist.ipynb

Score and Predicted_label return the same value. 
e.g.
{'predictions': [{'score': 0.0, 'predicted_label': 0.0}]}

Score should be a continuous value between [0, 1] representing the probability being a 0 or not in this case.

**Comment by ehsanmok** [comment]
@araitats thanks for reporting the issue! please checkout the PR that clarifies the explanations.

**Comment by paul-cb** [comment]
Closed. This has been mentioned and fixed here https://github.com/aws/amazon-sagemaker-examples/pull/991.
